### ISSUE TITLE
One PC, two android phones,how can control these phones

### ISSUE THREAD

**Issue by niuniudd** [selendroid/selendroid#1007]
I connect 2 android phones in a coumupter
I start server on PC，the server found these phones

I create a driver object from the below codes

desired_capabilities1 = {'aut':'com.XXX.XXX:1.0.1.223'}
driver1 = webdriver.Remote(desired_capabilities=desired_capabilities1)

adb devices
List of devices attached
13f8d00b        device
ca5ed6d6        device

I can`t set the ID for android phone for the object:driver1

How can I create a webdriver object for the device：13f8d00b ？PLS help me，ths

**Comment by niuniudd** [comment]
Sorry,I found method:update desired_capabilities values,I close the issue

**Comment by metasonic** [comment]
can you please add an example?

**Comment by niuniudd** [comment]
self.capabilities = DesiredCapabilities.ANDROID.copy()
self.capabilities['browserName']='selendroid'
self.capabilities['serial']=self.deviceId
self.capabilities['aut'] = '%s'%appId
you change [‘serial’] to connect different device，and change [‘aut’] to test different app
