### ISSUE TITLE
Cannot able to find elements of 2nd application which is opened from 1st application using selendroid

### ISSUE THREAD

**Issue by LohitRaj** [selendroid/selendroid#1010]
_Selendroid library used: **selendroid-standalone-0.17.0-with-dependencies.jar**_
_Framework used to launch session: **Appium v1.4.16**_

**Procedure Followed:**
1. Launched "Application 1", using desired capabilities of Appium,
2. Navigated to GridView of Icons which launch other applications,
3. Clicked to open "Application 2",
4. Trying to find elements on the "Application 2" using below syntax:
`driver.findElement(By.id("homeicon"));`
5. Got error in the Appium log as follows:
> info: --> POST /wd/hub/session/5ec7c1d8-a94e-a3f7-1511-3036fc18229e/element {"using":"id","value":"homeicon"}
info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/5ec7c1d8-a94e-a3f7-1511-3036fc18229e/element","method":"POST","json":{"using":"id","value":"homeicon"}}
info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"Element was not found."},"sessionId":"5ec7c1d8-a94e-a3f7-1511-3036fc18229e"}
info: <-- POST /wd/hub/session/5ec7c1d8-a94e-a3f7-1511-3036fc18229e/element 500 50163.063 ms - 201

Please note that the action indicated above can be performed using **UIAutomator** but cannot be performed with _Selendroid_ using same Appium version. 
As we want to make it work on lower version of android devices, need it to make work using Selendroid on Appium.

Any Help will be of great help thanks..
Let me know if need more information regarding this...

**Comment by lukeis** [comment]
this is not going to be possible with selendroid because it currently uses Android's Instrumentation framework. This is limited to running against one app at a time. So this is use case is not feasible, so I'm going to close this issue.

Some are trying to work on bringing UIAutomator2 to selendroid, but that may take a while.

**Comment by LohitRaj** [comment]
Thanks @lukeis for the info..
