### ISSUE TITLE
two selendroid server in the same coumputer,I have 2 phones,how can i control the 1st phone connect the 1st server,the 2nd phone connect the 2nd server

### ISSUE THREAD

**Issue by niuniudd** [selendroid/selendroid#1014]
when I start server ,the 1st server`s port is 4444,the 2nd server `port is 4445,I have 2 phones ,id are 12345,67890,how can i control the phone 12345 connect the 1st server,the phone 67890 connect the 2nd server 
![image](https://cloud.githubusercontent.com/assets/14904226/11579210/ef962742-9a66-11e5-8280-95ab2db4dcb0.png)

**Comment by lukeis** [comment]
connect to the port it's started on?

Other options include specifying the "serial" capability to specify the individual device you want to connect to (and use just one selendroid server).

closing since this is not an 'issue'
