### ISSUE TITLE
Error building server: An error occurred while resigning the app

### ISSUE THREAD

**Issue by thejaswi28** [selendroid/selendroid#1015]
Hi All,

My JAVA_HOME is set and ANDROID_HOME is also set. 
I am still getting the error while running the server using the below command line

java -jar selendroid-standalone-0.15.0-with-dependencies.jar -app MYAPP.apk 

D:\FSTP Automation>java -jar selendroid-standalone-0.15.0-with-dependencies.jar
-app MYAPP.apk
Dec 04, 2015 5:13:18 PM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Selendroid #################
Dec 04, 2015 5:13:20 PM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Configuration in use #################
Dec 04, 2015 5:13:20 PM io.selendroid.standalone.SelendroidLauncher main
INFO: io.selendroid.standalone.SelendroidConfiguration@87aac27[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[MYAPP.apk]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  keystorePassword=<null>
  keystoreAlias=<null>
  emulatorOptions=<null>
  keepEmulator=false
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  maxSession=5
  maxInstances=5
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
  deviceLog=true
  serverStartTimeout=20000
  printHelp=false
  serverStartRetries=5
  folder=<null>
]
Dec 04, 2015 5:13:20 PM io.selendroid.standalone.SelendroidLauncher launchServer

INFO: Starting Selendroid standalone on port 4444
Dec 04, 2015 5:13:20 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: D:\AndroidStudio-sdk\build-tools\23.0.1\aapt.exe
remove D:\FSTP Automation\MYAPP.apk META-INF/MANIFEST.MF
Dec 04, 2015 5:13:21 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: D:\AndroidStudio-sdk\build-tools\23.0.1\aapt.exe
remove D:\FSTP Automation\MYAPP.apk META-INF/CERT.RSA
Dec 04, 2015 5:13:21 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: D:\AndroidStudio-sdk\build-tools\23.0.1\aapt.exe
remove D:\FSTP Automation\MYAPP.apk META-INF/CERT.SF
Dec 04, 2015 5:13:22 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: D:\AndroidStudio-sdk\build-tools\23.0.1\aapt.exe
remove D:\FSTP Automation\MYAPP.apk META-INF/ANDROIDD.SF
Dec 04, 2015 5:13:22 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: D:\AndroidStudio-sdk\build-tools\23.0.1\aapt.exe
remove D:\FSTP Automation\MYAPP.apk META-INF/ANDROIDD.RSA
Dec 04, 2015 5:13:23 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: D:\AndroidStudio-sdk\build-tools\23.0.1\aapt.exe
remove D:\FSTP Automation\MYAPP.apk META-INF/NDKEYSTO.SF
Dec 04, 2015 5:13:24 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: D:\AndroidStudio-sdk\build-tools\23.0.1\aapt.exe
remove D:\FSTP Automation\MYAPP.apk META-INF/NDKEYSTO.RSA
Dec 04, 2015 5:13:24 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Java\jdk1.8.0_60\bin\jarsigner.e
xe -sigalg MD5withRSA -digestalg SHA1 -signedjar D:\FSTP Automation\resigned-FST
PAPP_5197.apk -storepass android -keystore C:\Users\tejaswi_r\.android\debug.key
store D:\FSTP Automation\MYAPP.apk androiddebugkey
Dec 04, 2015 5:13:44 PM io.selendroid.standalone.SelendroidLauncher launchServer

SEVERE: Error building server: An error occurred while resigning the app 'FSTPAP
P_5197.apk'.
Exception in thread "main" io.selendroid.server.common.exceptions.SessionNotCrea
tedException: An error occurred while resigning the app 'MYAPP.apk'.
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addT
oAppsStore(SelendroidStandaloneDriver.java:123)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.init
ApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<ini
t>(SelendroidStandaloneDriver.java:94)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.initialize
SelendroidServer(SelendroidStandaloneServer.java:65)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(Sel
endroidStandaloneServer.java:54)
        at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLa
uncher.java:65)
        at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.j
ava:117)
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: Error exec
uting shell command: C:\Program Files\Java\jdk1.8.0_60\bin\jarsigner.exe -sigalg
 MD5withRSA -digestalg SHA1 -signedjar D:\FSTP Automation\resigned-MYAPP.
apk -storepass android -keystore C:\Users\tejaswi_r\.android\debug.keystore D:\F
STP Automation\MYAPP.apk androiddebugkey
        at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.signTestServ
er(SelendroidServerBuilder.java:294)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(Se
lendroidServerBuilder.java:153)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addT
oAppsStore(SelendroidStandaloneDriver.java:121)
        ... 6 more
Caused by: io.selendroid.standalone.exceptions.ShellCommandException:
        ... 10 more

Not able to find the reason. Can someone please help?

**Comment by operatiay** [comment]
can you try executing the command causing the issue? ```C:\Program Files\Java\jdk1.8.0_60\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar D:\FSTP Automation\resigned-MYAPP.apk -storepass android -keystore :\Users\tejaswi_r.android\debug.keystore D:\FSTP Automation\MYAPP.apk androiddebugkey```

maybe the white spaces are not a good idea to be used... (but it's just a guess)

**Comment by thejaswi28** [comment]
Hi, I checked and got the below error

Only one alias can be specified
Please type jarsigner -help for usage

**Comment by operatiay** [comment]
then can you try placing your app in a folder without white spaces?

**Comment by thejaswi28** [comment]
Now I am getting a different error

C:\Program Files\Java\jdk1.8.0_60\bin>jarsigner.exe -sigalg MD5withRSA -digestal
g SHA1 -signedjar D:\FSTPAutomation\resigned-FSTPAPP_5197.apk -storepass android
 -keystore :\Users\tejaswi_r.android\debug.keystore D:\FSTPAutomation\FSTPAPP_51
97.apk androiddebugkey
jarsigner error: java.lang.RuntimeException: keystore load: C:\Program Files\Jav
a\jdk1.8.0_60\bin\:\Users\tejaswi_r.android\debug.keystore (The filename, direct
ory name, or volume label syntax is incorrect)

**Comment by operatiay** [comment]
your -keystore parameter is missing the letter ```C```

**Comment by thejaswi28** [comment]
Hi,

Sorry for the delay. I am getting this exception. I have set my environment variables and jarsigner jar is present inside bin folder

C:\Program Files\Java\jdk1.8.0_60\bin>jarsigner.exe -sigalg MD5withRSA -digestal
g SHA1 -signedjar D:\FSTPAutomation\resigned-FSTPAPP_5197.apk -storepass android
 -keystore C:\Users\tejaswi_r.android\debug.keystore D:\FSTPAutomation\FSTPAPP_5
197.apk androiddebugkey
jarsigner error: java.lang.RuntimeException: keystore load: C:\Users\tejaswi_r.a
ndroid\debug.keystore (The system cannot find the path specified)

**Comment by operatiay** [comment]
follow the steps in this description: http://stackoverflow.com/a/4055893

check that the ```debug.keystore``` is located at the expected location.

**Comment by thejaswi28** [comment]
Hi, 

I don't know what was wrong. It started working all of a sudden now. I have not changed anything. Looks crazy!! Anyways thank you for your help :)

**Comment by lukeis** [comment]
:+1:

**Comment by niuniudd** [comment]
I also faced this problem，finally，I found the reason，because I didn·t set JAVA_HOME,and I added the path：D:\Program Files\Java\jdk1.7.0_07\bin，you must use %JAVA_HOME%\bin
