### ISSUE TITLE
how to navigate to android home screen in Selendroid

### ISSUE THREAD

**Issue by tankjason** [selendroid/selendroid#1020]
hi 
i'm trying to select "Play Store" which is on home screen but i couldn't navigate it to home screen so i cant either select "Play Store"
i tried below codes but didn't work. Please help me...
	new Actions(driver).sendKeys(SelendroidKeys.ANDROID_HOME).perform();
new Actions(driver).sendKeys(SelendroidKeys.MENU).perform();

**Comment by operatiay** [comment]
afaik this is not supported in Selendroid. Interaction is restricted to the specific app.

**Comment by lukeis** [comment]
There is a method SelendroidDriver.backgroundApp();  which is like going to the home screen.

From there your only option in selendroid is to send adb commands to perform any actions (but you won't be able to 'read' the state of the screen, you can only do that with the running app under test).

When you want to go back to your app, run SelendroidDriver.resumeApp();

**Comment by tankjason** [comment]
When I use that, it gives a error the method "backgroundApp() is undefined
for the Selendroid...
