### ISSUE TITLE
Selendroid how to re-sign the APK file when the apk file has signed 

### ISSUE THREAD

**Issue by angelliu** [selendroid/selendroid#1022]
I used the third APP on my device, but I want to auto testing it.
input the java -jar selendroid-standalone-0.17.0-with-dependencies.jar -app kwplayerhd.apk
the selendroid-standalone server has been started on 4444

code:
import sys
import unittest,HTMLTestRunner,time
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.touch_actions import TouchActions

class FindElementTest(unittest.TestCase):

    def setUp(self):
        desired_capabilities = {'aut':'cn.kuwo.kwmusiccar:2.1.1.0'}

        self.driver = webdriver.Remote(
            desired_capabilities=desired_capabilities
        )
        self.driver.implicitly_wait(30)

    def test_find_element_by_id(self):
        self.driver.get('and-activity://cn.kuwo.kwmusiccar.WelcomeActivity')
        self.assertTrue("and-activity://WelcomeActivity" in self.driver.current_url)
        quku = self.driver.find_element_by_id('radio_quku')
        quku.click()

    def tearDown(self):
        self.driver.quit()

if __name__ == '__main__':
    unittest.main()

        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: Failed

        ... 33 more

十二月 28, 2015 11:12:41 上午 io.selendroid.standalone.server.model.SelendroidSt
andaloneDriver createNewTestSession
信息: 'cn.kuwo.kwmusiccar:2.1.1.0' will be used as app under test.
十二月 28, 2015 11:12:41 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\Program Files\adt-bundle-windows-x86\adt-bundl
e-windows-x86-20131030\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell dump
sys power
十二月 28, 2015 11:12:42 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Shell command output
-->
Power Manager State:
  mIsPowered=false mPowerState=3 mScreenOffTime=6663820 ms
  mPartialCount=0
  mWakeLockState=
  mUserState=SCREEN_BRIGHT_BIT SCREEN_ON_BIT
  mPowerState=SCREEN_BRIGHT_BIT SCREEN_ON_BIT
  mLocks.gather=
  mNextTimeout=2153568267 now=6663823 2146904s from now
  mDimScreen=false mStayOnConditions=0 mPreparingForScreenOn=false mSkippedScree
nOn=false
  mScreenOffReason=0 mUserState=3
  mBroadcastQueue={-1,-1,-1}
  mBroadcastWhy={0,0,0}
  mPokey=0 mPokeAwakeonSet=false
  mKeyboardVisible=false mUserActivityAllowed=true
  mKeylightDelay=6000 mDimDelay=-1 mScreenOffDelay=2147483647
  mPreventScreenOn=false  mScreenBrightnessOverride=-1  mButtonBrightnessOverrid
e=-1
  mScreenOffTimeoutSetting=-1 mMaximumScreenOffTimeout=2147483647
  mLastScreenOnTime=335721
  mBroadcastWakeLock=UnsynchronizedWakeLock(mFlags=0x1 mCount=0 mHeld=false)
  mStayOnWhilePluggedInScreenDimLock=UnsynchronizedWakeLock(mFlags=0x6 mCount=0
mHeld=false)
  mStayOnWhilePluggedInPartialLock=UnsynchronizedWakeLock(mFlags=0x1 mCount=0 mH
eld=false)
  mPreventScreenOnPartialLock=UnsynchronizedWakeLock(mFlags=0x1 mCount=0 mHeld=f
alse)
  mProximityPartialLock=UnsynchronizedWakeLock(mFlags=0x1 mCount=0 mHeld=false)
  mProximityWakeLockCount=0
  mProximitySensorEnabled=false
  mProximitySensorActive=false
  mProximityPendingValue=-1
  mLastProximityEventTime=0
  mLightSensorEnabled=false mLightSensorAdjustSetting=0.0
  mLightSensorValue=-1.0 mLightSensorPendingValue=-1.0
  mHighestLightSensorValue=-1 mWaitingForFirstLightSensor=false
  mLightSensorPendingDecrease=false mLightSensorPendingIncrease=false
  mLightSensorScreenBrightness=-1 mLightSensorButtonBrightness=-1 mLightSensorKe
yboardBrightness=-1
  mUseSoftwareAutoBrightness=true
  mAutoBrightessEnabled=false
mScreenBrightnessAnimator:
  animating: start:0, end:255, duration:0, current:255
  startSensorValue:-1 endSensorValue:-1
  startTimeMillis:335721 now:6663824
  currentMask:SCREEN_BRIGHT_BIT

mLocks.size=0:

mPokeLocks.size=0:
<--
十二月 28, 2015 11:12:42 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\Program Files\adt-bundle-windows-x86\adt-bundl
e-windows-x86-20131030\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell pm l
ist packages cn.kuwo.kwmusiccar
十二月 28, 2015 11:12:42 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Shell command output
-->
package:io.selendroid.cn.kuwo.kwmusiccar
<--
十二月 28, 2015 11:12:42 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\Program Files\adt-bundle-windows-x86\adt-bundl
e-windows-x86-20131030\sdk\platform-tools\adb.exe -s 0123456789ABCDEF install -r
 D:\Program Files\adt-bundle-windows-x86\resigned-kwplayerhd.apk
十二月 28, 2015 11:12:45 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Shell command output
-->
pkg: /data/local/tmp/resigned-kwplayerhd.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
4173 KB/s (6478794 bytes in 1.516s)
<--
十二月 28, 2015 11:12:46 上午 io.selendroid.standalone.server.model.SelendroidSt
andaloneDriver createNewTestSession
严重: Error occurred while starting Selendroid session
io.selendroid.standalone.exceptions.AndroidSdkException: APK installation failed
. Output:
pkg: /data/local/tmp/resigned-kwplayerhd.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
4173 KB/s (6478794 bytes in 1.516s)
        at io.selendroid.standalone.android.impl.AbstractDevice.install(Abstract
Device.java:141)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.crea
teNewTestSession(SelendroidStandaloneDriver.java:239)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.crea
teNewTestSession(SelendroidStandaloneDriver.java:214)
        at io.selendroid.standalone.server.handler.CreateSessionHandler.handleRe
quest(CreateSessionHandler.java:40)
        at io.selendroid.standalone.server.BaseSelendroidStandaloneHandler.handl
e(BaseSelendroidStandaloneHandler.java:45)
        at io.selendroid.standalone.server.SelendroidServlet.handleRequest(Selen
droidServlet.java:131)
        at io.selendroid.server.common.BaseServlet.handleHttpRequest(BaseServlet
.java:67)
        at io.selendroid.server.common.http.ServerHandler.channelRead(ServerHand
ler.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:319)
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(Ab
stractTrafficShapingHandler.java:223)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:319)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToM
essageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:163)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedCha
nnelDuplexHandler.java:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.ja
va:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Unknown Source)

十二月 28, 2015 11:12:46 上午 io.selendroid.standalone.server.model.DeviceStore
release
信息: Releasing device HardwareDevice [serial=0123456789ABCDEF, model=Full AOSP
on MStar Cedric3, targetVersion=ANDROID16, apiTargetType=android]
十二月 28, 2015 11:12:46 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\Program Files\adt-bundle-windows-x86\adt-bundl
e-windows-x86-20131030\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell am f
orce-stop cn.kuwo.kwmusiccar
十二月 28, 2015 11:12:47 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Shell command output
-->

<--
十二月 28, 2015 11:12:47 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\Program Files\adt-bundle-windows-x86\adt-bundl
e-windows-x86-20131030\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell ps
十二月 28, 2015 11:12:47 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Shell command output
-->
USER     PID   PPID  VSIZE  RSS     WCHAN    PC         NAME
root      1     0     388    252   ffffffff 00000000 S /init
root      2     0     0      0     ffffffff 00000000 S kthreadd
root      3     2     0      0     ffffffff 00000000 S ksoftirqd/0
root      6     2     0      0     ffffffff 00000000 S migration/0
root      7     2     0      0     ffffffff 00000000 S migration/1
root      8     2     0      0     ffffffff 00000000 S kworker/1:0
root      9     2     0      0     ffffffff 00000000 S ksoftirqd/1
root      10    2     0      0     ffffffff 00000000 S khelper
root      25    2     0      0     ffffffff 00000000 S ms_otg_queue
root      218   2     0      0     ffffffff 00000000 S sync_supers
root      220   2     0      0     ffffffff 00000000 S bdi-default
root      222   2     0      0     ffffffff 00000000 S kblockd
root      232   2     0      0     ffffffff 00000000 S khubd
root      239   2     0      0     ffffffff 00000000 S md
root      264   2     0      0     ffffffff 00000000 S cfg80211
root      265   2     0      0     ffffffff 00000000 S kworker/1:1
root      302   2     0      0     ffffffff 00000000 S kswapd0
root      350   2     0      0     ffffffff 00000000 S fsnotify_mark
root      368   2     0      0     ffffffff 00000000 S crypto
root      446   2     0      0     ffffffff 00000000 S f_mtp
root      451   2     0      0     ffffffff 00000000 S file-storage
root      460   2     0      0     ffffffff 00000000 S mmcqd/0
root      461   2     0      0     ffffffff 00000000 S mmcqd/0boot0
root      462   2     0      0     ffffffff 00000000 S mmcqd/0boot1
root      485   2     0      0     ffffffff 00000000 S binder
root      505   2     0      0     ffffffff 00000000 S key_wq
root      512   2     0      0     ffffffff 00000000 D MONITOR_THREAD_
root      575   2     0      0     ffffffff 00000000 D collect_light
root      590   2     0      0     ffffffff 00000000 S mmcqd/1
root      602   2     0      0     ffffffff 00000000 S krfcommd
root      607   2     0      0     ffffffff 00000000 S deferwq
root      610   2     0      0     ffffffff 00000000 S goodix_wq
root      619   2     0      0     ffffffff 00000000 D QST_looper
root      620   2     0      0     ffffffff 00000000 D QST_cvbs_thread
root      621   2     0      0     ffffffff 00000000 D QST_cvbs_detect
root      623   2     0      0     ffffffff 00000000 D QST_rtk_backtra
root      624   1     348    4     ffffffff 00000000 S /sbin/ueventd
root      828   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p5-
root      829   2     0      0     ffffffff 00000000 S ext4-dio-unwrit
root      831   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p6-
root      832   2     0      0     ffffffff 00000000 S ext4-dio-unwrit
root      833   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p7-
root      834   2     0      0     ffffffff 00000000 S ext4-dio-unwrit
root      835   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p10
root      836   2     0      0     ffffffff 00000000 S ext4-dio-unwrit
root      843   2     0      0     ffffffff 00000000 S mali-pmm-wq
system    848   1     900    176   ffffffff 00000000 S /system/bin/servicemanage
r
root      849   1     5416   1180  ffffffff 00000000 S /system/bin/vold
root      852   1     972    484   ffffffff 00000000 S /system/bin/debuggerd
system    853   1     49952  5916  ffffffff 00000000 S /system/bin/surfaceflinge
r
drm       855   1     10380  3244  ffffffff 00000000 S /system/bin/drmserver
bluetooth 857   1     1416   728   ffffffff 00000000 S /system/bin/dbus-daemon
root      858   1     6740   892   ffffffff 00000000 S /system/bin/blueletd
root      859   1     936    404   ffffffff 00000000 S /system/bin/installd
keystore  860   1     1928   684   ffffffff 00000000 S /system/bin/keystore
shell     861   1     832    320   ffffffff 00000000 S /system/bin/sh
shell     867   1     4516   248   ffffffff 00000000 S /sbin/adbd
root      875   2     0      0     ffffffff 00000000 D vbi_thread
root      1061  2     0      0     ffffffff 00000000 S flush-179:0
root      1373  2     0      0     ffffffff 00000000 S RTW_CMD_THREAD
media     3193  1     215388 9520  ffffffff 00000000 S /system/bin/mediaserver
root      3194  1     9876   1080  ffffffff 00000000 S /system/bin/netd
root      3195  1     191764 38420 ffffffff 00000000 S zygote
root      3196  2     0      0     ffffffff 00000000 S kworker/u:2
system    3327  3195  316432 57404 ffffffff 00000000 S system_server
wifi      3403  1     2764   1504  ffffffff 00000000 S /system/bin/wpa_supplican
t
u0_a27    3411  3195  233628 43220 ffffffff 00000000 S com.android.systemui
u0_a37    3439  3195  220188 42448 ffffffff 00000000 S com.qihoo.permmgr
u0_a24    3474  3195  201740 33332 ffffffff 00000000 S com.android.inputmethod.p
inyin
radio     3492  3195  212912 35312 ffffffff 00000000 S com.android.phone
u0_a1     3558  3195  213552 39068 ffffffff 00000000 S android.process.acore
u0_a37    3590  3195  214884 38232 ffffffff 00000000 S com.qihoo.permmgr:scan
u0_a37    3606  3439  210628 31336 ffffffff 00000000 S com.qihoo.permmgr
system    3646  3195  204872 33156 ffffffff 00000000 S com.android.settings
u0_a7     3672  3195  204028 34720 ffffffff 00000000 S android.process.media
u0_a31    3704  3195  226444 44172 ffffffff 00000000 S com.autonavi.minimap
u0_a37    3725  3195  217532 39620 ffffffff 00000000 S com.qihoo.permmgr:engine
u0_a46    3747  3195  212488 38712 ffffffff 00000000 S com.dianxinos.superuser
u0_a31    3864  3195  222852 40488 ffffffff 00000000 S com.autonavi.minimap:push

u0_a69    3899  3195  206852 34204 ffffffff 00000000 S com.baidu.easyroot:bdserv
ice_v1
u0_a69    3915  3195  221656 39596 ffffffff 00000000 S com.baidu.easyroot
u0_a3     4008  3195  200824 31448 ffffffff 00000000 S com.mesada.calendarwidget

root      4201  1     180528 20300 ffffffff 00000000 S qh_rt_service
root      4203  1     5684   680   ffffffff 00000000 S sservice
log       4239  1     756    164   ffffffff 00000000 S /system/bin/logwrapper
dhcp      4240  4239  988    444   ffffffff 00000000 S /system/bin/dhcpcd
u0_a18    4318  3195  222304 38772 ffffffff 00000000 S org.rearview.messagecente
r
u0_a31    4447  1     804    336   ffffffff 00000000 S /data/data/com.autonavi.m
inimap/files/DaemonServer
root      5269  2     0      0     ffffffff 00000000 S kworker/0:2
shell     5425  867   0      0     ffffffff 00000000 Z screencap
u0_a6     5450  3195  202492 31040 ffffffff 00000000 S com.android.defcontainer
system    5608  3195  235460 54152 ffffffff 00000000 S android.mesada.launcher
u0_a23    7204  3195  200396 29816 ffffffff 00000000 S com.svox.pico
u0_a4     7291  3195  200764 29840 ffffffff 00000000 S org.rearview.carrecorder
shell     7329  867   0      0     ffffffff 00000000 Z screencap
u0_a31    8130  3195  220604 37748 ffffffff 00000000 S com.autonavi.minimap:loca
tionservice
u0_a45    8154  3195  201496 31516 ffffffff 00000000 S org.rearview.bluetooth
u0_a30    8167  3195  203548 30160 ffffffff 00000000 S com.mesada.btservice
u0_a11    8188  3195  203672 31800 ffffffff 00000000 S org.ila.gpslocation
u0_a0     8269  3195  204436 35696 ffffffff 00000000 S org.ila.carappstore
root      8358  2     0      0     ffffffff 00000000 S kworker/0:1
root      8360  2     0      0     ffffffff 00000000 S kworker/u:1
system    8595  3195  200476 31248 ffffffff 00000000 S com.android.keychain
u0_a34    8626  3195  246544 45708 ffffffff 00000000 S com.qihoo.daemon
u0_a34    8650  3195  252092 65732 ffffffff 00000000 S com.qihoo.appstore
u0_a17    8749  3195  203556 34088 ffffffff 00000000 S com.mesada.server
root      9639  1     7976   736   ffffffff 00000000 S /system/bin/rild
shell     9866  867   816    328   c001a810 401454d0 S /system/bin/sh
shell     9868  9866  1028   224   00000000 400a892c R ps
<--
十二月 28, 2015 11:12:47 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\Program Files\adt-bundle-windows-x86\adt-bundl
e-windows-x86-20131030\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell pm c
lear cn.kuwo.kwmusiccar

**Comment by niuniudd** [comment]
I delete the folder META-INF in the apk,after that the script can run successful

**Comment by angelliu** [comment]
Hi niuniudd：

**Comment by niuniudd** [comment]
Because selendroid need to build a new selendroid server apk ,
the test app`s signature is different from the new server apk,If you don`t re-sign the APK file,the new selendroid apk will build fail

**Comment by angelliu** [comment]
thanks niuniudd!
Before I hava seen the Selendroid's Architecture as following:

**Comment by holybible934** [comment]
Hi angelliu, re-signing your AUT (App Under Test) is not Selendroid Server but the nature of Android.  
Android basically forbids one APK to access others to prevent any security leakage.  
As Selendroid Server (APK in Android Device) needs to take over control of your AUT, Selendroid Server need to re-sign your AUT with its debug key then Selendroid Server will be authorized to access / control your AUT.  
You shall spend some time to understand whole Android + Selendroid before reporting this issue.

如果你看不懂英文，中文的說法就是請你先回去看看 Android 對於應用的權限控管(Permission)以及如何讓一個應用去操作另外一個應用，這些都是 Android 的權限安全的限制，並不是 Selendroid 的問題。
