### ISSUE TITLE
problem while working with phone gap app automation 

### ISSUE THREAD

**Issue by rakslalsangi** [selendroid/selendroid#1026]
Hi All ,

I am trying to automate phone gap app on android platform with Selendroid , I am getting following error .
I attached images please find .
I used main activity & app id , which displaying in http://localhost:4444/wd/hub/status (which display in image ) , 

code image :--
![image](https://cloud.githubusercontent.com/assets/13434323/12448242/a51d842c-bf9a-11e5-9828-31acd8c328c0.png)

Error image :--
![image](https://cloud.githubusercontent.com/assets/13434323/12448011/4d6b8f54-bf99-11e5-8b97-059d6cf7968b.png)

http://localhost:4444/wd/hub/status image :--
![image](https://cloud.githubusercontent.com/assets/13434323/12448295/19a3da4e-bf9b-11e5-8532-18451c427015.png)

**Comment by mi2pankaj** [comment]
Try to uninstall any existing installed selendroid driver app in device and try it again.

**Comment by rakslalsangi** [comment]
Thanks Pankaj for reply .

I uninstalled all existing  selendroid driver app , still I am getting this issue .

When I use apk file employee-directory which provided by solendroid officially , it works fine but for my apk ( phonegap ) file it dont work .

**Comment by mi2pankaj** [comment]
Please share the whole selendroid log and exception.
