### ISSUE TITLE
Getting ERR_NAME_NOT_RESOLVED on Webdriver Webview App

### ISSUE THREAD

**Issue by DebabrataC** [selendroid/selendroid#1036]
Hi,

i have created a simple code to open my application and perform some basic function. However when its trying to open the application AndroidDriver Webview App, its showing "ERR_NAME_NOT_RESOLVED". My device is connected to network and manually from browser i am able to open the application.
Also my sample code to open google search page and type some text is working fine.

Any pointer would be a great help.

Thanks,
~D

**Comment by mi2pankaj** [comment]
try uninstalling any existing Android Driver app.

**Comment by DebabrataC** [comment]
No luck.

**Comment by operatiay** [comment]
are you testing a website or a native app? your description is somewhat ambiguous...

**Comment by DebabrataC** [comment]
My bad, if i am not clear. Its a website which i am testing, and ofcourse its not on public domain. So i believe its not able to resolve the server IP.

**Comment by DebabrataC** [comment]
I had to connect to VPN before accessing the website.
