### ISSUE TITLE
apk dependencies are missing

### ISSUE THREAD

**Issue by DominikDary** [selendroid/selendroid#1037]
When the project is build, the apk dependencies of 

- android-driver
- selendroid-server 

are not any longer included to the output artifacts.

**Comment by DominikDary** [comment]
@PrakashGoulla you may have an idea?

**Comment by PrakashGoulla** [comment]
@DominikDary is it in the jcenter/maven published artifacts?

**Comment by DominikDary** [comment]
I understood it that we have our own bintray organisation and then let this one publish to jcenter and maven central.
But in the old maven world, the apks are included to the selendroid-standalone jar. This is not any longer the case. I played with it, but it is still not working. do you have an idea about that?

**Comment by DominikDary** [comment]
fixed #627e9155d8de0511248d0c65e5cc802bcc8ea6ee
