### ISSUE TITLE
sendKeys() not working in username/password editText fields

### ISSUE THREAD

**Issue by baclark77** [selendroid/selendroid#110]
On my application login page, sendKeys() fails to type in the username/password fields. A screenshot of the inspector layout of the login page is attached (really wish github allowed you to upload other files so I could attach the app package).
![loginpage](https://f.cloud.github.com/assets/5147624/1092310/0251774c-167a-11e3-87b5-ec1da47e39eb.jpg)

Also, not sure if this helps but I played around with robotium a while back and I had the same issue with their typeText() method, but their enterText() method worked fine.

Is there a work around for this issue? In the interim I've written a little method that uses chimpchat to type in the username/password field but I'd like to get rid of that work around if possible.

Appreciate any info/help!

**Comment by longmazhanfeng** [comment]
How to use selendroid test custom view? I try and failed

**Comment by mustafa-issa** [comment]
do your problem have solved now? if yes could you please tell me how ?

**Comment by longmazhanfeng** [comment]
selendroid support custom views well when the version of android is after 4.4

**Comment by longmazhanfeng** [comment]
@mustafa-issa selendroid support custom views well when the version of android is after 4.4

**Comment by LucySwain** [comment]
Hi,  I am facing the same  issue for appium 1.7.1 and android 6 lava mobile, eagerly looking for a solution ?
Please anyone update me with the answer.
Thanks in advance.
