### ISSUE TITLE
device '(null)' not found

### ISSUE THREAD

**Issue by wa1one** [selendroid/selendroid#1133]
Always get that error in java console

**Comment by rgoerner** [comment]
You mean, when running, it can not find any device (emulated)?

**Comment by rgoerner** [comment]
io.selendroid.standalone.server.model.SelendroidStandaloneDriver getsupportedDevices Error occurred when buildung supported device info: null

Same here, I get an error connection a real or virtual device on it (0.17)

**Comment by rgoerner** [comment]
If I remove the device, I first get a releasing device notify (works), but then device is disconnect and removing ;-) - seems to be bug or loop ....

**Comment by rgoerner** [comment]
![grafik](https://user-images.githubusercontent.com/17622072/31929952-22f37a66-b89e-11e7-83f6-53565148c99c.png)

**Comment by lpetre** [comment]
This was due to the device using a newer API version than the code could handle.  This should be fixed by #1141, please get the latest code from master and try again.
