### ISSUE TITLE
cant found android device,the device is android 7.1.1

### ISSUE THREAD

**Issue by FuckyouBB** [selendroid/selendroid#1153]
when i start server,it work ,and command 'adb devices' has all device
open http://localhost:4444/wd/hub/status, only the device in  android 7.1.1 is not in there ,other devices can found ,what's the problem?

**Comment by FuckyouBB** [comment]
io.selendroid.standalone.io 

.ShellCommand exec
信息: Executing shell command: [/Users/ctwl/Library/Android/sdk/platform-tools/adb, -s, GSLDU17B11003991, shell, ls, /system/framework/*map*]
 io.selendroid.standalone.io 

.ShellCommand exec
信息: Shell command output
-->
/system/framework/com.google.android.maps.jar
<--
 io.selendroid.standalone.server.model.DeviceStore addDevice
信息: Adding: HardwareDevice [serial=GSLDU17B11003991, model=null, targetVersion=null, apiTargetType=google]
 io.selendroid.standalone.android.impl.DefaultDeviceManager initializeAdbConnection
信息: my devices: null

**Comment by lpetre** [comment]
This should be fixed with #1141, please pull the latest code from master and try again.
