### ISSUE TITLE
Unable to select date/month/year from native date picker object 

### ISSUE THREAD

**Issue by vchandran-care** [selendroid/selendroid#129]
I am facing a problem where i am not able to select date/month/year from native date picker using selendroid  
i tried this .  driver.findElement(By.id("month")).sendKeys("Oct");  But it's not working 

from irc:

lukeis
charbrandeis: is this in a native component? with a DatePicker object? (not a webview)  if so… I don't think we've explicitly handled that code path in selendroid, I don't see any code handling DatePicker objects (nor calling the method needed to be called… updateDate) 
charbrandeis:
yes, it's in a native component with a date picker object.. 
== chhsiung has quit  
lukeis
ok, then I don't see that being handled in selendroid currently

**Comment by CharlesBrandeis** [comment]
Hi

I created a script using samsung galaxy S5 and the script works fine on
S5.But if i try to run the same script on Nexus 7,it couldn't interact with
a button on the alert.Can you please look into this?

i am attaching a screenshot from Nexus 7 .

Thanks
Charles

**Comment by jankowskirobert** [comment]
cause datePicker has other key reaction on specific mobile phone brands and android "versions". Better option to push "button1" is to use a tap() function.

**Comment by CharanpreetHora** [comment]
This is pretty strange. I am able to select date picker date if I am using below capability instead of uiautomator2.
capability name="automationName" value="Appium"

removed below

capability name="automationName" value="uiautomator2"
But now for me Allow Permission is blocker.
Can you suggest?
