### ISSUE TITLE
Selendroid inspector doesn't show details of elements

### ISSUE THREAD

**Issue by jeelansheriff** [selendroid/selendroid#136]
I was able to get Selendroid server running, and http://localhost:5555/inspector/ does show a UI snapshot of the Mobile Device connected. But i am unable to drill to each individual elements or even able to select the elements on the inspector.

Device in Use: Kindle Fire(Android Version 4.0.4)
Latest version of Selendroid.

Any pointers into the issue would be very helpful.

**Comment by vprem786** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17675568/13548677/c6c37c68-e31b-11e5-9cf0-d0222b86290d.png)
Hi,
Selendroid Inspector is not able to load Element Properties
Kindly Solve problem
