### ISSUE TITLE
Unexpected confirm dialogs with title "The page at "file://" says:" in a Cordova app

### ISSUE THREAD

**Issue by stkomitov** [selendroid/selendroid#153]
I have a simple hybrid app with a login page and one more page after that.
When I start the app from the java code:

``` java
SelendroidCapabilities capa = SelendroidCapabilities.emulator( ... );
WebDriver driver = new SelendroidDriver( "http://localhost:5555/wd/hub", capa );
```

stop in debug, and try to login in without specifying user/pass, I receive a native alert like this (snippet from driver.getPageSource()):

```
{"id":"alertTitle",...,"value":"Alert","shown":true,"type":"DialogTitle","rect"
...
{"id":"message",...,"value":"Please specify username and password","shown":true,"type":"TextView","rect":}
```

which is the correct behaviour.
But after I do any action with the driver, for example:

``` java
driver.switchTo().window( "WEBVIEW" );   or   driver.findElement( By.id( "blabla" ) );
```

and again try to login without user/pass, I receive different native dialog, a confirm, with Cancel and OK buttons, title: "The page at "file://" says:" and value: "gap:["Notification...". The snippet from the driver.getPageSource() is: 

```
{"id":"alertTitle",...,"value":"The page at "file://" says:","shown":true,"type":"DialogTitle","rect":
...
{"id":"message",...,"value":"["Please specify username and password","Alert","OK"]","shown":true,"type":"TextView","rect":
...
{"id":"value",...,"value":"gap:["Notification","alert","N6",true]","shown":true,"type":"EditText","rect":...
```

And the main problem is that there are other, unexpected, confirmation dialogs with the same title `The page at "file://" says:`, which pops up with the `gap:[...]` commands in the value field (also gap_callbackserver, gap_poll:...), which breaks all my tests.

**Comment by Divyaadz** [comment]
Facing same issue. When clicking any link in the hybrid app I'm getting this alert msg. Pls help
