### ISSUE TITLE
Failed to create assembly: ... No such archiver: 'apk'

### ISSUE THREAD

**Issue by Son-kun** [selendroid/selendroid#178]
When i try to build application with selendroid-standalone using maven i get that error:

Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.3:single (create-executable-jar) on project XXX: Failed to create assembly: Error adding file-set for 'io.selendroid:selendroid-server:apk:0.5.0' to archive: Error adding archived file-set. PlexusIoResourceCollection not found for: d:\maven\repository\io\selendroid\selendroid-server\0.5.0\selendroid-server-0.5.0.apk: No such archiver: 'apk'

same with 0.5.1, and 0.6.0(#514)

**Comment by Marrowbones** [comment]
I know this is an old question, but I had this problem myself quite recently and never found any decent answers.  I eventually sorted it and posted my answer here: http://stackoverflow.com/questions/21984047/selendroid-with-maven-no-such-archiver-apk/38641065#38641065
