### ISSUE TITLE
Selecting an item in a ListView

### ISSUE THREAD

**Issue by steigerm** [selendroid/selendroid#180]
I am trying to integrate a ListView in a testcase and must therefore select a specific item from the list.
Does selendroid has something like scroll_to like Appium has?

**Comment by nilofarjargela** [comment]
I have tried to use

WebElement pages = driver.findElement(By.id("conditionQuestionOptionTextView"));
TouchActions singleTap = new TouchActions(driver).singleTap(pages.findElement(By.linkText("I have a clean title.")));

but it is not working. This is element of Listview.

**Comment by 5654566** [comment]
Hi, 
How can i select single option from listview using selendroid. It would be great if anyone help me!!

I have tried with following...

WebElement frameElement = driver.findElement(By.linkText("Firstname."));
WebElement listView = frameElement.findElement(By.tagName("ListView"));
List elements = listView.findElements(By.linkText("Firstname."));


Thanks in advance...
