### ISSUE TITLE
Setting up hardware device

### ISSUE THREAD

**Issue by NikPatelQA** [selendroid/selendroid#199]
I am setting up selendroid first time and having issue setting up hardware device. I have android device with V 4.1.2. it is plugged in to to the box where I am running selendroid-standalone but it doesn't detect. I am following steps from http://selendroid.io/setup.html. It looks like I am missing something here. please help.

![image](https://f.cloud.github.com/assets/6333768/1854170/74b22ecc-7718-11e3-8d68-5c2856f4beac.png)

Thanks,
Nik

**Comment by akilanc1** [comment]
hi lukeis,

how can I automate chrome browser on mobile using chromedriver (Selendroid).

please find my configuration code and guide me if any corrections needed.

You told previous post that use chromedriver to automate. can you explain how to use by step by step.
SelendroidConfiguration config = new SelendroidConfiguration();

    selendroidServer = new SelendroidLauncher(config);

    selendroidServer.launchSelendroid();

    DesiredCapabilities caps = SelendroidCapabilities.android();

  driver = new SelendroidDriver(DesiredCapabilities.android());

  driver.get("http://www.google.com");

**Comment by operatiay** [comment]
@akilanc1 this is a dead (closed) issue.
another issue: please use google before posting an 'issue': http://stackoverflow.com/questions/19545629/how-to-get-chromedriver-working-on-android-java-example

`chromedriver != Selendroid`
