### ISSUE TITLE
"Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher" when starting the grid 

### ISSUE THREAD

**Issue by mummana** [selendroid/selendroid#200]
I have followed the steps as described in the page http://selendroid.io/scale.html  in order to have hub and node .I am able to start the  selendroid server successfully  in the cmd prompt , But when i start the grid using the command : java -Dfile.encoding=UTF-8 -cp "selendroid-grid-plugin-0.7.0.jar:selenium-server-standalone-2.35.0.jar" org.openqa.grid.selenium.GridLauncher -capabilityMatcher io.selendroid.grid.SelendroidCapabilityMatcher -role hub -host 127.0.0.1 -port 4444 ,I'm facing an error as ""Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher" .Please do check it ,
Note:I am using 1)selendroid-grid-plugin-0.7.0
2)selendroid-standalone-0.7.0-with-dependencies
3)selenium-server-standalone-2.35.0
which are all in same folder

**Comment by rahulrajeevan** [comment]
HI @martynwinsen  Please find solution from http://stackoverflow.com/questions/33930190/could-not-find-load-main-class-gridlauncher-for-selendroid-grid
