### ISSUE TITLE
The requested application under test is not configured in selendroid server.

### ISSUE THREAD

**Issue by nxqamar** [selendroid/selendroid#236]
I am trying to run some basic findElement webdriver test on android native browser. So my testing is purely Mobile testing unlike a native or hybrid approach. A lot of people here have suggested passing myApp.apk string as an app name which doesnt make sense to me in case of a purely Mobile approach. This is what I have and any pointer would be highly appreciated.

```
public synchronized static WebDriver getAndroidDriver() {
        if (driver == null) {
            DesiredCapabilities caps = SelendroidCapabilities.emulator(DeviceTargetPlatform.ANDROID19, "io.selendroid.androiddriver:0.8.0-SNAPSHOT");
            try {
                driver = new SelendroidDriver("http://localhost:4444/wd/hub", caps);
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
        return driver;
    }
```

Steps:
I start selendroid without any errors using command line.

```
C:\Program Files (x86)\adt-bundle-windows-x86_64-20131030\sdk>java -jar selendroid-standalone-0.8.0-with-dependencies.jar
```

I have an AVD setup and I start it manually through command line.

Then I run build using maven plugin in eclipse and I get the following exception.

In the browser I can see the following JSON object after running the selendroid jar:

```
{"status":0,"value":{"supportedApps":[{"appId":"io.selendroid.androiddriver:0.8.0-SNAPSHOT","mainActivity":"io.selendroid.androiddriver.WebViewActivity","basePackage":"io.selendroid.androiddriver"}],"os":{"arch":"x86","name":"Windows Server 2008 R2","version":"6.1"},"build":{"browserName":"selendroid","version":"0.8.0-SNAPSHOT"},"supportedDevices":[{"screenSize":"480x800","emulator":true,"androidTarget":"ANDROID19","avdName":"AVD_BWK"}]}}
```

I have tried many permutations but nothing works e.g.

```
//          SelendroidCapabilities caps = SelendroidCapabilities.emulator(DeviceTargetPlatform.ANDROID19, "AVD_BWK");
//          DesiredCapabilities caps = SelendroidCapabilities.android();
```

Error:

```
org.openqa.selenium.SessionNotCreatedException: The requested application under test is not configured in selendroid server.
Command duration or timeout: 193 milliseconds
Build info: version: '2.37.1', revision: 'a7c61cbd68657e133ae96672cf995890bad2ee42', time: '2013-10-21 09:08:07'
System info: host: 'NYBQAAPP2', ip: '10.12.13.140', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_45'
Driver info: io.selendroid.SelendroidDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:115)
    at io.selendroid.SelendroidDriver.<init>(SelendroidDriver.java:37)
    at com.pxma.io.app.utils.BrowserDriver.getAndroidDriver(BrowserDriver.java:166)
    at com.pxma.io.app.utils.BrowserDriver.getDriver(BrowserDriver.java:61)
    at com.pxma.io.app.utils.BrowserDriver.loadPage(BrowserDriver.java:204)
```

**Comment by dharmeshqk** [comment]
public class TestSelndrd {


	@org.junit.Test
	public void andrtest() throws Exception{

		SelendroidLauncher sndserver= null;
		WebDriver driver;

		SelendroidCapabilities capa = SelendroidCapabilities.emulator(DeviceTargetPlatform.ANDROID19,
				"io.selendroid.androiddriver:0.11.0");


		driver = new SelendroidDriver(capa);

		System.out.println("test inf 12454");
		Thread.sleep(1200);

		driver.quit();

	}
}

the above given is my code and i m using ARM(armeabi-v7a) as an emulator
all my path are corrrect i even installed resigned application on it but at the ned i get 

"org.openqa.selenium.SessionNotCreatedException: The requested application under test is not configured in selendroid server.
io.selendroid.exceptions.SessionNotCreatedException: The requested application under test is not configured in selendroid server."

p.s while installing i m intel x86 for 32-bit system i get failed to configure driver 
i have tried enabling virtiualization in bios too didnt worked out..pls help me out here

**Comment by 5654566** [comment]
Hi 

I am Facing the same issue,"The requested application under test is not configured in selendroid server." if any one help me to resove this.Please it's urgent.

**Comment by mbirthariya** [comment]
Hi,

Kindly update the appID in your code.
Run - java -jar selendroid-standalone-0.15.0-wuth-dependencies.jar -app <appname.apk>

Check the appID at http://localhost:4444/wd/hub/status

**Comment by zeeshanjan82** [comment]
I am able to run Run - java -jar selendroid-standalone-0.15.0-wuth-dependencies.jar -app provided with the path for the apk file which I would like to test. I have set the target to the actual device and not the emulator, however everytime I connect using the below code , I always have Android Driver WebView App open my app never loads

`````c#
           public static IWebDriver Instance { get; set; }
            DesiredCapabilities caps = DesiredCapabilities.Android();
            caps.SetCapability("emulator", false); 
            caps.SetCapability("browsername", "selendroid");
            caps.SetCapability("app", appId); 
            caps.SetCapability("mainActivity", mainActivity);

            Instance = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), caps);

``````
