### ISSUE TITLE
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by stcq1986** [selendroid/selendroid#247]
Hi,

When I use selendroid to test my app, it throw IllegalAccessError. I find the reason in the internet, and it may be that both the test project and app main project has the same library reference(See http://stackoverflow.com/questions/9199992/android-instrumentation-testing-illegalaccesserror). And my app project contains the netty library(3.6.6) and I find the selendroid also use it(actually, the exception is thrown when I new netty NioClientSocketChannelFactory). So is any idea about the exception.

Thanks,
Rico

**Comment by nilofarjargela** [comment]
Hi stcq1986,

I am facing the same issue. I am not sure where to add this dependency.

This dependency is alredy there in selendroid-server-common's pom file.

Please help.
