### ISSUE TITLE
Could you please provide C# codes for testing native and hybrid apps

### ISSUE THREAD

**Issue by Navneet24** [selendroid/selendroid#253]
I am able to test web applications using selendroid but not able to test hybrid and native application.
Both the selendroid driver and app get instaled but app does not get open..It thows message "URL Cannot be found"

**Comment by ruudsolidnl** [comment]
Hi,
I realize this is an old post; but I also cannot seem to start a hybrid app via Selendroid. Did you ever get this to work?
