### ISSUE TITLE
Error with multiple devices connected to same HUB

### ISSUE THREAD

**Issue by develmac** [selendroid/selendroid#278]
If we connect more than one device to the same HUB, there are duplicate devices registered (one device shows many times in the status report). 

Also we can not select specific device based on it's Serial (using capabilities). 

Example Code:
final SelendroidCapabilities cap = new SelendroidCapabilities(
                    "", "android");
            DesiredCapabilities.android();

```
        driver = new SelendroidDriver("http://localhost:4444/wd/hub", cap);
        driver.get("http://google.com");
```

**Comment by ArkoSeal** [comment]
Hi,
I am trying to do parallel testing on 2 android devices using selendroid and selenium grid,
I have followed http://selendroid.io/scale.html steps from here but i am unable to execute parallel on both device...also its just creating one node.. can anyone please tell me how to do parallel execution on 2 real device using grid and selendroid ? and what are the capabilities i need to write in json file ? please help me...

thank you,
arko
