### ISSUE TITLE
Error while creating new session: The requested application under test is not configured in selendroid server.

### ISSUE THREAD

**Issue by lirianojoel** [selendroid/selendroid#294]
Hi guys,

Trying to run selendroid on my Cordova/PhoneGap app I got this error: _Error while creating new session: The requested application under test is not configured in selendroid server._ I'm including output info here.
##### java -jar selendroid-standalone-0.8.0-with-dependencies.jar -app Bantasy-debug.apk

Feb 25, 2014 2:45:32 PM io.selendroid.SelendroidLauncher main
INFO: ################# Selendroid #################
Feb 25, 2014 2:45:32 PM io.selendroid.SelendroidLauncher lauchServer
INFO: Starting selendroid-server port 4444
Feb 25, 2014 2:45:32 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt remove /home/joel/bantasy/Bantasy-debug.apk META-INF/MANIFEST.MF
Feb 25, 2014 2:45:32 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt remove /home/joel/bantasy/Bantasy-debug.apk META-INF/CERT.RSA
Feb 25, 2014 2:45:32 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt remove /home/joel/bantasy/Bantasy-debug.apk META-INF/CERT.SF
Feb 25, 2014 2:45:32 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt remove /home/joel/bantasy/Bantasy-debug.apk META-INF/ANDROIDD.SF
Feb 25, 2014 2:45:32 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt remove /home/joel/bantasy/Bantasy-debug.apk META-INF/ANDROIDD.RSA
Feb 25, 2014 2:45:32 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /usr/lib/jvm/java-7-openjdk-i386/bin/jarsigner -sigalg MD5withRSA -digestalg SHA1 -signedjar /home/joel/bantasy/resigned-Bantasy-debug.apk -storepass android -keystore /home/joel/.android/debug.keystore /home/joel/bantasy/Bantasy-debug.apk androiddebugkey
Feb 25, 2014 2:45:33 PM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning: 
The signer certificate will expire within six months.
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2014-05-08) or after any future revocation date.

Feb 25, 2014 2:45:33 PM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: /home/joel/bantasy/resigned-Bantasy-debug.apk
Feb 25, 2014 2:45:33 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt dump badging /home/joel/bantasy/resigned-Bantasy-debug.apk
Feb 25, 2014 2:45:33 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt dump badging /home/joel/bantasy/resigned-Bantasy-debug.apk
Feb 25, 2014 2:45:33 PM io.selendroid.server.model.SelendroidStandaloneDriver initApplicationsUnderTest
INFO: App com.coolappz.Bantasy:1.0.0 has been added to selendroid standalone server.
Feb 25, 2014 2:45:33 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt remove /tmp/android-driver1492281892440988167.apk META-INF/MANIFEST.MF
Feb 25, 2014 2:45:33 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt remove /tmp/android-driver1492281892440988167.apk META-INF/CERT.RSA
Feb 25, 2014 2:45:33 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt remove /tmp/android-driver1492281892440988167.apk META-INF/CERT.SF
Feb 25, 2014 2:45:33 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt remove /tmp/android-driver1492281892440988167.apk META-INF/ANDROIDD.SF
Feb 25, 2014 2:45:33 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt remove /tmp/android-driver1492281892440988167.apk META-INF/ANDROIDD.RSA
Feb 25, 2014 2:45:33 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /usr/lib/jvm/java-7-openjdk-i386/bin/jarsigner -sigalg MD5withRSA -digestalg SHA1 -signedjar /tmp/resigned-android-driver1492281892440988167.apk -storepass android -keystore /home/joel/.android/debug.keystore /tmp/android-driver1492281892440988167.apk androiddebugkey
Feb 25, 2014 2:45:34 PM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning: 
The signer certificate will expire within six months.
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2014-05-08) or after any future revocation date.

Feb 25, 2014 2:45:34 PM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: /tmp/resigned-android-driver1492281892440988167.apk
Feb 25, 2014 2:45:39 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/tools/android list avds
Feb 25, 2014 2:45:39 PM io.selendroid.server.model.DeviceStore addEmulators
INFO: Adding: AndroidEmulator [screenSize=720x1280, targetPlatform=ANDROID17, avdName=GalaxyNexus]
Feb 25, 2014 2:45:39 PM io.selendroid.server.SelendroidStandaloneServer start
INFO: selendroid-standalone server has been started on port: 4444
##### http://localhost:4444/wd/hub/status

{"status":0,"value":{"supportedApps":[{"appId":"io.selendroid.androiddriver:0.8.0","mainActivity":"io.selendroid.androiddriver.WebViewActivity","basePackage":"io.selendroid.androiddriver"},{"appId":"com.coolappz.Bantasy:1.0.0","mainActivity":"com.coolappz.Bantasy.Bantasy","basePackage":"com.coolappz.Bantasy"}],"os":{"arch":"i386","name":"Linux","version":"3.8.0-36-generic"},"build":{"browserName":"selendroid","version":"0.8.0"},"supportedDevices":[{"screenSize":"720x1280","emulator":true,"androidTarget":"ANDROID17","avdName":"GalaxyNexus"}]}}
##### After trying to run a test:

Feb 25, 2014 2:45:52 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt dump badging /tmp/resigned-android-driver1492281892440988167.apk
Feb 25, 2014 2:45:52 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt dump badging /tmp/resigned-android-driver1492281892440988167.apk
Feb 25, 2014 2:45:52 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt dump badging /tmp/resigned-android-driver1492281892440988167.apk
Feb 25, 2014 2:45:53 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/joel/android-sdk-linux/build-tools/19.0.1/aapt dump badging /home/joel/bantasy/resigned-Bantasy-debug.apk
Feb 25, 2014 2:48:30 PM io.selendroid.server.handler.CreateSessionHandler handle
INFO: new session command with capabilities: {
  "desiredCapabilities": {"aut": "com.coolapz.Bantasy:1.0.0"},
  "sessionId": null
}
Feb 25, 2014 2:48:30 PM io.selendroid.server.handler.CreateSessionHandler handle
SEVERE: Error while creating new session: The requested application under test is not configured in selendroid server.
io.selendroid.exceptions.SessionNotCreatedException: The requested application under test is not configured in selendroid server.
    at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:257)
    at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:41)
    at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:127)
    at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:70)
    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
    at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
    at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
    at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
    at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:72)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:701)

**Comment by PKPradeepKumar** [comment]
Thanks **DominikDary** It's working fine for me.
