### ISSUE TITLE
Enhancement: Implement driver.manage().timeouts().PageLoadTimeout()

### ISSUE THREAD

**Issue by Gimpneek** [selendroid/selendroid#300]
On my Cucumber & Scala Play! setup I have a scenario that requires a modal dialog in JavaScript to popup and on asserting the content of the dialog the confirm button is clicked. This button then reloads the page and my scenario then verifies the page reload.

I was then calling `await().atmost().until().ispresent()`  to find the refreshed content but this immediately passed (I guess due to it being the same page). I then tried to use `driver.manage().timeouts().PageLoadTimeout()` but this wasn't implemented in Selendroid. 

I posted this on the IRC channel (which lead to this request) and the following was suggested as an alternative: https://github.com/selendroid/selendroid/blob/master/selendroid-client/src/main/java/io/selendroid/waiter/TestWaiter.java

Thanks,
Colin

**Comment by DominikDary** [comment]
has been merged
