### ISSUE TITLE
Run several webview tests without closing the emulator

### ISSUE THREAD

**Issue by SerinaTan** [selendroid/selendroid#315]
Hi,

I am trying to test webpages with Selendroid webview app and take screenshots of them. In each task, I need to load the same page several times in order to get an array of screenshots. I am wondering if there is any way I can keep the emulator open in each task and turn the webview app on and off instead. Now the emulator closes each time I finish taking a screenshot and it takes a huge amount of time to startup the emulator again to take the next one.

Would you please reply me if you think it is possible? I really appreciate it.

Serina

**Comment by lnagvekar** [comment]
hey Serina can you help me out with the issue of how to use a single emulator
thank you in advance
