### ISSUE TITLE
It is impossible to use URL with "and-activity://" scheme

### ISSUE THREAD

**Issue by smiklosovic** [selendroid/selendroid#326]
@DominikDary @selendroid 

Hi,

I am not sure if you are aware of this but I can not use URLs which has the form like 

``` java
URL url = new URL("and-activity://start.this.activity")
browser.get(url.toExternalForm());
```

I can use it only like this

``` java
browser.get("and-activity://start.this.activity")
```

This is very inconvenient since we are doing some new API where we _want_ and _need_ to be able to use that URL form and not just that string which is not so flexible anyway.

The problem with that custom URL scheme is that it is not supported by Java's URL. Check that (1). You have to register that URL handler with custom scheme name into your code as described.

I do not mind at all if you continue to use string based form - it is irrelevant from my point of view. _However_ I can not use that form "and-activity" string with dash because from (1) it is clear that there needs to be package with that name and I can not use dash in a package name - it is restricted by Java itself.

For that matter, all I need to change is that dash to another string, like "_"  - by doing that, I can create package hence I can register my own URL handler and finally use that URL in normal way.

WDYT?

http://mjremijan.blogspot.cz/2012/02/create-your-own-java-url-handlers.html

**Comment by Benbbe** [comment]
I think that you are using the default android Browser as AUT. 
You should use this code 

driver = new SelendroidDriver(aURL, caps);
driver.switchTo().window("WEBVIEW_0");

you can get the entire views of the app using this :
	Set<String> handles = driver.getWindowHandles();
