### ISSUE TITLE
Communication with emulator gets stuck and session creation times out

### ISSUE THREAD

**Issue by danail-branekov** [selendroid/selendroid#346]
Hi,

I have a JUnit test suite which contains a couple of test classes. Each test class would start Selendroid-standalone and would start a new emulator instance. While the suite is being executed (usually when the third test starts), communication with the emulator gets stuck. Do note that this is only reproducible in Windows only.
Here is the last message logged in the console

> III 22, 2014 7:20:11 PM io.selendroid.io.ShellCommand exec
> INFO: executing command: c:\AndroidSDK\sdk\platform-tools\adb.exe -s emulator-5560 shell getprop dev.bootcomplete

At this point of time the thread which is responsible for talking with the emulator has the following trace:

> Thread [Forwarding newSession on session null to remote](Suspended)  
>     java.net.SocketInputStream.socketRead0(java.io.FileDescriptor, byte[], int, int, int) line: not available [native method]  
>     java.net.SocketInputStream.read(byte[], int, int, int) line: 152  
>     java.net.SocketInputStream.read(byte[], int, int) line: 122 
>     org.apache.http.impl.io.SocketInputBuffer(org.apache.http.impl.io.AbstractSessionInputBuffer).fillBuffer() line: 166  
>     org.apache.http.impl.io.SocketInputBuffer.fillBuffer() line: 90 
>     org.apache.http.impl.io.SocketInputBuffer(org.apache.http.impl.io.AbstractSessionInputBuffer).readLine(org.apache.http.util.CharArrayBuffer) line: 281  
>     org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(org.apache.http.io.SessionInputBuffer) line: 92  
>     org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(org.apache.http.io.SessionInputBuffer) line: 62  
>     org.apache.http.impl.conn.DefaultHttpResponseParser(org.apache.http.impl.io.AbstractMessageParser<T>).parse() line: 254 
>     org.apache.http.impl.conn.DefaultClientConnection(org.apache.http.impl.AbstractHttpClientConnection).receiveResponseHeader() line: 289  
>     org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader() line: 252 
>     org.apache.http.impl.conn.tsccm.BasicPooledConnAdapter(org.apache.http.impl.conn.AbstractClientConnAdapter).receiveResponseHeader() line: 219  
>     org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(org.apache.http.HttpRequest, org.apache.http.HttpClientConnection, org.apache.http.protocol.HttpContext) line: 300  
>     org.apache.http.protocol.HttpRequestExecutor.execute(org.apache.http.HttpRequest, org.apache.http.HttpClientConnection, org.apache.http.protocol.HttpContext) line: 127 
>     org.apache.http.impl.client.DefaultRequestDirector.tryExecute(org.apache.http.impl.client.RoutedRequest, org.apache.http.protocol.HttpContext) line: 712  
>     org.apache.http.impl.client.DefaultRequestDirector.execute(org.apache.http.HttpHost, org.apache.http.HttpRequest, org.apache.http.protocol.HttpContext) line: 517  
>     org.apache.http.impl.client.DefaultHttpClient(org.apache.http.impl.client.AbstractHttpClient).execute(org.apache.http.HttpHost, org.apache.http.HttpRequest, org.apache.http.protocol.HttpContext) line: 906  
>     io.selendroid.SelendroidCommandExecutor(org.openqa.selenium.remote.HttpCommandExecutor).fallBackExecute(org.apache.http.protocol.HttpContext, org.apache.http.client.methods.HttpUriRequest) line: 319  
>     io.selendroid.SelendroidCommandExecutor(org.openqa.selenium.remote.HttpCommandExecutor).execute(org.openqa.selenium.remote.Command) line: 298  
>     io.selendroid.SelendroidDriver(org.openqa.selenium.remote.RemoteWebDriver).execute(java.lang.String, java.util.Map<java.lang.String,?>) line: 527  
>     io.selendroid.SelendroidDriver(org.openqa.selenium.remote.RemoteWebDriver).startSession(org.openqa.selenium.Capabilities, org.openqa.selenium.Capabilities) line: 216  
>     io.selendroid.SelendroidDriver(org.openqa.selenium.remote.RemoteWebDriver).<init>(org.openqa.selenium.remote.CommandExecutor, org.openqa.selenium.Capabilities, org.openqa.selenium.Capabilities) line: 111 
>     io.selendroid.SelendroidDriver(org.openqa.selenium.remote.RemoteWebDriver).<init>(org.openqa.selenium.remote.CommandExecutor, org.openqa.selenium.Capabilities) line: 115  
>     io.selendroid.SelendroidDriver.<init>(java.net.URL, org.openqa.selenium.Capabilities) line: 56  
>     ...

It seems that the thread would wait for response from the emulator but such a response is never received. As a result the test would fail with the error that session creation timed out.
The interesting thing here is that the emulator manages to boot and becomes fully operational

According to http://devmaze.wordpress.com/2011/12/12/starting-and-stopping-android-emulators/, 

> But there is one bug on windows emulator console. It ignores first command. And adb is only capable to send on command per connection. Hence there is no way to reliably kill emulator using adb.

Do you guys know something about such a bug? If such a bug exist I would suggest Selendroid to reissue the _adb.exe -s emulator-5560 shell getprop dev.bootcomplete_ command again after the timeout has been reached in order to verify emulator state

Thanks!

Regards, Danail

**Comment by sureshvv** [comment]
any update? happens to me with 0.15
