### ISSUE TITLE
Implement new session creation handling

### ISSUE THREAD

**Issue by DominikDary** [selendroid/selendroid#349]
Bases on this decision session creation should be updated:
https://groups.google.com/forum/#!searchin/selenium-developers/redirect$20spec/selenium-developers/G7fC3JvWDRk/0waOmo9eYsYJ

**Comment by asm89** [comment]
@DominikDary do you remember if this was done?

**Comment by lukeis** [comment]
this was done long ago, files have moved, can't tell what revision. But we don't send a redirect on a new session.
