### ISSUE TITLE
selendroid flick gesture is not working

### ISSUE THREAD

**Issue by pritamkadam555** [selendroid/selendroid#350]
I am testing hybrid app but flick action is not working selendroid 0.9

my code is 
TouchActions flick = new TouchActions(driver).flick(100,100);
        flick.perform();
        TouchActions flick1 = new TouchActions(driver).flick(100,100);
        flick1.perform();
        TouchActions flick2 = new TouchActions(driver).flick(100,0);
        flick2.perform();

flick(on element) is also not working.
test is not getting failed but flick is not working

**Comment by hencian** [comment]
What is main_wrapper in this context?
