### ISSUE TITLE
Flick, scroll issues

### ISSUE THREAD

**Issue by zh2eou** [selendroid/selendroid#370]
Just started off using selendroid, and finding a couple of weird issues with it - while testing with just the mobile webdriver. 

For one, I could not get flick(int xSpeed, int ySpeed) to work at all. Tried on Android 4.4, 4.3, and 4.2, 2.3.7 avd and 4.4 and 4.0 devices. 

TouchActions.flick(WebElement, int xOffset, int yOffset, int speed) did work for me (setting the page body as the WebElement target), but only on 4.4.

I tried using scroll instead and it seems to work - however, it doesn't appear to be bounded and you can end up scrolling out side of the application screen.

Any ideas?

**Comment by viccky88** [comment]
flick(int xSpeed, int ySpeed) is not working. I have tested on Android 5.0, 6.0.
I am using selendroid-standalne version 0.13.0. 
Can you please suggest how to swipe without using any web element reference.
