### ISSUE TITLE
selendroid can not find native element via xpath

### ISSUE THREAD

**Issue by luisxiaomai** [selendroid/selendroid#404]
Using latest appium 1.0 with appium python client, I can't find native element in selendroid mode via xpath, but ok for using class name locator strategy:
textfield=self.driver.find_element_by_xpath("//android.widget.EditText")-------Fail.
textfield=self.driver.find_element_by_class_name("android.widget.EditText")-------Pass.

**Comment by vijay0850** [comment]
Its not working
