### ISSUE TITLE
Error occurred while starting selendroid-server on the device

### ISSUE THREAD

**Issue by antonydootrix** [selendroid/selendroid#421]
Afternoon,

I have been attempting to get Selendroid to work with our own APK after successfully getting it to work with the selendroid-test-app through Eclipse.

At one point today I managed to get it to actually install the app onto the phone but then it would error. Since that point I have experimented some more and cannot seem to even get it that far.

The log from the selendroid server after the server has started is as follows:
```bash
May 28, 2014 3:06:18 PM io.selendroid.server.handler.CreateSessionHandler handle
INFO: new session command with capabilities: {"desiredCapabilities": {
  "aut": "com.qtx.mtk:1.1",
  "emulator": false
}}
May 28, 2014 3:06:18 PM io.selendroid.server.model.DeviceStore findAndroidDevice
INFO: Evaluating if this device is a match for this session: HardwareDevice [serial=04dbf5f15bdc44e7, model=Nexus 4, targetVersion=ANDROID19]
May 28, 2014 3:06:18 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Users/ak/Testing/adt-bundle-mac-x86_64-20140321/sdk/platform-tools/adb -s 04dbf5f15bdc44e7 shell pm list packages com.qtx.mtk
May 28, 2014 3:06:18 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Users/ak/Testing/adt-bundle-mac-x86_64-20140321/sdk/platform-tools/adb -s 04dbf5f15bdc44e7 install -r /Users/ak/Testing/Selendroid/resigned-qtx.apk
May 28, 2014 3:06:24 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Users/ak/Testing/adt-bundle-mac-x86_64-20140321/sdk/platform-tools/adb -s 04dbf5f15bdc44e7 shell pm list packages io.selendroid.com.qtx.mtk
May 28, 2014 3:06:25 PM io.selendroid.builder.SelendroidServerBuilder createSelendroidServer
INFO: create SelendroidServer for apk: /Users/ak/Testing/Selendroid/resigned-qtx.apk
May 28, 2014 3:06:25 PM io.selendroid.builder.SelendroidServerBuilder init
INFO: Creating customized Selendroid-server: /var/folders/ht/3rht99vn7bx7rbhqs0hnbrrw0000gn/T/selendroid-server5102260972452353625.apk
May 28, 2014 3:06:25 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Users/ak/Testing/adt-bundle-mac-x86_64-20140321/sdk/build-tools/android-4.4.2/aapt remove /var/folders/ht/3rht99vn7bx7rbhqs0hnbrrw0000gn/T/selendroid-server5102260972452353625.apk META-INF/CERT.RSA
May 28, 2014 3:06:25 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Users/ak/Testing/adt-bundle-mac-x86_64-20140321/sdk/build-tools/android-4.4.2/aapt remove /var/folders/ht/3rht99vn7bx7rbhqs0hnbrrw0000gn/T/selendroid-server5102260972452353625.apk META-INF/CERT.SF
May 28, 2014 3:06:25 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Users/ak/Testing/adt-bundle-mac-x86_64-20140321/sdk/build-tools/android-4.4.2/aapt remove /var/folders/ht/3rht99vn7bx7rbhqs0hnbrrw0000gn/T/selendroid-server5102260972452353625.apk AndroidManifest.xml
May 28, 2014 3:06:25 PM io.selendroid.builder.SelendroidServerBuilder createAndAddCustomizedAndroidManifestToSelendroidServer
INFO: Adding target package 'com.qtx.mtk' to /var/folders/ht/3rht99vn7bx7rbhqs0hnbrrw0000gn/T/com.qtx.mtk1401285985772/AndroidManifest.xml
May 28, 2014 3:06:25 PM io.selendroid.builder.SelendroidServerBuilder createAndAddCustomizedAndroidManifestToSelendroidServer
INFO: Final Manifest File:
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="0.10.0" package="io.selendroid.com.qtx.mtk">

    <uses-sdk android:minSdkVersion="10"/>

    <instrumentation android:name="io.selendroid.ServerInstrumentation" android:targetPackage="io.selendroid.testapp"/>

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION"/>
    <uses-permission android:name="android.permission.INJECT_EVENTS"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>

    <application android:debuggable="true" android:icon="@drawable/selenium_icon" android:label="Selendroid">
        <uses-library android:name="android.test.runner"/>
    </application>

</manifest>

May 28, 2014 3:06:25 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Users/ak/Testing/adt-bundle-mac-x86_64-20140321/sdk/build-tools/android-4.4.2/aapt package -M /var/folders/ht/3rht99vn7bx7rbhqs0hnbrrw0000gn/T/com.qtx.mtk1401285985772/AndroidManifest.xml -I /Users/ak/Testing/adt-bundle-mac-x86_64-20140321/sdk/platforms/android-19/android.jar -F /var/folders/ht/3rht99vn7bx7rbhqs0hnbrrw0000gn/T/com.qtx.mtk1401285985772/manifest.apk -f
May 28, 2014 3:06:25 PM io.selendroid.builder.SelendroidServerBuilder createAndAddCustomizedAndroidManifestToSelendroidServer
INFO: 
May 28, 2014 3:06:26 PM io.selendroid.builder.SelendroidServerBuilder createAndAddCustomizedAndroidManifestToSelendroidServer
INFO: file: /var/folders/ht/3rht99vn7bx7rbhqs0hnbrrw0000gn/T/com.qtx.mtk1401285985772selendroid-server.apk
May 28, 2014 3:06:26 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Library/Java/JavaVirtualMachines/jdk1.7.0_55.jdk/Contents/Home/bin/jarsigner -sigalg MD5withRSA -digestalg SHA1 -signedjar /var/folders/ht/3rht99vn7bx7rbhqs0hnbrrw0000gn/T/selendroid-server-com.qtx.mtk-0.10.0.apk -storepass android -keystore /Users/ak/.android/debug.keystore /var/folders/ht/3rht99vn7bx7rbhqs0hnbrrw0000gn/T/com.qtx.mtk1401285985772selendroid-server.apk androiddebugkey
May 28, 2014 3:06:26 PM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2041-08-22) or after any future revocation date.

May 28, 2014 3:06:26 PM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: /var/folders/ht/3rht99vn7bx7rbhqs0hnbrrw0000gn/T/selendroid-server-com.qtx.mtk-0.10.0.apk
May 28, 2014 3:06:26 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Users/ak/Testing/adt-bundle-mac-x86_64-20140321/sdk/platform-tools/adb -s 04dbf5f15bdc44e7 install -r /var/folders/ht/3rht99vn7bx7rbhqs0hnbrrw0000gn/T/selendroid-server-com.qtx.mtk-0.10.0.apk
running command: adb shell setprop log.tag.SELENDROID ERROR
May 28, 2014 3:06:30 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Users/ak/Testing/adt-bundle-mac-x86_64-20140321/sdk/platform-tools/adb -s 04dbf5f15bdc44e7 shell setprop log.tag.SELENDROID ERROR
May 28, 2014 3:06:30 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Users/ak/Testing/adt-bundle-mac-x86_64-20140321/sdk/platform-tools/adb -s 04dbf5f15bdc44e7 shell am instrument -e main_activity qtx.mtk.droid.SplashScreen -e server_port 8080 io.selendroid.com.qtx.mtk/io.selendroid.ServerInstrumentation
May 28, 2014 3:06:30 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Users/ak/Testing/adt-bundle-mac-x86_64-20140321/sdk/platform-tools/adb -s 04dbf5f15bdc44e7 shell am instrument -w -e main_activity qtx.mtk.droid.SplashScreen -e server_port 8080 io.selendroid.com.qtx.mtk/io.selendroid.ServerInstrumentation
May 28, 2014 3:06:31 PM io.selendroid.server.handler.CreateSessionHandler handle
SEVERE: Error while creating new session: Error occurred while starting selendroid-server on the device
io.selendroid.exceptions.SelendroidException: Error occurred while starting selendroid-server on the device
	at io.selendroid.android.impl.AbstractDevice.startSelendroid(AbstractDevice.java:235)
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:290)
	at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:42)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:142)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:70)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
	at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Throwable: android.util.AndroidException: INSTRUMENTATION_FAILED: io.selendroid.com.qtx.mtk/io.selendroid.ServerInstrumentation
	at com.android.commands.am.Am.runInstrument(Am.java:865)
	at com.android.commands.am.Am.onRun(Am.java:282)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:76)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:243)
	at dalvik.system.NativeStart.main(Native Method)
```
Details:
```
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation target package: com.qtx.mtk
INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: io.selendroid.com.qtx.mtk/io.selendroid.ServerInstrumentation
	at com.android.commands.am.Am.runInstrument(Am.java:865)
	at com.android.commands.am.Am.onRun(Am.java:282)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:76)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:243)
	at dalvik.system.NativeStart.main(Native Method)

	... 20 more
```

At the same time I have been tailing the logcat output and the first sign of trouble appears to happen when I see:
```
W/ActivityManager(  638): No content provider found for permission revoke: file:///data/local/tmp/resigned-qtx.apk
```

Let me know what I could be missing here to get this moving forward.

Thanks!

**Comment by nitikas** [comment]
any progress

**Comment by vickykm2000** [comment]
Dear Dominik,

Selendroid android App. project to automate android app. is working fine while executing via testng.xml as testng suite in eclipse.

But I am getting following error while executing the same through ant clean compile. Please help.

     [echo] compiling...
    [javac] C:\ws\build.xml:65: warning: 'includeantruntime' was not set,
 defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 9 source files to C:\ws\build
    [javac] C:\ws\src\android\x.java:9: error: cannot find sym
bol
    [javac] import io.selendroid.SelendroidCapabilities;
    [javac]                     ^
    [javac]   symbol:   class SelendroidCapabilities
    [javac]   location: package io.selendroid
    [javac] C:\ws\src\android\x.java:10: error: cannot find sy
mbol
    [javac] import io.selendroid.SelendroidConfiguration;
    [javac]                     ^
    [javac]   symbol:   class SelendroidConfiguration
    [javac]   location: package io.selendroid
    [javac] C:\ws\src\android\x.java:13: error: cannot find sy
mbol
    [javac] import io.selendroid.SelendroidLauncher;
    [javac]                     ^
    [javac]   symbol:   class SelendroidLauncher
    [javac]   location: package io.selendroid
    [javac] C:\ws\src\android\x.java:14: error: package io.sel
endroid.device does not exist
    [javac] import io.selendroid.device.DeviceTargetPlatform;
    [javac]

**Comment by vickykm2000** [comment]
above error resolved but getting below error now..

[testng] called dpprovider
   [testng] Exception in thread "Thread-42" java.net.BindException: Address alre
ady in use: bind
   [testng]     at sun.nio.ch.Net.bind0(Native Method)
   [testng]     at sun.nio.ch.Net.bind(Net.java:444)
   [testng]     at sun.nio.ch.Net.bind(Net.java:436)

**Comment by Ujjwalag** [comment]
hii
 selendroid server is not able to recognize the AVD's mentioned and when i change the port it is recognizing the AVD, and also i am not able to get the app id even after adding the _app apk
Mar 03, 2015 11:26:38 AM io.selendroid.SelendroidLauncher launchServer
INFO: Starting selendroid-server port 4444
Mar 03, 2015 11:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\ug00334381\Desktop\New folder\gu
ru\Guru99App.apk META-INF/MANIFEST.MF
Mar 03, 2015 11:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\ug00334381\Desktop\New folder\gu
ru\Guru99App.apk META-INF/CERT.RSA
Mar 03, 2015 11:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\ug00334381\Desktop\New folder\gu
ru\Guru99App.apk META-INF/CERT.SF
Mar 03, 2015 11:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\ug00334381\Desktop\New folder\gu
ru\Guru99App.apk META-INF/ANDROIDD.SF
Mar 03, 2015 11:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\ug00334381\Desktop\New folder\gu
ru\Guru99App.apk META-INF/ANDROIDD.RSA
Mar 03, 2015 11:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\ug00334381\Desktop\New folder\gu
ru\Guru99App.apk META-INF/NDKEYSTO.SF
Mar 03, 2015 11:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\ug00334381\Desktop\New folder\gu
ru\Guru99App.apk META-INF/NDKEYSTO.RSA
Mar 03, 2015 11:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Program Files (x86)\Java\jdk1.7.0_51\bin\jarsigner.e
xe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\ug00334381\Desktop\New
 folder\guru\resigned-Guru99App.apk -storepass android -keystore C:\Users\ug0033
4381\.android\debug.keystore C:\Users\ug00334381\Desktop\New folder\guru\Guru99A
pp.apk androiddebugkey
Mar 03, 2015 11:26:51 AM io.selendroid.builder.SelendroidServerBuilder signTestS
erver
INFO: App signing output: jar signed.

Warning:
No -tsa or -tsacert is provided and this jar is not timestamped. Without a times
tamp, users may not be able to validate this jar after the signer certificate's
expiration date (2042-07-14) or after any future revocation date.

Mar 03, 2015 11:26:51 AM io.selendroid.builder.SelendroidServerBuilder signTestS
erver
INFO: The app has been signed: C:\Users\ug00334381\Desktop\New folder\guru\resig
ned-Guru99App.apk
Mar 03, 2015 11:26:51 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe dump badging C:\Users\ug00334381\Desktop\New fol
der\guru\resigned-Guru99App.apk
Mar 03, 2015 11:26:51 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe dump badging C:\Users\ug00334381\Desktop\New fol
der\guru\resigned-Guru99App.apk
Mar 03, 2015 11:26:51 AM io.selendroid.server.model.SelendroidStandaloneDriver i
nitApplicationsUnderTest
INFO: App com.guru99app:1.0 has been added to selendroid standalone server.
Mar 03, 2015 11:26:51 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\UG0033~1\AppData\Local\Temp\andr
oid-driver4181356175947727735.apk META-INF/MANIFEST.MF
Mar 03, 2015 11:26:58 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\UG0033~1\AppData\Local\Temp\andr
oid-driver4181356175947727735.apk META-INF/CERT.RSA
Mar 03, 2015 11:26:59 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\UG0033~1\AppData\Local\Temp\andr
oid-driver4181356175947727735.apk META-INF/CERT.SF
Mar 03, 2015 11:26:59 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\UG0033~1\AppData\Local\Temp\andr
oid-driver4181356175947727735.apk META-INF/ANDROIDD.SF
Mar 03, 2015 11:26:59 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\UG0033~1\AppData\Local\Temp\andr
oid-driver4181356175947727735.apk META-INF/ANDROIDD.RSA
Mar 03, 2015 11:26:59 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\UG0033~1\AppData\Local\Temp\andr
oid-driver4181356175947727735.apk META-INF/NDKEYSTO.SF
Mar 03, 2015 11:26:59 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\aapt.exe remove C:\Users\UG0033~1\AppData\Local\Temp\andr
oid-driver4181356175947727735.apk META-INF/NDKEYSTO.RSA
Mar 03, 2015 11:26:59 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Program Files (x86)\Java\jdk1.7.0_51\bin\jarsigner.e
xe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\UG0033~1\AppData\Local
\Temp\resigned-android-driver4181356175947727735.apk -storepass android -keystor
e C:\Users\ug00334381\.android\debug.keystore C:\Users\UG0033~1\AppData\Local\Te
mp\android-driver4181356175947727735.apk androiddebugkey
Mar 03, 2015 11:26:59 AM io.selendroid.builder.SelendroidServerBuilder signTestS
erver
INFO: App signing output: jar signed.

Warning:
No -tsa or -tsacert is provided and this jar is not timestamped. Without a times
tamp, users may not be able to validate this jar after the signer certificate's
expiration date (2042-07-14) or after any future revocation date.

Mar 03, 2015 11:26:59 AM io.selendroid.builder.SelendroidServerBuilder signTestS
erver
INFO: The app has been signed: C:\Users\UG0033~1\AppData\Local\Temp\resigned-and
roid-driver4181356175947727735.apk
Mar 03, 2015 11:27:00 AM io.selendroid.android.impl.DefaultDeviceManager initial
izeAdbConnection
INFO: my devices: NEXUS5
Mar 03, 2015 11:27:00 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\tools\android.bat list avds
Mar 03, 2015 11:27:01 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\ug00334381\Desktop\New folder\Android-SDK\andr
oid-sdk\platform-tools\adb.exe devices
Mar 03, 2015 11:27:01 AM io.selendroid.server.model.DeviceStore addEmulators
INFO: Adding: AndroidEmulator [screenSize=WVGA800, targetPlatform=ANDROID16, ser
ial=null, avdName=AVDT]
Mar 03, 2015 11:27:01 AM io.selendroid.server.model.DeviceStore addEmulators
INFO: Adding: AndroidEmulator [screenSize=WVGA800, targetPlatform=ANDROID16, ser
ial=emulator-5554, avdName=NEXUS5]
selendroid-standalone server has been started on port: 4444
Exception in thread "Thread-42" java.net.BindException: Address already in use:
bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:444)
        at sun.nio.ch.Net.bind(Net.java:436)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:
214)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSo
cketChannel.java:125)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.
java:476)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChann
elPipeline.java:1021)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractCha
nnelHandlerContext.java:455)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHa
ndlerContext.java:440)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.j
ava:844)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:195)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:339
)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Single
ThreadEventExecutor.java:370)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:744)

**Comment by Ujjwalag** [comment]
please help me out from this issue..

**Comment by operatiay** [comment]
your port 4444 is already used by something.

**Comment by lukeis** [comment]
closing this issue since it seems to be a dumping ground for user issues... please open new issues that have concise reproducible steps for the issues, this one has become unreadable.

**Comment by Ujjwalag** [comment]
hii 
i tried to run the test app on the emulator , but i am not able to do it. i am not finding the step by step approach for this..please help me out from this issue..
Thank in advance.

**Comment by hanizaidi110** [comment]
This worked for me:

http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer

If selenium server is already running on port 4444 then it will shut down the server and says OKOK if selenium is not running on this port 4444 then by hitting above url will give you "Unable to connect"

**Comment by ravindra5557** [comment]
Hello every one 

i am getting below error while launching selendroid server , please help me to resolve 
D:\Ravindra_Backup_3rdmarch\Mobile Automation Tools\Selendroid>java -jar selendr
oid-standalone-0.17.0-with-dependencies.jar -app D:\Ravindra_Backup_3rdmarch\Mob
ile Automation Tools\Selendroid\apps\selendroid-test-app-0.17.0.apk
Apr 06, 2016 2:50:24 PM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Selendroid #################
Apr 06, 2016 2:50:24 PM io.selendroid.standalone.SelendroidLauncher parseConfig
SEVERE: An error occurred while starting selendroid
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed m
ain parameter 'Automation' but no main parameter was defined
        at com.beust.jcommander.JCommander.getMainParameter(JCommander.java:903)

        at com.beust.jcommander.JCommander.parseValues(JCommander.java:748)
        at com.beust.jcommander.JCommander.parse(JCommander.java:279)
        at com.beust.jcommander.JCommander.parse(JCommander.java:262)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:207)
        at io.selendroid.standalone.SelendroidLauncher.parseConfig(SelendroidLau
ncher.java:43)
        at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.j
ava:106)

Regards
ravi

**Comment by hanizaidi110** [comment]
paste your code here

Syed Muhammad Hani Zaidi
Phone: +923368317620
Skype: hanizaidi1
s.hani@khi.iba.edu.pk
