### ISSUE TITLE
How to do single tap using coordinates x,y

### ISSUE THREAD

**Issue by anudeepsinghpatelgithub** [selendroid/selendroid#429]
Hi,

I tried method singleTap(Coordinates where) i.e. Allows the execution of single tap on the screen, analogous to click using a Mouse.
Parameters:where The location on the screen. Typically a WebElement,

But is there any way to singleTab inside a web element with coordinates.

e.g. i want to click inside a webelement on the coordinates x-20,y-50

Thanks
Anudeep

**Comment by ayosuva** [comment]
@anudeepsinghpatelgithub

How you solved the above problem ?
I am also looking for the same.

Thanks,
Yosuva A

**Comment by anudeepsinghpatelgithub** [comment]
Hi,

You can follow this
http://grepcode.com/file/repo1.maven.org/maven2/io.selendroid/selendroid-server/0.4.2/io/selendroid/server/model/TouchScreen.java

Thanks
Anudeep
