### ISSUE TITLE
Run test on device by serial works incorrect.

### ISSUE THREAD

**Issue by a-shynkevich** [selendroid/selendroid#443]
(It is duplicate of closed issue #311 and #314.)

Good day!
I use selendroid 0.10 but I have the same issue when I try run my test on the specific ID. 
I use two " Nexus 5", one of them 4.4.2 version second 4.4.3 version. (For both the same Android 19 API)

PS: It seems that test runs on the device that first in the devices list in command shell.

**Comment by nareshnnk** [comment]
Hi,
I am still getting this issue with standalone server 0.12.I am using devices Galaxy S4 and Nexus5 and even after I use setSerial("xxx") method ,it is defaulting to top device in adb devices list

**Comment by nareshnnk** [comment]
Hi I am still seeing this issue on 1.12.0.appears that standalone server 0.12 defaults to the top device in adb devices list.
