### ISSUE TITLE
Not able to stimulate "send" key event from soft keypad

### ISSUE THREAD

**Issue by raghunadhkothuri** [selendroid/selendroid#499]
Hi,
I'm testing a scenario where i need to send a message, I entered text in the editor and need to tap on Send key(Which is replaced by Done) to send the message 
I tried with the following code 
if (driver.findElement(By.id("callwindow_user_name")).getText()
                        .contains("PRASHANT")) {

```
                driver.findElement(By.id("chat_text_field")).click();
                driver.findElement(By.id("chat_text_field")).sendKeys(
                        "Testing chat");
                Runtime.getRuntime().exec("adb shell input keyevent 4");
```

Following is the key event code for send given by Android but on executing this keypad is getting closed, Send action is not performed.

is there any way to stimulate send key action?

![send](https://cloud.githubusercontent.com/assets/8123748/3692020/66de20b2-1358-11e4-9192-62167c058977.PNG)

**Comment by ayosuva** [comment]
@raghunadhkothuri 

I am also facing same issue in android 2.3.7(Ginger Bread) and I tried below commands but that is also not working.so can you please into this issue #1094  
Runtime.getRuntime().exec("adb shell input keyevent 61");
Runtime.getRuntime().exec("adb shell input keyevent 66");
