### ISSUE TITLE
Fix End-to-End Tests

### ISSUE THREAD

**Issue by ains** [selendroid/selendroid#625]
Some E2E tests are broken due to changes in Selendroid or changes in the test app that haven't been accounted for in the test suite. Lets get the test suite all green so it's easier to keep it that way in future.

These tests were run under API19 (4.4.2)

Failed tests:
- [ ]  NativeElementFindingTest.shouldNotFindElementByIdFromPreviousActivity:300 The element from previous screen should not be found.
- [ ]  NativeElementInteractionTest.shouldScrollAndEnterText:208 expected:<true> but was:<false>

Tests in error:
- [X]  AdbConnectionTest.shouldSendTextViaAdb:48 » StaleElementReference The element ...
- [x]  AdbConnectionTest.shouldSendKeyEventViaAdb:60 » Runtime Condition timed out: u...
- [ ]  ExecuteAsyncScriptTest.shouldBeAbleToReturnArraysOfWebElementsFromAsyncScripts:112 » StaleElementReference
- [ ]  ExecuteAsyncScriptTest.shouldBeAbleToReturnWebElementsFromAsyncScripts:98 » StaleElementReference
- [x]  SelendroidUnknownCommandHandlingTest.shouldNotRefresh »  Unexpected exception,...
- [x]  SelendroidUnknownCommandHandlingTest.testShouldNotBeAbleToGoForward »  Unexpec...
- [x]  ExtensionLoadTest.extensionCallShouldSucceed:12 » WebDriver Didn't find class ...
- [ ]  NativeChildElementFindingTest.shouldFindChildButtonsByName:247 » StaleElementReference
- [ ]  NativeChildElementFindingTest.shouldFindChildButtonByClass:161 » StaleElementReference
- [ ] WaitForProgressBarGoneAwayTest.shouldPassWithRightTimeoutUsingLinkTextLocator:61->startTimeOutTest:80 » StaleElementReference

- [ ] WaitForProgressBarGoneAwayTest.shouldPassWithRightTimeoutUsingNameLocator:54->startTimeOutTest:80 » StaleElementReference
- [ ] WaitForProgressBarGoneAwayTest.shouldPassWithRightTimeoutUsingIdLocator:47->startTimeOutTest:80 » StaleElementReference
  WebElementFindingTest.shouldGetBodyDOMElementViaJavascript:338 » StaleElementReference

**Comment by asm89** [comment]
Most tests are ok now. I have pull requests that either fix or remove the other broken ones. Closing this issue. If someone feels strongly about the disabled tests feel free to open new issues.
