### ISSUE TITLE
Geolocation : Can it be configured ?

### ISSUE THREAD

**Issue by RobinDev** [selendroid/selendroid#716]
Hello,

I try to test an app geolocation settings set. I search every where (equally in the source code) and find nothing to change the geolocation parameters.

Any idea ?

Thank you.

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
