### ISSUE TITLE
Error occured while communicating with selendroid server on the device:

### ISSUE THREAD

**Issue by rahul9580** [selendroid/selendroid#722]
Hi,
I am getting above error intermittently. I have automated about 20 test cases out of them same test case some time works fine but some time above error appear. Also During the test case run I found the same error, So we can not bereave the results generated. Please suggest how to avoid such miss happenings.
If the automation build is not reliable, Automation is useless.

Please find the complete log:
[testng] Wait for '2' seconds
   [testng] Launching 'android_web' browser
   [testng] Start remote execution
   [testng] Get TestData Excel:-'ProductTestData.xls', Sheet:- 'PaymentType'
   [testng] Get TestData Excel:-'ProductTestData.xls', Sheet:- 'TransactionDetails'
   [testng] Navigate to web page- 'https://test.payu.in/admin/home'
   [testng] Added the cookie - Name: 'test_name' Value: 'Test.AdminPanel.MobilePayments.MobileTestTransactionCC.test_CC_AXIS' Domain: '.payu.in' Expiry: 'Wed Nov 26 18:08:35 IST 2014'
   [testng] Wait for page load by waiting for element [link text: Admin Login]
   [testng] Click on 'Admin Login link'
   [testng] Wait for page load by waiting for element [id: username]
   [testng] Enter the User name as 'qc2'
   [testng] Enter the Password as 'Password2'
   [testng] Click on 'Submit Button'
   [testng] Unable to take screenshot:- org.openqa.selenium.WebDriverException: Error occured while communicating with selendroid server on the device: 
   [testng] io.selendroid.exceptions.SelendroidException: Error occured while communicating with selendroid server on the device: 
   [testng] 	at io.selendroid.server.handler.RequestRedirectHandler.handle(RequestRedirectHandler.java:74)
   [testng] 	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
   [testng] 	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
   [testng] 	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:50)
   [testng] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
   [testng] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
   [testng] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
   [testng] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
   [testng] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
   [testng] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
   [testng] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
   [testng] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
   [testng] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
   [testng] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
   [testng] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
   [testng] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
   [testng] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
   [testng] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
   [testng] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
   [testng] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
   [testng] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
   [testng] 	at java.lang.Thread.run(Unknown Source)
   [testng] Caused by: java.net.SocketException: Connection reset
   [testng] 	at java.net.SocketInputStream.read(Unknown Source)
   [testng] 	at java.net.SocketInputStream.read(Unknown Source)
   [testng] 	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
   [testng] 	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
   [testng] 	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
   [testng] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
   [testng] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
   [testng] 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
   [testng] 	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
   [testng] 	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
   [testng] 	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:197)
   [testng] 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
   [testng] 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
   [testng] 	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
   [testng] 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
   [testng] 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
   [testng] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
   [testng] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
   [testng] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
   [testng] 	at io.selendroid.server.util.HttpClientUtil.executeRequest(HttpClientUtil.java:75)
   [testng] 	at io.selendroid.server.handler.RequestRedirectHandler.redirectRequest(RequestRedirectHandler.java:106)
   [testng] 	at io.selendroid.server.handler.RequestRedirectHandler.handle(RequestRedirectHandler.java:64)
   [testng] 	... 21 more

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
