### ISSUE TITLE
ErrorError checking if selendroid-server has started

### ISSUE THREAD

**Issue by planza5** [selendroid/selendroid#726]
<h5>Hello,

<h5>Im dont know what is hapenning. When I launch my test I get an error in selendroid-standalone server. The trace...

INFO: The app has been signed: C:\Users\Pablo\AppData\Local\Temp\selendroid-server-com.pablo-0.12.0.apk
nov 28, 2014 10:04:38 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 install -r C:\Users\Pablo\AppData\Local\Temp\selendroid-server-com.pablo-0.12.0.apk
running command: adb shell setprop log.tag.SELENDROID ERROR
nov 28, 2014 10:04:46 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 shell setprop log.tag.SELENDROID ERROR
nov 28, 2014 10:04:46 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe dump badging C:\proyectos\selendroid\resigned-Pablo.apk
nov 28, 2014 10:04:46 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 shell am instrument -e main_activity com.pablo.MainActivity -e server_port 8080 io.selendroid.com.pablo/io.selendroid.ServerInstrumentation
nov 28, 2014 10:04:47 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:8080 tcp:8080
nov 28, 2014 10:04:47 PM io.selendroid.android.impl.AbstractDevice startLogging
INFO: starting logcat:
Cleaning up unclosed ZipFile for archive C:\Users\Pablo\AppData\Local\Temp\selendroid-server6793077980423246277.apk
nov 28, 2014 10:04:47 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Using url: http://localhost:8080/wd/hub/status
nov 28, 2014 10:04:47 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8080: Connection reset
nov 28, 2014 10:04:47 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8080
nov 28, 2014 10:04:47 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8080: Connection reset
nov 28, 2014 10:04:47 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8080
nov 28, 2014 10:04:47 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8080: Connection reset
nov 28, 2014 10:04:47 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8080
nov 28, 2014 10:04:47 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Error checking if selendroid-server has started.
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
...
...

<h5>My JUnit test:

SelendroidCapabilities cap=SelendroidCapabilities.device("com.pablo:1.0");
cap.setEmulator(true);
SelendroidDriver driver=new SelendroidDriver(cap);
driver.switchTo().window("NATIVE_APP");
driver.findElement(By.id("textView1"));

<h5>I launch selendroid server with this command:

java -jar selendroid-standalone-0.12.0-with-dependencies.jar -app Pablo.apk -forceReinstall

<h5>I tried launching the server changing the emulatorPort without sucess:

java -jar selendroid-standalone-0.12.0-with-dependencies.jar -app Pablo.apk -forceReinstall -emulatorPort 38080

<h5>Thanks in advance

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
