### ISSUE TITLE
Support `adb shell input roll`

### ISSUE THREAD

**Issue by operatiay** [selendroid/selendroid#737]
While manually trying several direct `adb shell input` commands I've figured out that the command to `roll` works the best when operating with dropdown lists (in android called _spinner_), where android recycles views to display different entries.

The input it would be operating on is a `trackball`, not a `touchscreen`.

Is there any special reason why it hasn't been implemented till now?

@lukeis , @DominikDary , where would you see it implemented? I don't really feel comfortable putting it under `TouchActions`, especially because it's not really combinable with other touch actions. It feels more like a keyboard action. Or even a device specific implementation of `scroll`...

any ideas?

**Comment by danielrobertson** [comment]
Can we close this issue?
