### ISSUE TITLE
App quits automatically during runtime while running the java file under testNg

### ISSUE THREAD

**Issue by cheth09** [selendroid/selendroid#742]
Consider a scenario where the screen is loading and it is fetching few data from the server. Now app quits on itself while the test case is running. Not sure what could be the reason.

Here App is try to fetch the data and display on the screen, hence app shows loading spinner. When loading spinner appears and our script is running, automatically app quits.

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
