### ISSUE TITLE
Selendroid Insepctor can not load properties

### ISSUE THREAD

**Issue by vickykm2000** [selendroid/selendroid#743]
Dear Dominik,

Selendroid Inspector can not load properties. Its showing loading progress bar  and not able to load  web element viewer. I am facing this issue on "in.redbus.android.apk" (redbus apk).

Please help.
![issue](https://cloud.githubusercontent.com/assets/7531136/5377885/22f6095c-80ac-11e4-9e47-c219b9b880c6.png)

**Comment by Naina09** [comment]
i am new to mobile testing as well as Selendroid.. can anyone tell how to we inspect elements while working with Selendroid ? Like for inspecting elements for a Web application we had Firebug..

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
