### ISSUE TITLE
[Enquiry] Save Selendroid server log messages to a file

### ISSUE THREAD

**Issue by Hassan-Radi** [selendroid/selendroid#751]
I am using Selendroid version 0.10. I can see that there is a capability to set the log level for the Selendroid server, but I was wondering if the Selendroid server has a capability or something I am not aware of that allows me to save log messages to a file.

I am aware that I can redirect system output to a file, but this workaround will include both Selendroid and non-selendroid messages.

**Comment by asm89** [comment]
Selendroid server on the device logs to logcat. I suggest capturing that output and filtering for the SELENDROID tag.
