### ISSUE TITLE
Resigning Error while running: java -jar selendroid-standalone-0.1 2.0-with-dependencies.jar -app selendroid-test-app-0.12.0.apk

### ISSUE THREAD

**Issue by gaurav00504** [selendroid/selendroid#757]
Please help on this error:

C:\Users\Gaurav\Desktop\Workspace\selendroid>java -jar selendroid-standalone-0.1
2.0-with-dependencies.jar -app selendroid-test-app-0.12.0.apk
###### ########### Configuration in use

io.selendroid.SelendroidConfiguration@2f2c9b19[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[selendroid-test-app-0.12.0.apk]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  keystorePassword=<null>
  keystoreAlias=<null>
  emulatorOptions=<null>
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
  deviceLog=true
  serverStartTimeout=20000
  printHelp=false
]
Dec 17, 2014 11:16:43 PM io.selendroid.SelendroidLauncher launchServer
INFO: Starting selendroid-server port 4444
Dec 17, 2014 11:16:44 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\Gaurav\Desktop\Workspace\android-sdk-windows\b
uild-tools\21.1.2\aapt.exe remove C:\Users\Gaurav\Desktop\Workspace\selendroid\s
elendroid-test-app-0.12.0.apk META-INF/MANIFEST.MF
Dec 17, 2014 11:16:44 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\Gaurav\Desktop\Workspace\android-sdk-windows\b
uild-tools\21.1.2\aapt.exe remove C:\Users\Gaurav\Desktop\Workspace\selendroid\s
elendroid-test-app-0.12.0.apk META-INF/CERT.RSA
Dec 17, 2014 11:16:44 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\Gaurav\Desktop\Workspace\android-sdk-windows\b
uild-tools\21.1.2\aapt.exe remove C:\Users\Gaurav\Desktop\Workspace\selendroid\s
elendroid-test-app-0.12.0.apk META-INF/CERT.SF
Dec 17, 2014 11:16:44 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\Gaurav\Desktop\Workspace\android-sdk-windows\b
uild-tools\21.1.2\aapt.exe remove C:\Users\Gaurav\Desktop\Workspace\selendroid\s
elendroid-test-app-0.12.0.apk META-INF/ANDROIDD.SF
Dec 17, 2014 11:16:44 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\Gaurav\Desktop\Workspace\android-sdk-windows\b
uild-tools\21.1.2\aapt.exe remove C:\Users\Gaurav\Desktop\Workspace\selendroid\s
elendroid-test-app-0.12.0.apk META-INF/ANDROIDD.RSA
Dec 17, 2014 11:16:44 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\Gaurav\Desktop\Workspace\android-sdk-windows\b
uild-tools\21.1.2\aapt.exe remove C:\Users\Gaurav\Desktop\Workspace\selendroid\s
elendroid-test-app-0.12.0.apk META-INF/NDKEYSTO.SF
Dec 17, 2014 11:16:44 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\Gaurav\Desktop\Workspace\android-sdk-windows\b
uild-tools\21.1.2\aapt.exe remove C:\Users\Gaurav\Desktop\Workspace\selendroid\s
elendroid-test-app-0.12.0.apk META-INF/NDKEYSTO.RSA
Dec 17, 2014 11:16:44 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Program Files\Java\jdk1.8.0_25\bin\bin\keytool.exe -
genkey -v -keystore C:\Users\Gaurav.android\debug.keystore -storepass android -
alias androiddebugkey -keypass android -dname CN=Android Debug,O=Android,C=US -s
toretype JKS -sigalg MD5withRSA -keyalg RSA -validity 9999
Dec 17, 2014 11:16:44 PM io.selendroid.SelendroidLauncher launchServer
SEVERE: Error occurred while building server: An error occurred while resigning
the app 'selendroid-test-app-0.12.0.apk'.
io.selendroid.exceptions.SessionNotCreatedException: An error occurred while res
igning the app 'selendroid-test-app-0.12.0.apk'.
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplication
sUnderTest(SelendroidStandaloneDriver.java:116)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(Selendro
idStandaloneDriver.java:84)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidS
erver(SelendroidStandaloneServer.java:61)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStan
daloneServer.java:50)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java
:64)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:112)
Caused by: io.selendroid.exceptions.ShellCommandException: An error occured whil
e executing shell command: C:\Program Files\Java\jdk1.8.0_25\bin\bin\keytool.exe
 -genkey -v -keystore C:\Users\Gaurav.android\debug.keystore -storepass android
 -alias androiddebugkey -keypass android -dname CN=Android Debug,O=Android,C=US
-storetype JKS -sigalg MD5withRSA -keyalg RSA -validity 9999
        at io.selendroid.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.builder.SelendroidServerBuilder.signTestServer(Selendro
idServerBuilder.java:275)
        at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidSer
verBuilder.java:153)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplication
sUnderTest(SelendroidStandaloneDriver.java:114)
        ... 5 more
Caused by: io.selendroid.exceptions.ShellCommandException:
        ... 9 more
Exception in thread "main" io.selendroid.exceptions.SessionNotCreatedException:
An error occurred while resigning the app 'selendroid-test-app-0.12.0.apk'.
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplication
sUnderTest(SelendroidStandaloneDriver.java:116)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(Selendro
idStandaloneDriver.java:84)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidS
erver(SelendroidStandaloneServer.java:61)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStan
daloneServer.java:50)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java
:64)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:112)
Caused by: io.selendroid.exceptions.ShellCommandException: An error occured whil
e executing shell command: C:\Program Files\Java\jdk1.8.0_25\bin\bin\keytool.exe
 -genkey -v -keystore C:\Users\Gaurav.android\debug.keystore -storepass android
 -alias androiddebugkey -keypass android -dname CN=Android Debug,O=Android,C=US
-storetype JKS -sigalg MD5withRSA -keyalg RSA -validity 9999
        at io.selendroid.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.builder.SelendroidServerBuilder.signTestServer(Selendro
idServerBuilder.java:275)
        at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidSer
verBuilder.java:153)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplication
sUnderTest(SelendroidStandaloneDriver.java:114)
        ... 5 more
Caused by: io.selendroid.exceptions.ShellCommandException:
        ... 9 more

**Comment by jainvijay1975** [comment]
Facing same issue : 
JAVA_HOME = d:\Software\JAVA\bin (This folder contains java.exe, keytool and other bin files
When I start 
D:\Software\Selendroid>java -jar selendroid-standalone-0.12.0-with-dependencies.jar -app selendroid-test-app-0.12.0.apk

Getting the same error as gaurav. Please help

**Comment by operatiay** [comment]
please don't comment on closed issues (especially if it's not your own one.

here's a description how to set JAVA_HOME properly in Windows (you can google for it if you don't like this description): https://confluence.atlassian.com/display/DOC/Setting+the+JAVA_HOME+Variable+in+Windows
