### ISSUE TITLE
selendroid-common 0.13.0-SNAPSHOT is missing from oss-sonatype repository

### ISSUE THREAD

**Issue by surg** [selendroid/selendroid#762]
https://oss.sonatype.org/content/repositories/snapshots/io/selendroid/selendroid-common/0.13.0-SNAPSHOT/

There are all sorts of checksums there, but no actual pom and jar files.

**Comment by surg** [comment]
anyone?

**Comment by lukeis** [comment]
not sure why that is not showing up... @DominikDary if you have a moment, could you look?

Otherwise, the standalone is showing up:
https://oss.sonatype.org/content/repositories/snapshots/io/selendroid/selendroid-standalone/0.13.0-SNAPSHOT/

**Comment by asm89** [comment]
Closing. Newer releases should be available.
