### ISSUE TITLE
Add ability to restart app

### ISSUE THREAD

**Issue by mitchhentges** [selendroid/selendroid#778]
It is helpful to be able to test app state after it is restarted.

__Acceptance criteria:__
- Running `driver().restartApp();` should close and reopen the app
- When the app is restarted, the driver's state should be as it is at the start of a session

**Comment by jankowskirobert** [comment]
but i think it's more safety to driver.quit() then initialize it again.

**Comment by lukeis** [comment]
is backgrounding / foregrounding sufficient for you?

https://github.com/selendroid/selendroid/blob/master/selendroid-client/src/main/java/io/selendroid/client/SelendroidDriver.java#L235-L242

**Comment by mitchhentges** [comment]
Unfortunately not, it needs to be a full restart :(

**Comment by lukeis** [comment]
that may prove unfeasible, since 'killing' the app will also stop the instrumentation process.

I think your best best is to quit / start a new session... but make sure you use the -noClearData option when starting your server.

**Comment by asm89** [comment]
You should probably do this in user land instead by quitting and starting a new session.

**Comment by zaxy78** [comment]
@asm89  I'm trying to quit() + starting a new session and I getting an exception:

```java
class MyDriver extends SelendroidDriver {

// ....

 public restartApp() {
   super.quit();
  try {
      startClient();
      startSession(mCapabilities, null );
    } catch (RuntimeException e) {
      throw e; // <--- getting an UnreachableBrowserException
    }
}
```

```
UnreachableBrowserException: Could not start a new session. 
Possible causes are invalid address of the remote server or browser start-up failure.
```
