### ISSUE TITLE
Not able to start Selendorid Server

### ISSUE THREAD

**Issue by Sujith28** [selendroid/selendroid#781]
I'm working on windows 7 64 bit machine. 
JAVA_HOME = C:\Program Files\Java\jdk1.8.0_25 and ANDROID_HOME = C:\adt-64bit\sdk, please help me to resolve this issue.

C:\Sujith>java -jar selendroid-standalone-0.12.0-with-dependencies.jar -app selendroid-test-app-0.12.0.apk
################# Configuration in use #################
io.selendroid.SelendroidConfiguration@2f2c9b19[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[selendroid-test-app-0.12.0.apk]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  keystorePassword=<null>
  keystoreAlias=<null>
  emulatorOptions=<null>
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
  deviceLog=true
  serverStartTimeout=20000
  printHelp=false
]
Jan 13, 2015 11:00:53 AM io.selendroid.SelendroidLauncher launchServer
INFO: Starting selendroid-server port 4444
Jan 13, 2015 11:00:53 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Sujith\selendroid-test-app-0.12.0.apk META-INF/MANIFEST.MF
Jan 13, 2015 11:00:53 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Sujith\selendroid-test-app-0.12.0.apk META-INF/CERT.RSA
Jan 13, 2015 11:00:54 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Sujith\selendroid-test-app-0.12.0.apk META-INF/CERT.SF
Jan 13, 2015 11:00:54 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Sujith\selendroid-test-app-0.12.0.apk META-INF/ANDROIDD.SF
Jan 13, 2015 11:00:54 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Sujith\selendroid-test-app-0.12.0.apk META-INF/ANDROIDD.RSA
Jan 13, 2015 11:00:54 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Sujith\selendroid-test-app-0.12.0.apk META-INF/NDKEYSTO.SF
Jan 13, 2015 11:00:54 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Sujith\selendroid-test-app-0.12.0.apk META-INF/NDKEYSTO.RSA
Jan 13, 2015 11:00:54 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Sujith\resigned-selendro
id-test-app-0.12.0.apk -storepass android -keystore C:\Users\Sujith.p\.android\debug.keystore C:\Sujith\selendroid-test-app-0.12.0.apk androiddebugkey

Jan 13, 2015 11:00:55 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning:
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer cert
ificate's expiration date (2044-03-19) or after any future revocation date.

Jan 13, 2015 11:00:55 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: C:\Sujith\resigned-selendroid-test-app-0.12.0.apk
Jan 13, 2015 11:00:55 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe dump badging C:\Sujith\resigned-selendroid-test-app-0.12.0.apk
Jan 13, 2015 11:00:55 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe dump badging C:\Sujith\resigned-selendroid-test-app-0.12.0.apk
Jan 13, 2015 11:00:55 AM io.selendroid.server.model.SelendroidStandaloneDriver initApplicationsUnderTest
INFO: App io.selendroid.testapp:0.12.0 has been added to selendroid standalone server.
Jan 13, 2015 11:00:55 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Windows\TEMP\android-driver8196165181920971711.apk META-INF/MAN
IFEST.MF
Jan 13, 2015 11:00:55 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Windows\TEMP\android-driver8196165181920971711.apk META-INF/CER
T.RSA
Jan 13, 2015 11:00:55 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Windows\TEMP\android-driver8196165181920971711.apk META-INF/CER
T.SF
Jan 13, 2015 11:00:55 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Windows\TEMP\android-driver8196165181920971711.apk META-INF/AND
ROIDD.SF
Jan 13, 2015 11:00:55 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Windows\TEMP\android-driver8196165181920971711.apk META-INF/AND
ROIDD.RSA
Jan 13, 2015 11:00:55 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Windows\TEMP\android-driver8196165181920971711.apk META-INF/NDK
EYSTO.SF
Jan 13, 2015 11:00:55 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\build-tools\android-4.4.2\aapt.exe remove C:\Windows\TEMP\android-driver8196165181920971711.apk META-INF/NDK
EYSTO.RSA
Jan 13, 2015 11:00:55 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Windows\TEMP\resigned-an
droid-driver8196165181920971711.apk -storepass android -keystore C:\Users\Sujith.p\.android\debug.keystore C:\Windows\TEMP\android-driver8196165181920
971711.apk androiddebugkey
Jan 13, 2015 11:00:56 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning:
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer cert
ificate's expiration date (2044-03-19) or after any future revocation date.

Jan 13, 2015 11:00:56 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: C:\Windows\TEMP\resigned-android-driver8196165181920971711.apk
Jan 13, 2015 11:00:56 AM io.selendroid.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=ac7bd84, model=null, targetVersion=null]
Jan 13, 2015 11:00:56 AM io.selendroid.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=ac7bd84, model=XP6700, targetVersion=ANDROID19]
Jan 13, 2015 11:00:56 AM io.selendroid.android.impl.DefaultDeviceManager initializeAdbConnection
INFO: my devices: null
Jan 13, 2015 11:00:56 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-64bit\sdk\tools\android.bat list avds
Jan 13, 2015 11:00:56 AM io.selendroid.SelendroidLauncher launchServer
SEVERE: Error occurred while building server: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: C:\adt-6
4bit\sdk\tools\android.bat list avds
io.selendroid.exceptions.AndroidDeviceException: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: C:\ad
t-64bit\sdk\tools\android.bat list avds
        at io.selendroid.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:119)
        at io.selendroid.server.model.DeviceStore.initAndroidDevices(DeviceStore.java:121)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:156)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:85)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:61)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:50)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:64)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:112)
Caused by: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: C:\adt-64bit\sdk\tools\android.bat list avd
s
        at io.selendroid.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:117)
        ... 7 more
Caused by: io.selendroid.exceptions.ShellCommandException:
        ... 9 more
Exception in thread "main" java.lang.RuntimeException: io.selendroid.exceptions.AndroidDeviceException: io.selendroid.exceptions.ShellCommandException
: An error occured while executing shell command: C:\adt-64bit\sdk\tools\android.bat list avds
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:75)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:112)
Caused by: io.selendroid.exceptions.AndroidDeviceException: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell com
mand: C:\adt-64bit\sdk\tools\android.bat list avds
        at io.selendroid.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:119)
        at io.selendroid.server.model.DeviceStore.initAndroidDevices(DeviceStore.java:121)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:156)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:85)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:61)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:50)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:64)
        ... 1 more
Caused by: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: C:\adt-64bit\sdk\tools\android.bat list avd
s
        at io.selendroid.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:117)
        ... 7 more
Caused by: io.selendroid.exceptions.ShellCommandException:
        ... 9 more

**Comment by operatiay** [comment]
are you able to execute this command manually? ```C:\adt-64bit\sdk\tools\android.bat list avds```

**Comment by CharlesBrandeis** [comment]
can you delete the old version of the selendroid from your device manually ?

**Comment by Sujith28** [comment]
@operatiay @CharlesBrandeis Thank you...C:\adt-64bit\sdk\tools\android.bat path android.bat file was not there..now I changed and it's working fine...I'm able to execute some scripts on web application.

@operatiay @CharlesBrandeis : Could you please share sample examples(calculator, message)  for native application testing scripts...Thanks in advance

**Comment by operatiay** [comment]
@Sujith28 glad that you've found your error. for examples have a look at selendroid internal tests (https://github.com/selendroid/selendroid/tree/master/selendroid-test-app/src/test/java/io/selendroid).

**Comment by Sujith28** [comment]
@operatiay  Thank you very much :)
