### ISSUE TITLE
Release Selendroid 0.13.0

### ISSUE THREAD

**Issue by smiklosovic** [selendroid/selendroid#783]
Hi @DominikDary @lukeis 

I would like to see Selendroid 0.13 released. There is a lot of changes since 0.12. We want to release something which depends on Selendroid and we do not want to be behind in the long run and stick with 0.12 if Selendroid would be released pretty soon.

Any time estimation of 0.13 release?

As discussed with @asm89 on IRC, it would be nice to have Selendroid releases more frequently, even better regularly - bimonthly releases would be awesome. In this fast changing area as mobile testing is, waiting for months feels like eternity.

**Comment by asm89** [comment]
These are the changes since `0.12.0`: https://github.com/selendroid/selendroid/compare/0.12.0...master. I'm :+1: for doing a release. Since we're in `0.x` we could release more often after `0.13` as well.

What are your thoughts @DominikDary?

**Comment by asm89** [comment]
@smiklosovic I shortly chatted with Dominik today. He'll try to get out 0.13.x soon, maybe even tonight if possible. He also likes the idea of doing more frequent smaller releases in the upcoming time. :+1: 

cc @selendroid/contributers

**Comment by mach6** [comment]
awesome news. :+1:

**Comment by DominikDary** [comment]
is done :-)

**Comment by asm89** [comment]
Thank you @DominikDary ! :+1:
