### ISSUE TITLE
Android and Fragments.. heavy battle

### ISSUE THREAD

**Issue by jankowskirobert** [selendroid/selendroid#786]
Could some one give me some idea how to wait on element by "wait.until(...)" statment If selendroid load all "fragments" of android application, even those which are not on the visible screen? Can i in some way part XML ?

**Comment by operatiay** [comment]
are you checking for '.isDisplayed()'?

**Comment by jankowskirobert** [comment]
no. i will try. and then i'll give respons

**Comment by jankowskirobert** [comment]
and.... no it is not working. Sometimes it is printing positions like a -1090 per 300; probably it's catching other element on isDiplayed() flag. :/ sad..

**Comment by operatiay** [comment]
this works for me...
```
		ExpectedCondition<WebElement> eCondition = new ExpectedCondition<WebElement>() {
			@Override
			public WebElement apply(final WebDriver condDriver) {
				// try to find the element (it should be displayed)
				List<WebElement> elements = condDriver.findElements(finder);
				for (WebElement webElement : elements) {
					try {
						if (webElement.isDisplayed()) {
							return webElement;
						}
					} catch (StaleElementReferenceException e) {
						// proceed with the next element
					}
				}
				return null;
			}
		};
```

**Comment by jankowskirobert** [comment]
nope.. still the same situation. And notice that, im talking about android fragments where you have few pages which are moved. Inspector is showing button with some id few time but in other locations. Just not displayed elements on the screen but all in one page/activity

**Comment by operatiay** [comment]
if not displayed elements are returning `true` when requested then the implementation of `.isDisplayed()` has an error.
can you verify that all those elements having the same id are returning `true` for `.isDisplayed()`?

**Comment by jankowskirobert** [comment]
i will show you this on pic.
![gitsdk](https://cloud.githubusercontent.com/assets/5741221/5966920/d482da28-a808-11e4-9198-ee568a688d46.jpg)

the blue square is visible screen for user and these two green are the fragments loaded on blue activity. Purple is same element on few screen with the same id for example "buttonOK". And now the "problem" i cant identify these elements i cant make "wait.until() on them cause Inspector is loading full activity which is containing that fragments too with id's. and when i try wait to "isDisplayed" then i got randomly this element on left or on right. Inspector is not loading displayed elements but all elements from specify activity class.

**Comment by operatiay** [comment]
what about the coordinates? you can use the screen size (maybe width) to determine whether the received element is in the central width as opposed to left or right.

**Comment by jankowskirobert** [comment]
i am testing it on few different devices, :/ probably i will need to specify my own lib to do this.

**Comment by operatiay** [comment]
use something like this `((SelendroidCapabilities)getSelendroidDriver().getCapabilities()).getScreenSize()` to get the screen size

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
