### ISSUE TITLE
Running test on multiple android devices

### ISSUE THREAD

**Issue by KunalKathrotia** [selendroid/selendroid#790]
Hi @DominikDary, thank you sir for your great work, i am new to selendroid (and selenium) and i want to run the test case UserRegistrationTest in demo-project of selendroid on more than 1 (let's say 3) devices in parallel . How can i achieve that, can you please guide me ? Thanks again.

**Comment by operatiay** [comment]
use this https://code.google.com/p/selenium/wiki/Grid2

and this http://selendroid.io/scale.html

**Comment by KunalKathrotia** [comment]
Thanks for you response. I've gone through those links you have mentioned, and i am able to start the selendroid-standalone server and the grid with the selendroid-grid-plugin as well. I am also able to register the node to the grid maxInstance=5, but when i run the test it runs only on the first device among two devices i.e. connected. What i want is to run the test cases in both the attached devices in parallel. please guide me if i am missing something.

**Comment by operatiay** [comment]
If both devices are suitable for the test execution you just need to start the test a second time while the first one is still running. Alternatively you can restrict the test execution to a specific device. See here: http://selendroid.io/setup.html#DesiredCapabilities

**Comment by KunalKathrotia** [comment]
Thanks that is working. However, that's not what i wished. i wish to run that test case in both the devices with one time initiation. Is there any workaround?

**Comment by operatiay** [comment]
There's no need for a workaround. This is not a Selendroid issue.
Depending on your implementation you could use something like TestNG configuration to start those two executions "simultaneously".
