### ISSUE TITLE
Add support for getting the resourceId attribute of an element

### ISSUE THREAD

**Issue by paymand** [selendroid/selendroid#791]
Appium has added it recently: https://github.com/appium/appium/pull/4068
Would be nice to have this feature in Selendroid as well.

**Comment by paymand** [comment]
@bootstraponline

**Comment by bootstraponline** [comment]
:+1:

**Comment by lukeis** [comment]
been there for a long time :)

element.get_attribute("nativeid")

or you might be talking about:

element.get_attribute("id")


one of those should be what you're looking for

**Comment by paymand** [comment]
Awesome! For future reference, ``element.get_attribute("nativeid")`` does the trick. thanks!
