### ISSUE TITLE
Server log does not contain information about queries and responses since 0.13

### ISSUE THREAD

**Issue by PavelKulagin** [selendroid/selendroid#793]
Till Selendroid 0.12 there were some useful messages in a log, describing queries to server on device and responses to tests. It was like: INFO: Payload? {"using":"id","value":"login_button"}
Since Selendroid 0.13 they are gone. I cannot see them even using -verbose and -loglevel VERBOSE. Could you please return them back, it was very useful. Or, if they just moved to another place, could you, please tell me where to find those logs?

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
