### ISSUE TITLE
Selendroid searches in top level views that are not visible

### ISSUE THREAD

**Issue by asm89** [selendroid/selendroid#800]
In some cases selendroid ends up looking for elements in multiple top level views. I have a few questions about that:

1) What are valid cases where selendroid should look at multiple top level views?
2) Currently selendroid's `searchElements()` will also search for elements in views that are not the current root view. Is that intended behavior or a bug?

It seems that it's unintended because the element cache will never return elements that are not part of the current root view: [KnowsElement#get()](https://github.com/selendroid/selendroid/blob/eb50a4474c248f0610212830a828d2f1d65f1b20/selendroid-server/src/main/java/io/selendroid/server/model/KnownElements.java#L48). That means selendroid should also never have to search in those views?

These questions came to mind while working on #799. The proposed patch fixes a case for us where we would look up an element by id, but the element was present in multiple top level views that selendroid ended up searching. The way the search happened before would return the element that was not a child of the current root view, thus failing the following check when retrieving the element from cache when clicking: [KnowsElement#get()](https://github.com/selendroid/selendroid/blob/eb50a4474c248f0610212830a828d2f1d65f1b20/selendroid-server/src/main/java/io/selendroid/server/model/KnownElements.java#L48). Without changing the behavior of selendroid we are not able to make this test pass it seems.

**Comment by aluedeke** [comment]
is this issue fixed in master or not?

**Comment by asm89** [comment]
@aluedeke No, I'm awaiting response from @DominikDary as to why the searching in multiple top level views exists in the first place.

**Comment by aluedeke** [comment]
@asm89 @DominikDary any updates? without having that fixed Selendroid is super unstable

**Comment by DominikDary** [comment]
For me it also looks like that it is unintended.
I added the element cache verification that will never return elements that are not part of the current root view. So therefore I guess it would be the best that selendroid should  never have to search in those views.

**Comment by asm89** [comment]
@DominikDary thanks for responding. I'll create a patch that fixes the behavior then.

**Comment by DominikDary** [comment]
@asm89 thanks!

**Comment by asm89** [comment]
Fixed by https://github.com/selendroid/selendroid/commit/85d3700a16a2fa76c1aa7bc2f0c327d1452d5ac4

**Comment by aluedeke** [comment]
finally thx @asm89
