### ISSUE TITLE
Selendroid Error - The requested application under test is not configured in selendroid server.

### ISSUE THREAD

**Issue by sethsaurabh** [selendroid/selendroid#806]
I have been running a sample test with all the configurations as advised on selendroid.io. However whenever i run the below code, i get the Error 
"The requested application under test is not configured in selendroid server."

public class Selen {
	public static void main(String args[]) throws Exception{
		
		SelendroidCapabilities capa = new SelendroidCapabilities("io.selendroid.androiddriver:0.14.0");
		WebDriver driver = new SelendroidDriver(capa);
	}
}

Can somebody help?

**Comment by operatiay** [comment]
Hi @sethsaurabh.
Make sure the server is running.

Did you follow all the steps as described here: http://selendroid.io/quickStart.html ?

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
