### ISSUE TITLE
Maven failed to create assembly: No such archiver apk.

### ISSUE THREAD

**Issue by vmcano** [selendroid/selendroid#807]
I get this error when using Maven to create an artifact:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:single (make-assembly) on project seleniumNode: Failed to create assembly: Error adding file-set for 'io.selendroid:selendroid-server:apk:0.15.0-SNAPSHOT' to archive: Error adding archived file-set. PlexusIoResourceCollection not found for: d:\Workspaces\Repository\io\selendroid\selendroid-server\0.15.0-SNAPSHOT\selendroid-server-0.15.0-SNAPSHOT.apk: No such archiver: 'apk'. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
I've tried adding the latest android maven plugin as a new dependency, but I get the same error.
This happens with different Selendroid versions. I'm using 0.15.0-SNAPSHOT but the result is the same using 0.14.

**Comment by operatiay** [comment]
which maven version are you using? it works quite well for me with 3.1.1

**Comment by vmcano** [comment]
I was using maven 3.0.3, but I've tried with versions 3.1.1 and 3.2.5 and the result is the same.
I've also updated versions of maven-compiler-plugin and maven-assembly-plugin to the latest release but it didn't work.

**Comment by DominikDary** [comment]
I'm using  3.2.5 and there is everything fine.

Is there maybe an error in your `seleniumNode` project?

**Comment by vmcano** [comment]
I looked for it and I didn't find it. However, if it works for you, I'll continue trying to solve the problem.
Thank you anyway!

**Comment by lukeis** [comment]
sounds like you're not running the maven command from the root of the project?

can you create a gist of your entire output?

**Comment by vmcano** [comment]
Here you have the maven output: https://gist.github.com/vmcano/fd9374ea181a79a339fc

I've also created a gist with the content of the output using the -X option, just in case: https://gist.github.com/vmcano/91dd27290bd405a9bd8e

**Comment by lukeis** [comment]
what is "seleniumNode" ?? This is not selendroid....

**Comment by vmcano** [comment]
seleniumNode is the name of the project. I'm using Selendroid in it.

**Comment by lukeis** [comment]
ok... then you have an issue with your project, and this is not a 'selendroid issue'

**Comment by Marrowbones** [comment]
I had this problem.  Solved it as follows: http://stackoverflow.com/questions/21984047/selendroid-with-maven-no-such-archiver-apk/38641065#38641065
