### ISSUE TITLE
Selendroid seems to find Elements which are stale.

### ISSUE THREAD

**Issue by aluedeke** [selendroid/selendroid#814]
I can currently observe in a lot of my test cases that Selendroid reports way to many StaleElementExceptions. Thus i implemented a retry logic and the result was quite surprising to me. See the following example:

var e1 = find(By.id("a") => returns an element
e1.isDisplayed() => throws StaleElementException
var e1 = find(By.id("a") => returns an element
e1.isDisplayed() => throws StaleElementException
...
and so on

So i am using always the same query and i always get something back, but when i try to access the returned element it is always stale. I also checked the page source and the element was actually never there.

So i tried debugging it by enhancing KnownElements with log statements and figured out that it always run into this code block:
https://github.com/selendroid/selendroid/blob/master/selendroid-server/src/main/java/io/selendroid/server/model/KnownElements.java#L49

After that i just added the isViewChieldOfCurrentRootView with an log statement here (which seems to be called by findElement):
https://github.com/selendroid/selendroid/blob/67491a38a75b1990c4ee70bfbbf9686df82ca7eb/selendroid-server/src/main/java/io/selendroid/server/model/internal/AbstractNativeElementContext.java#L267

and it turned out that AbstractNativeElementContext returns for e.g. findElement an Element which would be always stale when accessing it.

For a client it seems to me impossible to figure out why this happens so Selendroid behavior should be changed from my point of view.

I actually cannot say how it must be changed because i don't understand why searchViews is actually returning the stale element. But if someone could help me to understand i will try to provide a fix.

**Comment by aluedeke** [comment]
@DominikDary any ideas whats going wrong here?

**Comment by lukeis** [comment]
I think this is a duplicate of #800

**Comment by asm89** [comment]
@aluedeke Read #800. I'm pretty sure you're seeing the same issue.

**Comment by aluedeke** [comment]
closing this issues as it is an duplicate of #800
