### ISSUE TITLE
Release Selendroid 0.15.0

### ISSUE THREAD

**Issue by smiklosovic** [selendroid/selendroid#821]
Hi @DominikDary 

what about cutting 0.15? There are few changes improving Cordova support and you are supporting 2.45.0 of Selenium which would be nice to depend on. New release every month would be awesome. You are on the schedule :)

Thanks

**Comment by lukeis** [comment]
I think we may want to add the chromedriver support that Dominik and I started working on... but otherwise yes, i'm in favor of cutting another release soon. (I can also do so)

**Comment by smiklosovic** [comment]
cool! i can wait. thanks
