### ISSUE TITLE
MultiTouchScreen.executeAction() methods should be public

### ISSUE THREAD

**Issue by EvilOverlordX** [selendroid/selendroid#824]
While trying out the multitouch test examples (at http://selendroid.io/gestures.html), I keep getting the following error back from the java compiler:

Error:(159, 37) java: executeAction(io.selendroid.client.MultiTouchAction) has protected access in io.selendroid.client.MultiTouchScreen

This suggests that either the executeAction() methods should be made public, or that the examples need to be fixed.

**Comment by Blackbaud-KyleMartinez** [comment]
@lukeis 
@EvilOverlordX 

I was looking into this issue. And the example in the documentation is incorrect. You need to use TouchActions's perform() method. Looking at the other examples this is the correct way to execute a TouchAction.

TouchAction ta = new TouchActionBuilder().pointerDown(0, 0).pointerMove(x, y).pointerUp().build();
 ta.perform(driver);

I will update the documentation

**Comment by Blackbaud-KyleMartinez** [comment]
@lukeis How do i update the documentation at http://selendroid.io/gestures.html

**Comment by EvilOverlordX** [comment]
Ok.

**Comment by lukeis** [comment]
@Blackbaud-KyleMartinez update this file:
https://github.com/selendroid/selendroid.io/blob/master/gestures.html.haml

and send a PR to the "selendroid.io" repo
