### ISSUE TITLE
Appium is not able to find 2nd element

### ISSUE THREAD

**Issue by irangtester** [selendroid/selendroid#825]
I have been trying to automate login form of my android. When I run program , It runs proper till Username, It enter username and then after some time it says no element found. So it is not able to find my password text box. I have checked that password text box ID is correct.

My code is given below : 

WebDriver driver = null;
				
			    File classpathRoot = new File(System.getProperty("user.dir"));
			    File appDir = new File(classpathRoot, "");
			    File app = new File(appDir, "ThreePaid.apk");
			    DesiredCapabilities capabilities = new DesiredCapabilities();
			    
			    capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
			    capabilities.setCapability("device", "Android Emulator");
			   // capabilities.setSerial("192.168.56.101:5555");
			    capabilities.setCapability("platformName", "Android");
			   
			    capabilities.setCapability("deviceName","vds");
			    capabilities.setCapability("platformVersion", "19");
			    capabilities.setCapability("app-package", "air.iNMyBabyPaid"); //Replace with your app's package
				capabilities.setCapability("app-activity", "com.ripl.earlythree.activities.SplashActivty"); //Replace with app's Activity
				capabilities.setCapability("app", app.getAbsolutePath());
			
				
	driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub/"), capabilities);
				
				driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
				
				
				  WebElement username = driver.findElement(By.id("et_Username"));
				  
				   if(username.isDisplayed())
				 {

				  
				    username.sendKeys("parent");
				    
				 
				 }
				 else
				 {
					 
					 
					 System.out.println("Your username element not found");
					 
					 
				 }
			
				
				
			 WebElement password = driver.findElement(By.id("et_Password"));
				 
				 if(password.isDisplayed())
					 
				 {

				 password.click();
				 password.sendKeys("test123");
				 
				 }
				 else
					 
				 {
					 System.out.println("Your password element not found");
					 
					
				  }

			}
				
			

	}

**Comment by operatiay** [comment]
Hi @irangtester, why don't you ask your question in the appium forum? I don't see anything selendroid specific in your code and your issue says that you're using a different framework for testing.

If you want someone to have a look at what's going wrong with your application, you'd need to reproduce it with pure selendroid.

**Comment by irangtester** [comment]
@operatiay - Yeah sure. I have just posted in appium discussion.
