### ISSUE TITLE
How to interact with a WebView in a WebView in a Cordova app?

### ISSUE THREAD

**Issue by smiklosovic** [selendroid/selendroid#830]
Hi @DominikDary @lukeis ,

I do not know if I hit the same issue which is not currently implemented however I want to ask anyway.

I have Cordova application. I know I have to switch to WEBVIEW in order to interact with it. So I did and it works to my satisfaction.

However, that Cordova application has a button which is a link. When I click on it, what happens is that another web view is shown to me. It is kind of popup window. I can see that it has ID and I can find that element by findElement() method.

What I can not do is the subsequent interaction with elements inside that popup element I got after I clicked on a link which shows it.

I know that this leads to problem "webview in webview" which is not currently supported (afaik) but I want to have this confirmed.

Is there another approach how I could interact with elements in that popped up web view?

Thanks

**Comment by operatiay** [comment]
can you try calling ```driver.getWindowHandles()```? One of them might be the one you need to switch to in order to interact with the popup.

by the way, what cordova version are you using? I'm currently having trouble to switch to WEBVIEW with 4.0.0-dev.

**Comment by smiklosovic** [comment]
@operatiay 

All handles I have are NATIVE_APP and WEBVIEW_0. Initially, I switch to WEBVIEW_0 right after the start and when I interact with the application and I get that popup webview, no new handle via that method aside of these metioned is availabe.

cordova -version gives me 4.3.0.

**Comment by operatiay** [comment]
It might help to fetch the view hierarchy via eclipse DDMS.
could it be an iframe issue?

can you check the cordova-android version?

**Comment by smiklosovic** [comment]
@operatiay @DominikDary @lukeis 

yeah! so it works :D I have to do a little bit magic

So,

driver.switchTo().window("WEBVIEW_0"); // this switch me to web view

button.click(); // this effectively pops up another web view

driver.switchTo().window("NATIVE_APP"); // I have to switch back to native app to get handle of that popup

WebElement webOauth = driver.findElement(By.id("web_oauth"));

driver.switchTo().window("WEBVIEW_0"); // then I have to switch to web view again

// and here I get email field which is in that popup window and I can pass a string to it!

WebElement email = driver.findElement(By.name("email"));

**Comment by smiklosovic** [comment]
But one more thing which fails is this, after that popup is closed, I expect some another popup to show me some notice about the result.

I do not know if this is selendroid's fault or cordova?

I/SELENDROID(16992): io.selendroid.server.model.SelendroidWebDriver$ExtendedCordovaChromeClient#onJsAlert:518 - new alert message: Upload complete
W/System.err(16992): java.lang.NullPointerException
W/System.err(16992): 	at org.apache.cordova.CordovaChromeClient.onJsAlert(CordovaChromeClient.java:97)
W/System.err(16992): 	at io.selendroid.server.model.SelendroidWebDriver$ExtendedCordovaChromeClient.onJsAlert(SelendroidWebDriver.java:519)
W/System.err(16992): 	at com.android.webview.chromium.WebViewContentsClientAdapter.handleJsAlert(WebViewContentsClientAdapter.java:612)
W/System.err(16992): 	at com.android.org.chromium.android_webview.AwContentsClientBridge.handleJsAlert(AwContentsClientBridge.java:72)
W/System.err(16992): 	at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err(16992): 	at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
W/System.err(16992): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(16992): 	at android.os.Looper.loop(Looper.java:136)
W/System.err(16992): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
W/System.err(16992): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(16992): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(16992): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
W/System.err(16992): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
W/System.err(16992): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by smiklosovic** [comment]
@operatiay 

I am using 

platform add android@3.6.4

I can not use 4.0 for various reasons.

**Comment by smiklosovic** [comment]
So, this is called in Selendroid

https://github.com/selendroid/selendroid/blob/master/selendroid-server/src/main/java/io/selendroid/server/model/SelendroidWebDriver.java#L519

and then it propagates to this

https://github.com/Wizcorp/phonegap-plugin-wizViewManager/blob/master/platforms/android/CordovaLib/src/org/apache/cordova/CordovaChromeClient.java#L97

and it seems to me that the only place it can get NPE is on that "this.cordova.getActivity()" and it kind of calls that recursively ... 

any hints here?

**Comment by smiklosovic** [comment]
I was also trying this but it does not work either.

// this switches me to Cordova web view
driver.switchTo().window("WEBVIEW_0");

// this effectively pops up another web view
button.click();

// i tried to load web view again, I was thinking to kind of "refresh" it
driver.switchTo().window("WEBVIEW_0");

// but no, it fails to find that element in embedded web view
WebElement email = driver.findElement(By.name("email"));

**Comment by smiklosovic** [comment]
@operatiay 

the reason it does not work in 4.0 of cordova-android is that CordovaChromeClient is not there. It seems it is only in 3.x releases and it was rewritten in 4.x. As of now, Selendroid uses Cordova Android of that 3.x release stream.

**Comment by DominikDary** [comment]
can you have a look at the merge we recently did https://github.com/selendroid/selendroid/pull/859 ?

**Comment by DominikDary** [comment]
closing this for now, please reopen or create a new bug if the mentioned PR does not fix your problem.
