### ISSUE TITLE
How to automate pull to refresh option in apk with Selendroid

### ISSUE THREAD

**Issue by fayizkc** [selendroid/selendroid#831]
Is there any option to swipe on the screen without using a webelement in Selendroid. With Appium we can do driver.swipe (x1, y1,x2,y2);  but I did not see any similar method in Selendroid and also JavaScript swipe also will not support for native app in Selendroid. So is it possible to inplemetn swipt method based on xy coordinate or any other workaround for the same.

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
