### ISSUE TITLE
can't get text of a web element in webview in selendroid test app

### ISSUE THREAD

**Issue by jlipps** [selendroid/selendroid#832]
I have a simple script that uses the selendroid test app's webview. It enters some text in the box, clicks the submit button, and then tries to get the text from the h1 tag (which has the content "This is my way of saying hello"). I can get the h1 element, and I can get its text, but it always says it is the empty string. If I print the source of the webview before getting the text of the element, the source shows the h1 tag with the content as expected. So it's not a timing issue.

any ideas what could be going on? Could this be a more widespread issue?

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
