### ISSUE TITLE
Unable to run the apk files (downloaded online example: facebook,gmail) using emulator 

### ISSUE THREAD

**Issue by bradzy** [selendroid/selendroid#834]
Hello,

As I am very new to selendroid, I want to run an .apk file in the emulator and locate the elements and below is the problem which I am facing

> Able to see the installed application icon in the emulator but unable to run it. when manually clicking on the icon in the emulator its not opening and crashing.
> Followed the solution provided in the link [https://github.com/selendroid/selendroid/issues/483] but its not working
> Is it possible to run and locate the elements of the .apk files (downloaded from internet) through selendroid in the emulator

Below is the code which I am using

Code:
import io.selendroid.SelendroidDriver;
import io.selendroid.common.SelendroidCapabilities;
import io.selendroid.common.device.DeviceTargetPlatform;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.Test;

public class Gmail {

	private WebDriver driver;
	@Test
	public void test() throws Exception{
		SelendroidCapabilities capa = new SelendroidCapabilities("com.google.android.gm:4.8 (1167183)");
		driver = new SelendroidDriver(capa); 
		
		capa.setPlatformVersion(DeviceTargetPlatform.ANDROID21);
        capa.setEmulator(true);
        
		System.out.println("Testing Gmail --");
		
		Thread.sleep(50000);
		
	}
	
	@AfterTest
	public void close() {
		driver.quit();
	}
		
}

Error Log:

FAILED CONFIGURATION: @AfterTest close
java.lang.NullPointerException

FAILED: test
org.openqa.selenium.SessionNotCreatedException: Error starting Selendroid session

Console:
Can't connect to selendroid server, assuming it is not working

Thanks in advance ..

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by bradzy** [comment]
Thanks for the info
