### ISSUE TITLE
Selendroid and Gradle

### ISSUE THREAD

**Issue by kul3r4** [selendroid/selendroid#837]
Hi,
I am trying to run Selendroid Acceptance tests from a gradle project in Intellij on a MacOS.

Even if I setup the android home (I can do echo $ANDROID_HOME and the output is correct), I get "Environment variable 'ANDROID_HOME' was not found!".

Is there anything I can setup or pass directly to Selendroid when I run tests so that the ANDROID_HOME get set?

Thanks

**Comment by operatiay** [comment]
This seems to be a gradle IntelliJ configuration issue. Add the ANDROID_HOME variable there and it should work.

**Comment by kul3r4** [comment]
Can you tell me exactly where I could add the ANDROID_HOME in Intellij?

**Comment by lukeis** [comment]
http://lmgtfy.com/?q=how+to+set+environment+variable+in+intellij

**Comment by kul3r4** [comment]
Thanks for googling that for me.
There is no Environment setting in the run/debug configuration in gradle.

**Comment by kul3r4** [comment]
I solved the problem, maybe can be of any help to someone.
Instead of creating a gradle run configuration, you can create a groovy run configuration. A groovy run configuration gives you the chance to setup an Environment Variable and in this way you can pass the ANDROID_HOME required by Selendroid. This solved the problem.
