### ISSUE TITLE
Selendroid doesn't recognize android hardware devices

### ISSUE THREAD

**Issue by Doena** [selendroid/selendroid#839]
Hi,

I've tried to follow the setup instructions but after startup of the server it doesn't recognize my android phones:

INFORMATION: No emulators have been found.
... or plugin an Android Hardware Device via USB.

Output at http://localhost:4444/wd/hub/status:
{"value":{"os":{"name":"Windows 8.1","arch":"amd64","version":"6.3"},"build":{"browserName":"selendroid","version":"0.15.0"},"supportedDevices":[],"supportedApps":[{"mainActivity":"io.selendroid.androiddriver.WebViewActivity","appId":"io.selendroid.androiddriver:0.15.0","basePackage":"io.selendroid.androiddriver"}]},"status":0}

The device has been plugged in before the server was started. 

Model: HTC One mini. 
Android-Version: 4.4.2
OS: Windows 8

Best regards.

**Comment by operatiay** [comment]
make sure you can see those devices via ```adb devices``` command

**Comment by Doena** [comment]
That was a good hint: For htc one mini there were drivers missing. Now it
is recognized.

The Galaxy S though will not execute any mobile web tests. Is selendroid
not supporting old (froyo) android versions?

2015-03-23 18:16 GMT+01:00 operatiay <notifications@github.com>:

**Comment by DominikDary** [comment]
No, we support versions starting from gingerbread.
