### ISSUE TITLE
scrollToUIElement

### ISSUE THREAD

**Issue by pootyx** [selendroid/selendroid#842]
Hi,
I used to use Calabash, but I switch to Selendroid. Now I have to refactor all of my code, and I am searching for similar methods, like
waitForUIElement (Calabash) vs. WaitForElement (Selendroid)

I have used scrollToUIElement a lot, which is good for scrolling until the given element is displayed. Do you have any guess, how can I change this method? As I see in Selendroid there isn't anything like this, what I need is a method that scrolls until an element isn't displayed. I don't know the exact position of this element, so I cannot use flick.

What I thought is an algorithm which creates a list, and a for cycle goes through this list and search the element what I need, if it cannot find this, than scroll down and start it over and over. But it is slow and contains tons of unnecessary code.

I have a second problem also, please read it below.

In Calabash I can locate an element like this:
The location:
ERROR_MSG_TEXTVIEW(By.xpath("//TextView");
This line is stored in an enum, like all the other elements, 

The controller:
scrollToUIElement(android, ElementsClass.ERROR_MSG_TEXTVIEW.getQuery("any string"));
it looks like this in Selendroid:
WaitForElement (driver,  ElementsClass.ERROR_MSG_TEXTVIEW.getBy());

The Selendroid methot select the first TextView in order.
The first one select the TextView which contains the "any string" string

What I like to ask, is as you can see I can give the element any string and if there are more than 1 matching elements than it will select the one that contains the given text. For example, there is a list that contains 30 elements, all with the same id, so that when I search for this id I'm gonna get 30 elements, but if I use the Calabash method I can type there the text what I want to be selected. I can store the texts in a different class and modify them easily. Do you know how can I locate an element, by text, but the location does not contain the text.

**Comment by DominikDary** [comment]
You don't have to scroll to an element to interact with it. For Waiting until a specific element is displayed you can use those [waiters](https://github.com/selendroid/selendroid/tree/master/selendroid-client/src/main/java/io/selendroid/client/waiter).

If you would like to wait e.g. until a new activity is displayed, you find an example here:
https://github.com/selendroid/demoproject-selendroid/blob/master/src/main/java/io/selendroid/demo/nativeui/UserRegistrationTest.java#L70

The other thing you asked if how to find an element by text:
https://github.com/selendroid/demoproject-selendroid/blob/master/src/main/java/io/selendroid/demo/nativeui/UserRegistrationTest.java#L65

All this examples can be verified with the selendroid-test-app.

Please reopen if you have additional questions.
