### ISSUE TITLE
Can't connect to Selendroid Server, assume it is not working 

### ISSUE THREAD

**Issue by bchand1748** [selendroid/selendroid#843]
I am not sure Why I am getting this error. I have ran the server in CMD using java -jar selendroid-standalone-0.15.0-with-dependencies.jar -aut io.selendroid.testapp_0.15.0.apk

Java Code: 
SelendroidCapabilities capa = new SelendroidCapabilities("io.selendroid.testapp:0.15.0");

		WebDriver driver = new SelendroidDriver(capa);
		WebElement inputField = driver.findElement(By.id("my_text_field"));
		inputField.getTagName();
		}

Log : 

-->
/storage/emulated/legacy
<--
Mar 25, 2015 11:25:29 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\bkbc011\AppData\Local\Android\sdk\platfo
rm-tools\adb.exe -s 0506931ad84a9331 shell ls C:\storage\emulated\legacy/
Mar 25, 2015 11:25:30 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
C:\storage\emulated\legacy/: No such file or directory
<--
Mar 25, 2015 11:25:30 AM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Checking if the Selendroid server is running: http://localhost:8085/wd/hub
/status
Mar 25, 2015 11:25:30 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8085: Connection reset
Mar 25, 2015 11:25:30 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8085
Mar 25, 2015 11:25:30 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8085: Connection reset
Mar 25, 2015 11:25:30 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8085
Mar 25, 2015 11:25:30 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8085: Connection reset
Mar 25, 2015 11:25:30 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8085
Mar 25, 2015 11:25:30 AM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Can't connect to Selendroid server, assuming it is not running.
Mar 25, 2015 11:25:32 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\bkbc011\AppData\Local\Android\sdk\platfo
rm-tools\adb.exe -s 0506931ad84a9331 shell echo $EXTERNAL_STORAGE
Mar 25, 2015 11:25:32 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
/storage/emulated/legacy
<--
Mar 25, 2015 11:25:32 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\bkbc011\AppData\Local\Android\sdk\platfo
rm-tools\adb.exe -s 0506931ad84a9331 shell ls C:\storage\emulated\legacy/
Mar 25, 2015 11:25:32 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
C:\storage\emulated\legacy/: No such file or directory
<--
Mar 25, 2015 11:25:32 AM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Checking if the Selendroid server is running: http://localhost:8085/wd/hub
/status
Mar 25, 2015 11:25:32 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8085: Connection reset
Mar 25, 2015 11:25:32 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8085
Mar 25, 2015 11:25:32 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8085: Connection reset
Mar 25, 2015 11:25:32 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8085
Mar 25, 2015 11:25:32 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8085: Connection reset
Mar 25, 2015 11:25:32 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8085
Mar 25, 2015 11:25:32 AM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Can't connect to Selendroid server, assuming it is not running.
Mar 25, 2015 11:25:34 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\bkbc011\AppData\Local\Android\sdk\platfo
rm-tools\adb.exe -s 0506931ad84a9331 shell echo $EXTERNAL_STORAGE
Mar 25, 2015 11:25:34 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
/storage/emulated/legacy
<--
Mar 25, 2015 11:25:34 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\bkbc011\AppData\Local\Android\sdk\platfo
rm-tools\adb.exe -s 0506931ad84a9331 shell ls C:\storage\emulated\legacy/
Mar 25, 2015 11:25:34 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
C:\storage\emulated\legacy/: No such file or directory
<--
Mar 25, 2015 11:25:34 AM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Checking if the Selendroid server is running: http://localhost:8085/wd/hub
/status
Mar 25, 2015 11:25:34 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8085: Connection reset
Mar 25, 2015 11:25:34 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8085
Mar 25, 2015 11:25:34 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8085: Connection reset
Mar 25, 2015 11:25:34 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8085
Mar 25, 2015 11:25:34 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8085: Connection reset
Mar 25, 2015 11:25:34 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8085
Mar 25, 2015 11:25:34 AM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Can't connect to Selendroid server, assuming it is not running.
Mar 25, 2015 11:25:36 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\bkbc011\AppData\Local\Android\sdk\platfo
rm-tools\adb.exe -s 0506931ad84a9331 shell echo $EXTERNAL_STORAGE
Mar 25, 2015 11:25:36 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
/storage/emulated/legacy
<--
Mar 25, 2015 11:25:36 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\bkbc011\AppData\Local\Android\sdk\platfo
rm-tools\adb.exe -s 0506931ad84a9331 shell ls C:\storage\emulated\legacy/
Mar 25, 2015 11:25:36 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
C:\storage\emulated\legacy/: No such file or directory
<--
Mar 25, 2015 11:25:36 AM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Checking if the Selendroid server is running: http://localhost:8085/wd/hub
/status
Mar 25, 2015 11:25:36 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8085: Connection reset
Mar 25, 2015 11:25:36 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8085
Mar 25, 2015 11:25:36 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8085: Connection reset
Mar 25, 2015 11:25:36 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8085
Mar 25, 2015 11:25:36 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8085: Connection reset
Mar 25, 2015 11:25:36 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8085
Mar 25, 2015 11:25:36 AM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Can't connect to Selendroid server, assuming it is not running.
Mar 25, 2015 11:25:36 AM io.selendroid.standalone.server.model.SelendroidStandal
oneDriver createNewTestSession
SEVERE: Error occurred while starting Selendroid session
io.selendroid.server.common.exceptions.SelendroidException: Selendroid server on
 the device didn't come up after 20sec:
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.wait
ForServerStart(SelendroidStandaloneDriver.java:341)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.crea
teNewTestSession(SelendroidStandaloneDriver.java:265)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.crea
teNewTestSession(SelendroidStandaloneDriver.java:210)
        at io.selendroid.standalone.server.handler.CreateSessionHandler.handleRe
quest(CreateSessionHandler.java:40)
        at io.selendroid.standalone.server.BaseSelendroidStandaloneHandler.handl
e(BaseSelendroidStandaloneHandler.java:45)
        at io.selendroid.standalone.server.SelendroidServlet.handleRequest(Selen
droidServlet.java:131)
        at io.selendroid.server.common.BaseServlet.handleHttpRequest(BaseServlet
.java:67)
        at io.selendroid.server.common.http.ServerHandler.channelRead(ServerHand
ler.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:319)
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(Ab
stractTrafficShapingHandler.java:223)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:319)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToM
essageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:163)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedCha
nnelDuplexHandler.java:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.ja
va:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Unknown Source)

Mar 25, 2015 11:25:36 AM io.selendroid.standalone.server.model.DeviceStore relea
se
INFO: Releasing device HardwareDevice [serial=0506931ad84a9331, model=Nexus 4, t
argetVersion=ANDROID21]
Mar 25, 2015 11:25:36 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\bkbc011\AppData\Local\Android\sdk\platfo
rm-tools\adb.exe -s 0506931ad84a9331 shell am force-stop io.selendroid.testapp
Mar 25, 2015 11:25:37 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Mar 25, 2015 11:25:37 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\bkbc011\AppData\Local\Android\sdk\platfo
rm-tools\adb.exe -s 0506931ad84a9331 forward --remove tcp:8085
Mar 25, 2015 11:25:37 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Mar 25, 2015 11:25:37 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\bkbc011\AppData\Local\Android\sdk\platfo
rm-tools\adb.exe -s 0506931ad84a9331 shell pm clear io.selendroid.testapp
Mar 25, 2015 11:25:38 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
Success
<--
Mar 25, 2015 11:25:38 AM io.selendroid.standalone.server.handler.CreateSessionHa
ndler handleRequest
SEVERE: Error while creating new session
io.selendroid.server.common.exceptions.SelendroidException: Selendroid server on
 the device didn't come up after 20sec:
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.wait
ForServerStart(SelendroidStandaloneDriver.java:341)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.crea
teNewTestSession(SelendroidStandaloneDriver.java:265)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.crea
teNewTestSession(SelendroidStandaloneDriver.java:210)
        at io.selendroid.standalone.server.handler.CreateSessionHandler.handleRe
quest(CreateSessionHandler.java:40)
        at io.selendroid.standalone.server.BaseSelendroidStandaloneHandler.handl
e(BaseSelendroidStandaloneHandler.java:45)
        at io.selendroid.standalone.server.SelendroidServlet.handleRequest(Selen
droidServlet.java:131)
        at io.selendroid.server.common.BaseServlet.handleHttpRequest(BaseServlet
.java:67)
        at io.selendroid.server.common.http.ServerHandler.channelRead(ServerHand
ler.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:319)
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(Ab
stractTrafficShapingHandler.java:223)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:319)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToM
essageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:163)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedCha
nnelDuplexHandler.java:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.ja
va:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Unknown Source)

**Comment by ravindra5557** [comment]
i am also facing same issue, can some one provide solution for this issue?

**Comment by metasonic** [comment]
You can build a custom version of selendroid,  using an old selenium
distribution.  That's the only thing that worked for.me

**Comment by ravindra5557** [comment]
Hi,
Thanks for reply,
i am using below version selendroid , 

selendroid-standalone-0.17.0-with-dependencies
selendroid-test-app-0.17.0.apk 
i am using Samsung Tab 7 inches and after executing this command 
 java -jar selendroid-standalone-0.17.0-with-dependencies.jar -app selendroid-test-app-0.17.0.apk and i am getting resigned-selendroid-test-app-0.17.0.apk.

i trying to launch app in my samsung tab and its showing error still Can't connect to Selendroid Server, assume it is not working .

please correct me if any thing wrong in configuration 

@metasonic , can you please provide clear steps setting the old distribution.

**Comment by ravindra5557** [comment]
@metasonic, which old selenium distribution you have used , can you please provide this information?

**Comment by metasonic** [comment]
So, what I did was:
1- Download the latest selendroid source code
2- Open pom.xml and chance selenium version to <selenium.version>2.45.0</selenium.version> (this is the version used in 0.15
3- Build selendroid (gradle clean build) or you can try to build it with maven following the steps here (http://selendroid.io/architecture.html)

Issues caused by doing this:
If you have a framework similar to mine, where both selenium and selendroid are part of the project you will not be able to run web tests using the latest selenium build and firefox 45, instead you need to use the same selenium version which works with firefox 35, hope this helps
