### ISSUE TITLE
Looking to add to the github wiki.

### ISSUE THREAD

**Issue by colindmurray** [selendroid/selendroid#845]
I decided to put together some guides for my own sake on debugging selendroid.  Mainly selendroid-standalone and selendroid-server.  I thought perhaps this info should be on the wiki, since I can't edit it however I opted to clone it and make the modifications in my own fork selendroid wiki here https://github.com/colindmurray/selendroid/wiki/Debugging

Unfortunately, [you cannot pull request wiki pages](http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github), so a maintainer would have to manually merge in my changes like so:
```
git clone https://github.com/selendroid/selendroid.wiki.git
cd selendroid.wiki
git remote add colindmurray https://github.com/colindmurray/selendroid.wiki.git
git pull colindmurray master
git push origin master
```

Any feedback would be appreciated also, I'd be happy to clean it up or extend upon it.

**Comment by DominikDary** [comment]
hi @colindmurray 
that would be fine for me. the other thing: just create a github gist and then i will copy it over.

**Comment by colindmurray** [comment]
Here it is in a gist: https://gist.github.com/colindmurray/ab5d738991408f91bb59

**Comment by DominikDary** [comment]
Awesome,  thanks!  Will add it probably tomorrow.

**Comment by DominikDary** [comment]
Done!

https://github.com/selendroid/selendroid/wiki/Debugging-Selendroid-standalone-Server/_history

Are you fine how I added your contribution or should I also add your name?

**Comment by colindmurray** [comment]
Seems fine to me.  Thanks!

**Comment by DominikDary** [comment]
Welcome and thanks for your contribution!
