### ISSUE TITLE
How to locate the elements when we are doing mobile web testing?

### ISSUE THREAD

**Issue by bradzy** [selendroid/selendroid#847]
Hello,

I am successfully able to do mobile web testing and able to launch the site in the connected device 

I would like to do more test with the Testing the mobile web so how to locate an element when we are able to see the mobile web app in the inspector 

please can you provide me with some details of how to locate elements when we test the mobile web

Thanks in advance...

**Comment by operatiay** [comment]
In general it should be something like this: http://docs.seleniumhq.org/docs/appendix_locating_techniques.jsp
In other words you can use a number of finders/locators to get the element you need (e.g. id, name, text, partial link text, xPath, CSS selector).

By the way, your question is not related to selendroid.

**Comment by bradzy** [comment]
Hello operatiay,

Thanks for the reply..

I have done the Testing the Mobile Web and below is the code:

package io.selendroid.demo.mobileweb;

import io.selendroid.SelendroidCapabilities;
import io.selendroid.SelendroidConfiguration;
import io.selendroid.SelendroidDriver;
import io.selendroid.SelendroidLauncher;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;

public class MobileWebTest {
  private SelendroidLauncher selendroidServer = null;
  private WebDriver driver = null;

  @Test
  public void shouldSearchWithEbay() {
    // And now use this to visit ebay
    driver.get("http://m.ebay.de");

    // Find the text input element by its id
    WebElement element = driver.findElement(By.id("kw"));

    // Enter something to search for
    element.sendKeys("Nexus 5");

    // Now submit the form. WebDriver will find the form for us from the element
    element.submit();

    // Check the title of the page
    System.out.println("Page title is: " + driver.getTitle());
    driver.quit();
  }

  @Before
  public void startSelendroidServer() throws Exception {
    if (selendroidServer != null) {
      selendroidServer.stopSelendroid();
    }
    SelendroidConfiguration config = new SelendroidConfiguration();

    selendroidServer = new SelendroidLauncher(config);
    selendroidServer.lauchSelendroid();

    DesiredCapabilities caps = SelendroidCapabilities.android();

    driver = new SelendroidDriver(caps);
  }

  @After
  public void stopSelendroidServer() {
    if (driver != null) {
      driver.quit();
    }
    if (selendroidServer != null) {
      selendroidServer.stopSelendroid();
    }
  }
}

Once the server is started I am able to see the app in the device attached to the PC and also in the link [http://localhost:4444/inspector/]

Now if you see in the above code we are able to find the text box by its id and passing the values Nexus 5 in the below lines
WebElement element = driver.findElement(By.id("kw"));
element.sendKeys("Nexus 5");

As much I am aware that the only way selendroid allows us to find the elements through its inbuilt tool Inspector then if someone wants to locate other elements through Inspector then what is the ways.I can able to see the complete HTML source code by locking the tree structure displays in the Inspector link

Thanks !

**Comment by operatiay** [comment]
Sorry, I don't have time right now to run your scenario, but you might have a problem with the context (native vs. web).

A completely separate point is the following: Selendroid inspector doesn't work on web content. You'd need to write your selectors using other tools. you can open the website in a browser on your desktop and do the investigations what works for you.

**Comment by bhumireddy100** [comment]
Hello Operatiay,

Could you please provide info for the following queries.

1. Selendroid does support running test scripts on Opera browser on Mobile device.
2. what are the mobile browsers supports Selendroid.
3. Is there any mobile automation tool available in market for mobile web app testing (running test scripts) on mobile opera browser(Mobile Device).

Thanks in advance.

Regards,
Venkat
