### ISSUE TITLE
Install multiple APKs with selendroid

### ISSUE THREAD

**Issue by axelbarfod** [selendroid/selendroid#851]
Is it possible to install multiple APKS with seledroid? 
Here is the thing i have, and apk which inside has another apk inside but when i install the first apk, how can I get to install the second apk with the same certificate? Is it posible to handle multiple apks with selendroid ?

**Comment by DominikDary** [comment]
Hi @axelbarfod ,

you can specifiy mutiple apps and selendroid can use those apps each for a test session on another device. But you cannot use two APKs in the same test.
