### ISSUE TITLE
Click outside an instrumented app using selendroid

### ISSUE THREAD

**Issue by mayurdharmadhikari** [selendroid/selendroid#854]
Hi Friends,

Is there any way,so I can click outside of an instrumented app scope.
For e.g while executing a test on native app,I have to go in android device settings and turn on wi-fi or go to sound settings and click on certain text on it.

**Comment by lukeis** [comment]
you can try to use the AdbCommand interface and issue taps or button presses. Be sure to not kill your running app / instrumentation process, or selendroid would need to be 'restarted'.

    driver.getAdbConnection().<tap or executeShellCommand>

**Comment by ayosuva** [comment]
@lukeis how to apply tap command in android 2.3.7 device?
