### ISSUE TITLE
Selendroid Mobile View: When running script - map is not loaded for my mobile web site, as it requires to enable location access.

### ISSUE THREAD

**Issue by Nishant-Taksande** [selendroid/selendroid#856]
I am working on mobile web site which has the following feature:
   - A page with map widget with address edit.
   - Enter post code/address in the edit and the location is searched and selected.

I am trying to automate the above scenario.

1. When i open my mobile web app on firefox/chrome browser on mobile device, i get a popup "do you want to share your location with 'www.myweb.com' " - after accepting this popup the map is loaded and i am able to search the locations using address(refer screenshot for firefox browser on mobile samsung galaxy note 3)

2. I have created a script using selendroid, but the selendroid mobile view app doesn't show any pop-up, map is also not loaded.

It seems the location is not by default shared with the selendroid web view app, Kindly let me know if there is a way to achieve this.

Best Regards,
Nishant Taksande

 
![firefoxpopup](https://cloud.githubusercontent.com/assets/7511343/7273398/00d11a10-e911-11e4-98b6-2df2c4d253e7.png)

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
