### ISSUE TITLE
jarsigner: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by pinek6** [selendroid/selendroid#858]
I am trying to setup test environment. Everything works for me completely fine for selendroid-test-app-0.15.0.apk, so the environment is correctly setup is gues. But have a problem with an app which I would like to test. First I was trying to google it, but no luck.

actions:
a) server correctly started, and visible on http://localhost:4444/wd/hub/status
b) when executing test(just start application) getting errors in console:

java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{XXXXX/io.selendroid.server.ServerInstr
umentation} from pid=4965, uid=4965 not allowed because package XXXXXXX does not have a signature matching the target XXXXX
        at android.os.Parcel.readException(Parcel.java:1425)
        at android.os.Parcel.readException(Parcel.java:1379)
        at android.app.ActivityManagerProxy.startInstrumentation(ActivityManagerNative.java:2871)
        at com.android.commands.am.Am.runInstrument(Am.java:680)
        at com.android.commands.am.Am.run(Am.java:119)
        at com.android.commands.am.Am.main(Am.java:82)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:235)
        at dalvik.system.NativeStart.main(Native Method)

from logcat:
W/ActivityManager(  440): Permission Denial: starting instrumentation ComponentInfo{io.selendroid.XXXXXX/io.selendroid.server.ServerInstrumentation} from pid=4965, uid=4965 not allowed because package XXXX does not have a signature matching the target XXXX

Test is failing!

c) then I have done below check on " resigned-myApp.apk* "(created when starting server) file in my working directory

command: jarsigner -verify -verbose -certs "resigned-myApp.apk"
output: jarsigner: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

Before resign(starting server) this output from above command was: "jar verified."

I am using: selendroid-standalone-0.15.0-with-dependencies.jar

Could you help me please to solve this issue? Can give more info if needed. 

Thanks in advance.

**Comment by DominikDary** [comment]
That sounds like the selendroid-server you are using was not signed (created) for the dedicated app under test.
I would try to run the selendroid-standalone with the flag `-forceReinstall`. This created a new selendroid-server and pushes it to the devices even if there is already a server existent.

Please reopen if this is not solving your issue.
