### ISSUE TITLE
TOAST validation

### ISSUE THREAD

**Issue by joaoclineu** [selendroid/selendroid#86]
It is possible to do validation TOAST with Selendroid ?

**Comment by asm89** [comment]
We have a working e2e test covering this. https://github.com/selendroid/selendroid/blob/85b1f6dc95e41c721261e5b969bbd6a95cfe12a5/selendroid-test-app/src/test/java/io/selendroid/nativetests/WaitForProgressBarGoneAwayTest.java#L87-L93
