### ISSUE TITLE
Server Instrumentation error with Selendroid 0.12

### ISSUE THREAD

**Issue by SK-23** [selendroid/selendroid#863]
When using selendroid dependencies jar 0.12, encountering "Crash of app com.newshunt running instrumentation ComponentInfo{io.selendroid.com.nh/io.selendroid.ServerInstrumentation" in the adb logcat. 

Ran : D:\Android\sdk\platform-tools>adb shell am instrument -e main_activity com.nh io.selendroid/.ServerInstrumentation. 

Returned: 
android.util.AndroidException: INSTRUMENTATION_FAILED: io.selendroid/io.selendroid.ServerInstrumentation
        at com.android.commands.am.Am.runInstrument(Am.java:676)
        at com.android.commands.am.Am.run(Am.java:119)
        at com.android.commands.am.Am.main(Am.java:82)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:235)
        at dalvik.system.NativeStart.main(Native Method)

Not seeing this issue with Selendroid 0.15. Why is this issue seen in 0.12? Can this be fixed without upgrading?

**Comment by lukeis** [comment]
You're likely encountering a bug that was fixed in between the releases. No, there isn't a fix without upgrading. 

Any reason you can't upgrade?

(Closing this since it's not an issue with the current release)

**Comment by SK-23** [comment]
Thanks lukeis for your response. Cannot upgrade coz of Appium (has selendroid v0.12 even in the latest). 
- Have been using Appium 1.3.4 (Selendroid 0.12), with no issues past couple of months.
- With the latest application apk, started encountering "could not bring up server in 20 seconds error"
- Was recommended to upgrade. With latest appium upgrade(1.3.7 - still with Selendroid 0.12), the 20 sec error went away, but the instrumentation error is being seen. 

Wanted to check if this issue seen in Selendroid 0.12 standalone as well. As mentioned above, its indeed reproducible in selendroid. Since this had been working fine with old apk, I was hoping something can be done to resolve this error for the new one. 

Note: I have looked at other posts and tried cleaning up the emulator and starting fresh. No luck. Still encountering this instrumentation error.

**Comment by lukeis** [comment]
Have you logged a bug with appium?

**Comment by SK-23** [comment]
There seems to be an issue already open: https://github.com/appium/appium/issues/4617. Have commented on that issue, yet to get a response. 
When do we get this kind of error in selendroid?
