### ISSUE TITLE
the getCenterCoordinate function throws NumberFormationException for some Nexus devices

### ISSUE THREAD

**Issue by roseknight** [selendroid/selendroid#865]
I found that my Nexus devices (Nexus 5 + Android 5.1 and Nexus 9 + Android 5.0) return the element size string (width and height) with double numbers instead of integer numbers. 

As a result, the getCenterCoordinate function in https://github.com/selendroid/selendroid/blob/master/selendroid-server/src/main/java/io/selendroid/server/model/AndroidWebElement.java#L233 will throw NumberFormatException when doing Integer.parseInt. 

This problem does not happen to Galaxy S3 + 4.0 and Moto G + 4.3. 
I have to apply the following patch to bypass this issue. 

-    return new Point(topLeft.x + Integer.parseInt(result[0]) / 2, topLeft.y
-        + Integer.parseInt(result[1]) / 2);
+    int xSize = (new Double(result[0])).intValue();
+    int ySize = (new Double(result[1])).intValue();
+    return new Point(topLeft.x + xSize / 2, topLeft.y+ ySize / 2);
   }

It is a safety net trick. Do you think it is worthwhile for a pull request?

Thanks
Jun

**Comment by DominikDary** [comment]
Of course!

**Comment by CStefania** [comment]
I had the same issue and solved it in a similar way.
Did you make the pull request? I was about to do one myself on this topic.

**Comment by CStefania** [comment]
Thank you very much! :)
