### ISSUE TITLE
waitForPageLoad function may throw Timeout Exception in a wrong way

### ISSUE THREAD

**Issue by roseknight** [selendroid/selendroid#866]
I got a problem when using click for a web element in the webview of my hybrid app. The web element is a text field. I like to send keys to it. However, when the script runs element.click, Selendroid throws a Timeout exception. 

After reviewing the commits and code, I found it is related to the following commit:
https://github.com/selendroid/selendroid/commit/9b0e0115ae0ae3b2b867e74b0466892eb1878649#diff-c6ab3b7e945144463081470c1a95aeed

-      long end = System.currentTimeMillis() + LOADING_TIMEOUT;
+      long end = System.currentTimeMillis() + pageLoadTimeout;
       while (!pageDoneLoading && pageStartedLoading && (System.currentTimeMillis() < end)) {
         try {
-          syncObject.wait(LOADING_TIMEOUT);
+          syncObject.wait(POLLING_INTERVAL);
         } catch (InterruptedException e) {
           throw new RuntimeException(e);
         }
       }
+      if (!pageDoneLoading) {
+        throw new TimeoutException(String.format("Timed out after %d seconds",
+          SECONDS.convert(pageLoadTimeout, MILLISECONDS)));
+      }
     }
   }

The last part checks whether pageDoneLoading is false or not. The element click always resets the page load status and calls waitForPageLoad(). 

However, if the click does not actually cause a pageLoad event (for example, click a text field to type), the pageDoneLoading and pageStartedLoading could all be false. then, this throw exception block will be triggered even though nothing is wrong. 

I did not read the way to set pageDoneLoading and pageStartedLoading. I could be wrong. However, after I comment out this block, my script just works. 

What is your thought? A bug or not?

**Comment by lukeis** [comment]
yes, seems like a bug :) hopefully corrected with that commit.
