### ISSUE TITLE
Current selendroid-standalone-0.15.0-with-dependencies.jar is corrupt

### ISSUE THREAD

**Issue by ObjectiveTruth** [selendroid/selendroid#869]
Hitting my head against the wall for a few hours to resolve this, and it seems that it is indeed corrupt.

Downloading version 0.140 from Maven works fine

Environment: 
Mac OSX Yosemite 10.10.3
Java: 1.8

Kept giving me this when running `java selendroid-standalone-0.15.0-with-dependencies.jar` as per the documentation.

`Error: Could not find or load main class selendroid-standalone-0.15.0-with-dependencies.jar`

Download 0.14.0 from Maven [here](http://search.maven.org/remotecontent?filepath=io/selendroid/selendroid-standalone/0.14.0/selendroid-standalone-0.14.0-with-dependencies.jar)

**Comment by lukeis** [comment]
you need to pass in -jar too

    java -jar selendroid-standalone-0.15.0-with-dependencies.jar

**Comment by ObjectiveTruth** [comment]
Well I'm retarded, thanks for the fast response :+1:
