### ISSUE TITLE
please add isClickable

### ISSUE THREAD

**Issue by ndk-** [selendroid/selendroid#871]
Hi,

I'm trying to use Selendroid for test case generation for black-box testing.
At this moment, I had to resort to dirty tricks in order to determine whether an element is clickable or not.

Could you add isClickable method as well as <i>clickable</i> property to the xml representation of the UI.

In addition, I was trying to find documentation on how to use <i>advanced concepts</i> in Python, however, it seems that it ether well hidden or non-existent. Would it be possible to update the documentation with Python examples?

Thank you in advance!

**Comment by asm89** [comment]
The project is an attempt to implement a [webdriver spec](https://w3c.github.io/webdriver/webdriver-spec.html) compatible server to drive native android applications. What you're trying to achieve can be implemented in a custom extension. See http://selendroid.io/advanced.html#dynamicExtension.
