### ISSUE TITLE
App closed suddenly after launching . same app working find on other devices.  

### ISSUE THREAD

**Issue by nagardhru** [selendroid/selendroid#875]
console log :
May 15, 2015 1:20:02 PM io.selendroid.standalone.SelendroidLauncher launchServer
INFO: Starting Selendroid standalone on port 4444
May 15, 2015 1:20:02 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\salendroidwork\cpw.apk META-INF/MANIFEST.MF
May 15, 2015 1:20:03 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\salendroidwork\cpw.apk META-INF/CERT.RSA
May 15, 2015 1:20:03 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\salendroidwork\cpw.apk META-INF/CERT.SF
May 15, 2015 1:20:03 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\salendroidwork\cpw.apk META-INF/ANDROIDD.SF
May 15, 2015 1:20:04 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\salendroidwork\cpw.apk META-INF/ANDROIDD.RSA
May 15, 2015 1:20:04 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\salendroidwork\cpw.apk META-INF/NDKEYSTO.SF
May 15, 2015 1:20:04 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\salendroidwork\cpw.apk META-INF/NDKEYSTO.RSA
May 15, 2015 1:20:04 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Java\jdk1.6.0_27\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar D:\dhrupal\salendroidwork\resigned-cpw.apk -storepass android -keystore C:\Users\DN00359387\.android\debug.keystore D:\dhrupal\salendroidwork\cpw.apk androiddebugkey
May 15, 2015 1:20:09 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
May 15, 2015 1:20:09 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: 
May 15, 2015 1:20:09 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: D:\dhrupal\salendroidwork\resigned-cpw.apk
May 15, 2015 1:20:09 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe dump badging D:\dhrupal\salendroidwork\resigned-cpw.apk
May 15, 2015 1:20:09 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package: name='com.comviva.cpw' versionCode='7277' versionName='1.0.0'
sdkVersion:'7'
targetSdkVersion:'21'
uses-feature-not-required:'android.hardware.telephony'
uses-feature-not-required:'android.hardware.telephony.cdma'
uses-feature-not-required:'android.hardware.telephony.gsm'
uses-feature-not-required:'android.hardware.camera'
uses-feature-not-required:'android.hardware.camera.autofocus'
uses-feature-not-required:'android.hardware.camera.flash'
uses-feature-not-required:'android.hardware.camera.front'
uses-feature-not-required:'android.hardware.camera.any'
uses-feature-not-required:'android.hardware.bluetooth'
uses-feature-not-required:'android.hardware.bluetooth_le'
uses-feature-not-required:'android.hardware.location'
uses-feature-not-required:'android.hardware.location.network'
uses-feature-not-required:'android.hardware.location.gps'
uses-feature-not-required:'android.hardware.microphone'
uses-feature-not-required:'android.hardware.nfc'
uses-feature-not-required:'android.hardware.nfc.hce'
uses-feature-not-required:'android.hardware.wifi'
uses-feature-not-required:'android.hardware.wifi.direct'
uses-feature-not-required:'android.hardware.screen.landscape'
uses-feature-not-required:'android.hardware.screen.portrait'
uses-permission:'android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission:'android.permission.INTERNET'
uses-permission:'android.permission.ACCESS_NETWORK_STATE'
uses-permission:'android.permission.SEND_SMS'
uses-permission:'android.permission.RECEIVE_SMS'
uses-permission:'android.permission.CALL_PHONE'
uses-permission:'android.permission.WAKE_LOCK'
uses-permission:'android.permission.VIBRATE'
uses-permission:'android.permission.READ_CONTACTS'
uses-permission:'android.permission.READ_PHONE_STATE'
uses-permission:'android.permission.RECORD_AUDIO'
uses-permission:'android.permission.ACCESS_FINE_LOCATION'
uses-permission:'android.permission.ACCESS_WIFI_STATE'
uses-permission:'android.permission.MODIFY_AUDIO_SETTINGS'
uses-permission:'android.permission.CAMERA'
uses-permission:'android.permission.BLUETOOTH_ADMIN'
uses-permission:'android.permission.BLUETOOTH'
uses-permission:'android.permission.GET_ACCOUNTS'
uses-permission:'com.google.android.c2dm.permission.RECEIVE'
uses-permission:'android.permission.USE_CREDENTIALS'
uses-permission:'com.comviva.cpw.permission.C2D_MESSAGE'
application-label:'My ID SIT'
application-icon-120:'res/drawable-ldpi/webaxn.png'
application-icon-160:'res/drawable-mdpi/webaxn.png'
application-icon-240:'res/drawable-hdpi/webaxn.png'
application-icon-320:'res/drawable-xhdpi/webaxn.png'
application-icon-480:'res/drawable-xxhdpi/webaxn.png'
application: label='My ID SIT' icon='res/drawable-mdpi/webaxn.png'
launchable-activity: name='com.comviva.webaxn.ui.WebAxnActivity'  label='' icon=''
uses-permission:'android.permission.READ_EXTERNAL_STORAGE'
uses-implied-permission:'android.permission.READ_EXTERNAL_STORAGE','requested WRITE_EXTERNAL_STORAGE'
uses-feature:'android.hardware.touchscreen'
uses-implied-feature:'android.hardware.touchscreen','assumed you require a touch screen unless explicitly made optional'
main
other-activities
other-receivers
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--'
densities: '120' '160' '240' '320' '480'
<--
May 15, 2015 1:20:09 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe dump badging D:\dhrupal\salendroidwork\resigned-cpw.apk
May 15, 2015 1:20:09 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package: name='com.comviva.cpw' versionCode='7277' versionName='1.0.0'
sdkVersion:'7'
targetSdkVersion:'21'
uses-feature-not-required:'android.hardware.telephony'
uses-feature-not-required:'android.hardware.telephony.cdma'
uses-feature-not-required:'android.hardware.telephony.gsm'
uses-feature-not-required:'android.hardware.camera'
uses-feature-not-required:'android.hardware.camera.autofocus'
uses-feature-not-required:'android.hardware.camera.flash'
uses-feature-not-required:'android.hardware.camera.front'
uses-feature-not-required:'android.hardware.camera.any'
uses-feature-not-required:'android.hardware.bluetooth'
uses-feature-not-required:'android.hardware.bluetooth_le'
uses-feature-not-required:'android.hardware.location'
uses-feature-not-required:'android.hardware.location.network'
uses-feature-not-required:'android.hardware.location.gps'
uses-feature-not-required:'android.hardware.microphone'
uses-feature-not-required:'android.hardware.nfc'
uses-feature-not-required:'android.hardware.nfc.hce'
uses-feature-not-required:'android.hardware.wifi'
uses-feature-not-required:'android.hardware.wifi.direct'
uses-feature-not-required:'android.hardware.screen.landscape'
uses-feature-not-required:'android.hardware.screen.portrait'
uses-permission:'android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission:'android.permission.INTERNET'
uses-permission:'android.permission.ACCESS_NETWORK_STATE'
uses-permission:'android.permission.SEND_SMS'
uses-permission:'android.permission.RECEIVE_SMS'
uses-permission:'android.permission.CALL_PHONE'
uses-permission:'android.permission.WAKE_LOCK'
uses-permission:'android.permission.VIBRATE'
uses-permission:'android.permission.READ_CONTACTS'
uses-permission:'android.permission.READ_PHONE_STATE'
uses-permission:'android.permission.RECORD_AUDIO'
uses-permission:'android.permission.ACCESS_FINE_LOCATION'
uses-permission:'android.permission.ACCESS_WIFI_STATE'
uses-permission:'android.permission.MODIFY_AUDIO_SETTINGS'
uses-permission:'android.permission.CAMERA'
uses-permission:'android.permission.BLUETOOTH_ADMIN'
uses-permission:'android.permission.BLUETOOTH'
uses-permission:'android.permission.GET_ACCOUNTS'
uses-permission:'com.google.android.c2dm.permission.RECEIVE'
uses-permission:'android.permission.USE_CREDENTIALS'
uses-permission:'com.comviva.cpw.permission.C2D_MESSAGE'
application-label:'My ID SIT'
application-icon-120:'res/drawable-ldpi/webaxn.png'
application-icon-160:'res/drawable-mdpi/webaxn.png'
application-icon-240:'res/drawable-hdpi/webaxn.png'
application-icon-320:'res/drawable-xhdpi/webaxn.png'
application-icon-480:'res/drawable-xxhdpi/webaxn.png'
application: label='My ID SIT' icon='res/drawable-mdpi/webaxn.png'
launchable-activity: name='com.comviva.webaxn.ui.WebAxnActivity'  label='' icon=''
uses-permission:'android.permission.READ_EXTERNAL_STORAGE'
uses-implied-permission:'android.permission.READ_EXTERNAL_STORAGE','requested WRITE_EXTERNAL_STORAGE'
uses-feature:'android.hardware.touchscreen'
uses-implied-feature:'android.hardware.touchscreen','assumed you require a touch screen unless explicitly made optional'
main
other-activities
other-receivers
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--'
densities: '120' '160' '240' '320' '480'
<--
May 15, 2015 1:20:09 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver addToAppsStore
INFO: App com.comviva.cpw:1.0.0 has been added to selendroid standalone server.
May 15, 2015 1:20:10 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\TEMP\android-driver2885656925260731708.apk META-INF/MANIFEST.MF
May 15, 2015 1:20:10 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
May 15, 2015 1:20:10 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\TEMP\android-driver2885656925260731708.apk META-INF/CERT.RSA
May 15, 2015 1:20:11 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
May 15, 2015 1:20:11 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\TEMP\android-driver2885656925260731708.apk META-INF/CERT.SF
May 15, 2015 1:20:11 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
May 15, 2015 1:20:11 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\TEMP\android-driver2885656925260731708.apk META-INF/ANDROIDD.SF
May 15, 2015 1:20:11 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\TEMP\android-driver2885656925260731708.apk META-INF/ANDROIDD.RSA
May 15, 2015 1:20:11 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\TEMP\android-driver2885656925260731708.apk META-INF/NDKEYSTO.SF
May 15, 2015 1:20:12 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe remove D:\dhrupal\TEMP\android-driver2885656925260731708.apk META-INF/NDKEYSTO.RSA
May 15, 2015 1:20:12 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Java\jdk1.6.0_27\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar D:\dhrupal\TEMP\resigned-android-driver2885656925260731708.apk -storepass android -keystore C:\Users\DN00359387\.android\debug.keystore D:\dhrupal\TEMP\android-driver2885656925260731708.apk androiddebugkey
May 15, 2015 1:20:13 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
May 15, 2015 1:20:13 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: 
May 15, 2015 1:20:13 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: D:\dhrupal\TEMP\resigned-android-driver2885656925260731708.apk
May 15, 2015 1:20:14 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe -s ZX1D645L7Q shell ls /system/framework/*map*
May 15, 2015 1:20:14 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
/system/framework/com.google.android.maps.jar
<--
May 15, 2015 1:20:14 PM io.selendroid.standalone.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=ZX1D645L7Q, model=null, targetVersion=null]
May 15, 2015 1:20:14 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe -s ZX1D645L7Q shell ls /system/framework/*map*
May 15, 2015 1:20:15 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
/system/framework/com.google.android.maps.jar
<--
May 15, 2015 1:20:15 PM io.selendroid.standalone.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=ZX1D645L7Q, model=XT1068, targetVersion=ANDROID21]
May 15, 2015 1:20:15 PM io.selendroid.standalone.android.impl.DefaultDeviceManager initializeAdbConnection
INFO: my devices: null
May 15, 2015 1:20:15 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\tools\android.bat list avds
May 15, 2015 1:20:20 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
Available Android Virtual Devices:

The following Android Virtual Devices could not be loaded:
    Name: emulator
    Path: C:\Users\DN00359387\.android\avd\emulator.avd
   Error: Unknown target 'android-18' in C:\Users\DN00359387\.android\avd\emulator.ini
<--
May 15, 2015 1:20:20 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe devices
May 15, 2015 1:20:20 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
List of devices attached 
ZX1D645L7Q	device
<--
May 15, 2015 1:20:20 PM io.selendroid.standalone.android.impl.DefaultAndroidEmulator getScreenSizeFromSkin
WARNING: Failed to get dimensions for skin: 
May 15, 2015 1:20:20 PM io.selendroid.standalone.server.model.DeviceStore addEmulators
INFO: Adding: AndroidEmulator [screenSize=null, targetPlatform=null, serial=null, avdName=emulator, model=, apiTargetType=android]
May 15, 2015 1:20:20 PM io.selendroid.standalone.server.SelendroidStandaloneServer start
INFO: Selendroid standalone server has been started on port: 4444
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
launch
start
May 15, 2015 1:20:23 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver createNewTestSession
INFO: 'com.comviva.cpw:1.0.0' will be used as app under test.
May 15, 2015 1:20:23 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe -s ZX1D645L7Q shell pm list packages com.comviva.cpw
May 15, 2015 1:20:24 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package:io.selendroid.com.comviva.cpw
package:com.comviva.cpw
<--
May 15, 2015 1:20:24 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver createNewTestSession
INFO: the app under test is already installed.
May 15, 2015 1:20:24 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe -s ZX1D645L7Q shell pm list packages io.selendroid.com.comviva.cpw
May 15, 2015 1:20:25 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package:io.selendroid.com.comviva.cpw
<--
May 15, 2015 1:20:25 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver createNewTestSession
INFO: Not creating and installing selendroid-server because it is already installed for this app under test.
May 15, 2015 1:20:25 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe -s ZX1D645L7Q shell setprop log.tag.SELENDROID ERROR
May 15, 2015 1:20:25 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
May 15, 2015 1:20:25 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\aapt.exe dump badging D:\dhrupal\salendroidwork\resigned-cpw.apk
May 15, 2015 1:20:25 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package: name='com.comviva.cpw' versionCode='7277' versionName='1.0.0'
sdkVersion:'7'
targetSdkVersion:'21'
uses-feature-not-required:'android.hardware.telephony'
uses-feature-not-required:'android.hardware.telephony.cdma'
uses-feature-not-required:'android.hardware.telephony.gsm'
uses-feature-not-required:'android.hardware.camera'
uses-feature-not-required:'android.hardware.camera.autofocus'
uses-feature-not-required:'android.hardware.camera.flash'
uses-feature-not-required:'android.hardware.camera.front'
uses-feature-not-required:'android.hardware.camera.any'
uses-feature-not-required:'android.hardware.bluetooth'
uses-feature-not-required:'android.hardware.bluetooth_le'
uses-feature-not-required:'android.hardware.location'
uses-feature-not-required:'android.hardware.location.network'
uses-feature-not-required:'android.hardware.location.gps'
uses-feature-not-required:'android.hardware.microphone'
uses-feature-not-required:'android.hardware.nfc'
uses-feature-not-required:'android.hardware.nfc.hce'
uses-feature-not-required:'android.hardware.wifi'
uses-feature-not-required:'android.hardware.wifi.direct'
uses-feature-not-required:'android.hardware.screen.landscape'
uses-feature-not-required:'android.hardware.screen.portrait'
uses-permission:'android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission:'android.permission.INTERNET'
uses-permission:'android.permission.ACCESS_NETWORK_STATE'
uses-permission:'android.permission.SEND_SMS'
uses-permission:'android.permission.RECEIVE_SMS'
uses-permission:'android.permission.CALL_PHONE'
uses-permission:'android.permission.WAKE_LOCK'
uses-permission:'android.permission.VIBRATE'
uses-permission:'android.permission.READ_CONTACTS'
uses-permission:'android.permission.READ_PHONE_STATE'
uses-permission:'android.permission.RECORD_AUDIO'
uses-permission:'android.permission.ACCESS_FINE_LOCATION'
uses-permission:'android.permission.ACCESS_WIFI_STATE'
uses-permission:'android.permission.MODIFY_AUDIO_SETTINGS'
uses-permission:'android.permission.CAMERA'
uses-permission:'android.permission.BLUETOOTH_ADMIN'
uses-permission:'android.permission.BLUETOOTH'
uses-permission:'android.permission.GET_ACCOUNTS'
uses-permission:'com.google.android.c2dm.permission.RECEIVE'
uses-permission:'android.permission.USE_CREDENTIALS'
uses-permission:'com.comviva.cpw.permission.C2D_MESSAGE'
application-label:'My ID SIT'
application-icon-120:'res/drawable-ldpi/webaxn.png'
application-icon-160:'res/drawable-mdpi/webaxn.png'
application-icon-240:'res/drawable-hdpi/webaxn.png'
application-icon-320:'res/drawable-xhdpi/webaxn.png'
application-icon-480:'res/drawable-xxhdpi/webaxn.png'
application: label='My ID SIT' icon='res/drawable-mdpi/webaxn.png'
launchable-activity: name='com.comviva.webaxn.ui.WebAxnActivity'  label='' icon=''
uses-permission:'android.permission.READ_EXTERNAL_STORAGE'
uses-implied-permission:'android.permission.READ_EXTERNAL_STORAGE','requested WRITE_EXTERNAL_STORAGE'
uses-feature:'android.hardware.touchscreen'
uses-implied-feature:'android.hardware.touchscreen','assumed you require a touch screen unless explicitly made optional'
main
other-activities
other-receivers
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--'
densities: '120' '160' '240' '320' '480'
<--
May 15, 2015 1:20:25 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe -s ZX1D645L7Q shell am instrument -e main_activity com.comviva.webaxn.ui.WebAxnActivity -e server_port 8080 io.selendroid.com.comviva.cpw/io.selendroid.server.ServerInstrumentation
May 15, 2015 1:20:26 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
May 15, 2015 1:20:26 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe -s ZX1D645L7Q forward tcp:8080 tcp:8080
May 15, 2015 1:20:26 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
May 15, 2015 1:20:26 PM io.selendroid.standalone.android.impl.AbstractDevice startLogging
INFO: starting logcat:
May 15, 2015 1:20:26 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver waitForServerStart
INFO: Waiting for the Selendroid server to start.
May 15, 2015 1:20:26 PM io.selendroid.standalone.android.impl.AbstractDevice isSelendroidRunning
INFO: Checking if the Selendroid server is running: http://localhost:8080/wd/hub/status
May 15, 2015 1:20:26 PM io.selendroid.standalone.android.impl.AbstractDevice isSelendroidRunning
INFO: Got response status code: 200
May 15, 2015 1:20:26 PM io.selendroid.standalone.android.impl.AbstractDevice isSelendroidRunning
INFO: Got response value: {"status":0,"value":{"build":{"version":"0.13.0-SNAPSHOT","browserName":"selendroid"},"os":{"arch":"armeabi-v7a","name":"Android","version":"21"},"supportedDevices":[],"supportedApps":[]}}
May 15, 2015 1:20:26 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver waitForServerStart
INFO: Selendroid server has started.

code :+1: SelendroidConfiguration config = new SelendroidConfiguration();
				// Add the selendroid-test-app to the standalone server

				config.addSupportedApp("apk location");

				config.isDeviceScreenshot();
				String GetEmu = config.getEmulatorOptions();
				System.out.println(GetEmu);
				// start the standalone server
				SelendroidLauncher selendroidServer = new SelendroidLauncher(
						config);
			
				selendroidServer.launchSelendroid();
				System.out.println("launch"); 

SelendroidCapabilities caps = new SelendroidCapabilities("app ID");
	
				System.out.println("start");

http://localhost:4444/wd/hub/status :

{"status":0,"value":{"supportedApps":[{"appId":"io.selendroid.androiddriver:0.15.0","mainActivity":"io.selendroid.androiddriver.WebViewActivity","basePackage":"io.selendroid.androiddriver"},{"appId":"com.comviva.cpw:1.0.0","mainActivity":"com.comviva.webaxn.ui.WebAxnActivity","basePackage":"com.comviva.cpw"}],"os":{"arch":"x86","name":"Windows 7","version":"6.1"},"build":{"browserName":"selendroid","version":"0.15.0"},"supportedDevices":[{"screenSize":"(720, 1280)","platformVersion":"21","model":"XT1068","emulator":false,"serial":"ZX1D645L7Q"}]}}

don't know what is the issue ... app launch with different devices but facing issue while launch app with android 5.0;

able to launch app with adb command also.

**Comment by nagardhru** [comment]
logcat log for app :
05-15 12:45:12.435: D/SFPerfTracer(323):        layers: (3:9) (FocusedStackFrame (0xb756e6e8): 1:9296)* (DimLayer (0xb7580eb0): 0:11)* (DimLayer (0xb75102d8): 0:1556)* (DimLayer (0xb7511c40): 0:2356)* (StatusBar (0xb75444c0): 0:135249) (com.android.systemui.ImageWallpaper (0xb7549330): 0:3227)* (NavigationBar (0xb7514030): 28:299) (com.comviva.cpw/com.comviva.webaxn.ui.WebAxnActivity (0xb7537bf8): 0:289) 
05-15 12:45:13.301: W/PackageManager(1415): Failure retrieving resources for com.comviva.cpw: Resource ID #0x0
05-15 12:45:14.285: D/SFPerfTracer(323):        layers: (4:11) (FocusedStackFrame (0xb756e6e8): 1:9301)* (DimLayer (0xb7580eb0): 0:11)* (DimLayer (0xb75102d8): 0:1556)* (DimLayer (0xb7511c40): 0:2356)* (StatusBar (0xb75444c0): 2:135271) (com.android.systemui.ImageWallpaper (0xb7549330): 0:3228) (NavigationBar (0xb7514030): 2:343) (com.comviva.cpw/com.comviva.webaxn.ui.WebAxnActivity (0xb7537bf8): 0:315)- (com.google.android.googlequicksearchbox/com.google.android.launcher.GEL (0xb75a0cf8): 0:31)- (com.android.systemui/com.android.systemui.recents.RecentsActivity (0xb7537bf8): 32:42) 
05-15 12:45:15.017: D/TaskStackView(1415): onTaskViewDismissed: task = Task (1860): com.comviva.cpw [com.android.systemui.recents.model.Task@2b7dd5da] index = 1 focused = false
05-15 12:45:15.018: I/ActivityManager(917): Killing 14245:com.comviva.cpw/u0a126 (adj 11): remove task
05-15 12:59:39.602: I/ActivityManager(917): START u0 {flg=0x10000000 cmp=com.comviva.cpw/com.comviva.webaxn.ui.WebAxnActivity} from uid 2000 on display 0
05-15 12:59:39.686: I/ActivityManager(917): Start proc com.comviva.cpw for activity com.comviva.cpw/com.comviva.webaxn.ui.WebAxnActivity: pid=17128 uid=10126 gids={50126, 9997, 1028, 1015, 3003, 3001, 3002} abi=armeabi-v7a
05-15 12:59:40.414: I/LaunchCheckinHandler(917): Displayed com.comviva.cpw/com.comviva.webaxn.ui.WebAxnActivity,cp,ca,777
05-15 12:59:40.415: I/ActivityManager(917): Displayed com.comviva.cpw/com.comviva.webaxn.ui.WebAxnActivity: +777ms
05-15 12:59:40.529: V/WindowStateAnimator(917): windowAnimating in WindowStateAnimator{268173eb Starting com.comviva.cpw}
05-15 12:59:51.878: D/SFPerfTracer(323):        layers: (3:11) (FocusedStackFrame (0xb756e6e8): 0:9309)* (DimLayer (0xb7580eb0): 0:11)* (DimLayer (0xb75102d8): 0:1556)* (DimLayer (0xb7511c40): 0:2359)* (StatusBar (0xb75444c0): 1:135381) (com.android.systemui.ImageWallpaper (0xb7549330): 0:3230)* (NavigationBar (0xb7514030): 0:356) (com.google.android.googlequicksearchbox/com.google.android.launcher.GEL (0xb75a0cf8): 0:78)- (Starting com.comviva.cpw (0xb7537bf8): 0:33)- (com.comviva.cpw/com.comviva.webaxn.ui.WebAxnActivity (0xb7547290): 0:24) 
05-15 13:05:32.769: I/ActivityManager(917): START u0 {flg=0x10000000 cmp=com.comviva.cpw/com.comviva.webaxn.ui.WebAxnActivity} from uid 2000 on display 0
05-15 13:08:15.041: D/SFPerfTracer(323):        layers: (4:10) (FocusedStackFrame (0xb756e6e8): 0:9309)* (DimLayer (0xb7580eb0): 0:11)* (DimLayer (0xb75102d8): 0:1556)* (DimLayer (0xb7511c40): 0:2359)* (StatusBar (0xb75444c0): 0:135447) (com.android.systemui.ImageWallpaper (0xb7549330): 0:3230)* (NavigationBar (0xb7514030): 0:356) (com.comviva.cpw/com.comviva.webaxn.ui.WebAxnActivity (0xb7547290): 0:24) (Heads Up (0xb7537bf8): 12:16) 
05-15 13:08:23.599: D/SFPerfTracer(323):        layers: (3:12) (FocusedStackFrame (0xb756e6e8): 1:9315)* (DimLayer (0xb7580eb0): 0:11)* (DimLayer (0xb75102d8): 0:1556)* (DimLayer (0xb7511c40): 0:2362)* (StatusBar (0xb75444c0): 0:135474) (com.android.systemui.ImageWallpaper (0xb7549330): 0:3230)* (NavigationBar (0xb7514030): 0:369) (com.comviva.cpw/com.comviva.webaxn.ui.WebAxnActivity (0xb7547290): 0:52)- (Heads Up (0xb7537bf8): 0:31)- (Starting com.whatsapp (0xb75a0cf8): 0:41)- (com.whatsapp/com.whatsapp.Conversation (0xb7537bf8): 37:44)

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
