### ISSUE TITLE
reference error when calling switchTo

### ISSUE THREAD

**Issue by MartinoMensio** [selendroid/selendroid#878]
I am testing a cordova app on android using selendroid. Tests are written in protractor.

When i call switchTo().window("WEBVIEW") i get a java.lang.VerifyError:
Verifier rejected class io.selendroid.server.model.SelendroidWebDriver$4 due to bad method void io.selendroid.server.model.SelendroidWebDriver$4.run() (declaration of 'io.selendroid.server.model.SelendroidWebDriver$4' appears in /data/app/io.selendroid.com.myapp-1/base.apk)

In the logcat i see the following:
void io.selendroid.server.model.SelendroidWebDriver$4.run() failed to verify: register v5 has type Precise Reference: io.selendroid.server.model.SelendroidWebDriver$ExtendedCordovaChromeClient but expected Reference: android.webkit.WebChromeClient

I am currently using selendroid 15, but i tried also with 16 and 13 and the error is the same.

How can i fix that? Maybe i have a wrong configuration?

Thanks

**Comment by operatiay** [comment]
you're testing a cordova application. it's a complicated issue due to the internal implementation of cordova platform being in continuous change. I think that currently officially supported cordova version is 3.7. For that you must build selendroid manually (afaik).
If you're using a different cordova then the support is worse. Search for cordova related issues here and you'll find some clues if you want to dig into it. hope this helps.

**Comment by MartinoMensio** [comment]
Thanks for your reply. I am searching to build selendroid, but since i never used maven, it will take some time

**Comment by operatiay** [comment]
here are the steps (once you've installed maven on your machine):

- go to the folder where you've cloned the selendroid repository to
- call `./third-party/mvnInstall.sh`
- call `mvn clean install`
- you should be able to find your artifacts in the folder `target`

**Comment by MartinoMensio** [comment]
Thanks.
I have Android SDK API level 21 and 22 installed but when building it is searching API level 16. I need to install this obsolete one?

Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.1.1:generate-sources (default-generate-sources) on project android-driver-app: Execution default-generate-sources of goal com.simpligility.maven.plugins:android-maven-plugin:4.1.1:generate-sources failed: Invalid SDK: Platform/API level 16 not available. This command should give you all you need:
[ERROR] /home/martino/android-sdk-linux/tools/android update sdk --no-ui --obsolete --force

**Comment by MartinoMensio** [comment]
I answer myself: Yes. Building selendroid works. Now i only need to fix ChromeClient type

**Comment by operatiay** [comment]
:+1: go for it!

**Comment by asm89** [comment]
Closing as it seems resolved.
