### ISSUE TITLE
JavaDoc

### ISSUE THREAD

**Issue by kovalev007** [selendroid/selendroid#879]
Where i can find javadoc for selendroid?

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by asm89** [comment]
Also I don't think we provide a html generated version of the javadocs.
