### ISSUE TITLE
Automation of application with expansion file (obb file)

### ISSUE THREAD

**Issue by fayizkc** [selendroid/selendroid#882]
I want to automate an application which is downloaded from Google play, which has expansion. Actual size of the application is 128 MB. So the base app size is only 23 MB, remaining app contends are saving to Android/obb folder. How can I use this entire application for automation with Selendroid. I did not find any option to load .obb file in the Selendoird

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by asm89** [comment]
Quick thought. Do you actually want to test the .obb file expansion loading? Or are you just interesting in covering those parts of the app? If the latter, I'd recommend having a debug build that has all functionality you want to cover in your tests.
