### ISSUE TITLE
[Not A Bug] How can i increase session  timeout , (which is 30 minute by default)

### ISSUE THREAD

**Issue by biswatmanayak** [selendroid/selendroid#885]
I want to handle server timeout in programmatically.

My codes goes like this.	

SelendroidConfiguration config = new SelendroidConfiguration();
		config.addSupportedApp("apk/test.apk");
		selendroidServer = new SelendroidLauncher(config);

		URL url = new URL("http://localhost:4444/wd/hub");
		// -------------------------------------------------------
		SelendroidCapabilities test= SelendroidCapabilities
				.device("com.test.android:1.0");
		driver = new SelendroidDriver(url, test);

**Comment by lukeis** [comment]
update the selendroidConfiguration:

    config.setSessionTimeoutSeconds(60 * 60 * 24); // one day, change to what you want it to be.

**Comment by biswatmanayak** [comment]
Thanks a lot,  I am not getting proper doc to learn more about selendroid, can you please provide?
