### ISSUE TITLE
Selendroid 0.15 setLogLevel() method is not working

### ISSUE THREAD

**Issue by metasonic** [selendroid/selendroid#886]
**Running test in eclipse with the following configs:**
SelendroidConfiguration config = new SelendroidConfiguration();
config.setLogLevel(LogLevelEnum.ERROR);
config.setDeviceLog(false);
config.addSupportedApp(ParametersManager.getMbaApk());
selendroidServer = new SelendroidLauncher(config);
selendroidServer.launchSelendroid();

**Although i change the selendroid server log lvl the output doesnt have any effect**

**Eclipse console logs**
Jun 09, 2015 4:38:30 PM io.selendroid.standalone.SelendroidLauncher launchServer
INFO: Starting Selendroid standalone on port 4444
Jun 09, 2015 4:38:30 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Selenium\Workspace\JavaProjects\lib\Test.apk META-INF/MANIFEST.MF
Jun 09, 2015 4:38:30 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Selenium\Workspace\JavaProjects\lib\Test.apk META-INF/CERT.RSA
Jun 09, 2015 4:38:30 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Selenium\Workspace\JavaProjects\lib\Test.apk META-INF/CERT.SF
Jun 09, 2015 4:38:30 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Selenium\Workspace\JavaProjects\lib\Test.apk META-INF/ANDROIDD.SF
Jun 09, 2015 4:38:30 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Selenium\Workspace\JavaProjects\lib\Test.apk META-INF/ANDROIDD.RSA
Jun 09, 2015 4:38:30 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Selenium\Workspace\JavaProjects\lib\Test.apk META-INF/NDKEYSTO.SF
Jun 09, 2015 4:38:30 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Selenium\Workspace\JavaProjects\lib\Test.apk META-INF/NDKEYSTO.RSA
Jun 09, 2015 4:38:30 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Java\jdk1.8.0_40\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Selenium\Workspace\JavaProjects\lib\resigned-Test.apk -storepass android -keystore C:\Users\Aurelian\.android\debug.keystore C:\Selenium\Workspace\JavaProjects\lib\Test.apk androiddebugkey
Jun 09, 2015 4:38:31 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2042-09-21) or after any future revocation date.
<--
Jun 09, 2015 4:38:31 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2042-09-21) or after any future revocation date.
Jun 09, 2015 4:38:31 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: C:\Selenium\Workspace\JavaProjects\lib\resigned-Test.apk
Jun 09, 2015 4:38:31 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe dump badging C:\Selenium\Workspace\JavaProjects\lib\resigned-Test.apk
Jun 09, 2015 4:38:31 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package: name='test.appp' versionCode='1' versionName='1.1.6-beta' platformBuildVersionName=''
sdkVersion:'14'
targetSdkVersion:'21'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.MODIFY_AUDIO_SETTINGS'
uses-permission: name='android.permission.RECORD_AUDIO'
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='android.permission.BLUETOOTH'
application-label:'Test Appp'
application-icon-120:'res/drawable-mdpi/ic_launcher.png'
application-icon-160:'res/drawable-mdpi/ic_launcher.png'
application-icon-240:'res/drawable-hdpi/ic_launcher.png'
application-icon-320:'res/drawable-xhdpi/ic_launcher.png'
application-icon-480:'res/drawable-xxhdpi/ic_launcher.png'
application-icon-640:'res/drawable-xxxhdpi/ic_launcher.png'
application: label='Test Appp' icon='res/drawable-mdpi/ic_launcher.png'
launchable-activity: name='test.appp.MainActivity'  label='Test Appp' icon=''
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-implied-permission: name='android.permission.READ_EXTERNAL_STORAGE' reason='requested WRITE_EXTERNAL_STORAGE'
feature-group: label=''
  uses-feature: name='android.hardware.camera'
  uses-feature-not-required: name='android.hardware.camera.autofocus'
  uses-feature: name='android.hardware.bluetooth'
  uses-implied-feature: name='android.hardware.bluetooth' reason='requested android.permission.BLUETOOTH permission, and targetSdkVersion > 4'
  uses-feature: name='android.hardware.microphone'
  uses-implied-feature: name='android.hardware.microphone' reason='requested android.permission.RECORD_AUDIO permission'
  uses-feature: name='android.hardware.screen.landscape'
  uses-implied-feature: name='android.hardware.screen.landscape' reason='one or more activities have specified a landscape orientation'
  uses-feature: name='android.hardware.touchscreen'
  uses-implied-feature: name='android.hardware.touchscreen' reason='default feature for all apps'
main
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--'
densities: '120' '160' '240' '320' '480' '640'
<--
Jun 09, 2015 4:38:31 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe dump badging C:\Selenium\Workspace\JavaProjects\lib\resigned-Test.apk
Jun 09, 2015 4:38:31 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package: name='test.appp' versionCode='1' versionName='1.1.6-beta' platformBuildVersionName=''
sdkVersion:'14'
targetSdkVersion:'21'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.MODIFY_AUDIO_SETTINGS'
uses-permission: name='android.permission.RECORD_AUDIO'
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='android.permission.BLUETOOTH'
application-label:'Test Appp'
application-icon-120:'res/drawable-mdpi/ic_launcher.png'
application-icon-160:'res/drawable-mdpi/ic_launcher.png'
application-icon-240:'res/drawable-hdpi/ic_launcher.png'
application-icon-320:'res/drawable-xhdpi/ic_launcher.png'
application-icon-480:'res/drawable-xxhdpi/ic_launcher.png'
application-icon-640:'res/drawable-xxxhdpi/ic_launcher.png'
application: label='Test Appp' icon='res/drawable-mdpi/ic_launcher.png'
launchable-activity: name='test.appp.MainActivity'  label='Test Appp' icon=''
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-implied-permission: name='android.permission.READ_EXTERNAL_STORAGE' reason='requested WRITE_EXTERNAL_STORAGE'
feature-group: label=''
  uses-feature: name='android.hardware.camera'
  uses-feature-not-required: name='android.hardware.camera.autofocus'
  uses-feature: name='android.hardware.bluetooth'
  uses-implied-feature: name='android.hardware.bluetooth' reason='requested android.permission.BLUETOOTH permission, and targetSdkVersion > 4'
  uses-feature: name='android.hardware.microphone'
  uses-implied-feature: name='android.hardware.microphone' reason='requested android.permission.RECORD_AUDIO permission'
  uses-feature: name='android.hardware.screen.landscape'
  uses-implied-feature: name='android.hardware.screen.landscape' reason='one or more activities have specified a landscape orientation'
  uses-feature: name='android.hardware.touchscreen'
  uses-implied-feature: name='android.hardware.touchscreen' reason='default feature for all apps'
main
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--'
densities: '120' '160' '240' '320' '480' '640'
<--
Jun 09, 2015 4:38:31 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver addToAppsStore
INFO: App test.appp:1.1.6-beta has been added to selendroid standalone server.
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Users\Aurelian\AppData\Local\Temp\android-driver832065446501005436.apk META-INF/MANIFEST.MF
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Users\Aurelian\AppData\Local\Temp\android-driver832065446501005436.apk META-INF/CERT.RSA
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Users\Aurelian\AppData\Local\Temp\android-driver832065446501005436.apk META-INF/CERT.SF
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Users\Aurelian\AppData\Local\Temp\android-driver832065446501005436.apk META-INF/ANDROIDD.SF
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Users\Aurelian\AppData\Local\Temp\android-driver832065446501005436.apk META-INF/ANDROIDD.RSA
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Users\Aurelian\AppData\Local\Temp\android-driver832065446501005436.apk META-INF/NDKEYSTO.SF
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe remove C:\Users\Aurelian\AppData\Local\Temp\android-driver832065446501005436.apk META-INF/NDKEYSTO.RSA
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Java\jdk1.8.0_40\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\Aurelian\AppData\Local\Temp\resigned-android-driver832065446501005436.apk -storepass android -keystore C:\Users\Aurelian\.android\debug.keystore C:\Users\Aurelian\AppData\Local\Temp\android-driver832065446501005436.apk androiddebugkey
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2042-09-21) or after any future revocation date.
<--
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2042-09-21) or after any future revocation date.
Jun 09, 2015 4:38:32 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: C:\Users\Aurelian\AppData\Local\Temp\resigned-android-driver832065446501005436.apk
Jun 09, 2015 4:38:36 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe -s LGD8552e174058 shell ls /system/framework/*map*
Jun 09, 2015 4:38:36 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
/system/framework/com.google.android.maps.jar
/system/framework/qmapbridge.jar
<--
Jun 09, 2015 4:38:36 PM io.selendroid.standalone.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=LGD8552e174058, model=null, targetVersion=null]
Jun 09, 2015 4:38:37 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe -s LGD8552e174058 shell ls /system/framework/*map*
Jun 09, 2015 4:38:37 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
/system/framework/com.google.android.maps.jar
/system/framework/qmapbridge.jar
<--
Jun 09, 2015 4:38:37 PM io.selendroid.standalone.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=LGD8552e174058, model=LG-D855, targetVersion=ANDROID19]
Jun 09, 2015 4:38:37 PM io.selendroid.standalone.android.impl.DefaultDeviceManager initializeAdbConnection
INFO: my devices: null
Jun 09, 2015 4:38:37 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\tools\android.bat list avds
Jun 09, 2015 4:38:38 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
Available Android Virtual Devices:
<--
Jun 09, 2015 4:38:38 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe devices
Jun 09, 2015 4:38:38 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
List of devices attached 
LGD8552e174058	device
<--
Jun 09, 2015 4:38:38 PM io.selendroid.standalone.server.model.DeviceStore addEmulators
INFO: No emulators has been found.
Jun 09, 2015 4:38:38 PM io.selendroid.standalone.server.SelendroidStandaloneServer start
INFO: Selendroid standalone server has been started on port: 4444
Jun 09, 2015 4:38:39 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver createNewTestSession
INFO: 'test.appp:1.1.6-beta' will be used as app under test.
Jun 09, 2015 4:38:39 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe -s LGD8552e174058 shell pm list packages test.appp
Jun 09, 2015 4:38:40 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package:test.appp
package:io.selendroid.test.appp
<--
Jun 09, 2015 4:38:40 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver createNewTestSession
INFO: the app under test is already installed.
Jun 09, 2015 4:38:40 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe -s LGD8552e174058 shell pm list packages io.selendroid.test.appp
Jun 09, 2015 4:38:41 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package:io.selendroid.test.appp
<--
Jun 09, 2015 4:38:41 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver createNewTestSession
INFO: Not creating and installing selendroid-server because it is already installed for this app under test.
Jun 09, 2015 4:38:41 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe -s LGD8552e174058 shell setprop log.tag.SELENDROID ERROR
Jun 09, 2015 4:38:41 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 09, 2015 4:38:41 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\build-tools\22.0.1\aapt.exe dump badging C:\Selenium\Workspace\JavaProjects\lib\resigned-Test.apk
Jun 09, 2015 4:38:41 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package: name='test.appp' versionCode='1' versionName='1.1.6-beta' platformBuildVersionName=''
sdkVersion:'14'
targetSdkVersion:'21'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.MODIFY_AUDIO_SETTINGS'
uses-permission: name='android.permission.RECORD_AUDIO'
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='android.permission.BLUETOOTH'
application-label:'Test Appp'
application-icon-120:'res/drawable-mdpi/ic_launcher.png'
application-icon-160:'res/drawable-mdpi/ic_launcher.png'
application-icon-240:'res/drawable-hdpi/ic_launcher.png'
application-icon-320:'res/drawable-xhdpi/ic_launcher.png'
application-icon-480:'res/drawable-xxhdpi/ic_launcher.png'
application-icon-640:'res/drawable-xxxhdpi/ic_launcher.png'
application: label='Test Appp' icon='res/drawable-mdpi/ic_launcher.png'
launchable-activity: name='test.appp.MainActivity'  label='Test Appp' icon=''
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-implied-permission: name='android.permission.READ_EXTERNAL_STORAGE' reason='requested WRITE_EXTERNAL_STORAGE'
feature-group: label=''
  uses-feature: name='android.hardware.camera'
  uses-feature-not-required: name='android.hardware.camera.autofocus'
  uses-feature: name='android.hardware.bluetooth'
  uses-implied-feature: name='android.hardware.bluetooth' reason='requested android.permission.BLUETOOTH permission, and targetSdkVersion > 4'
  uses-feature: name='android.hardware.microphone'
  uses-implied-feature: name='android.hardware.microphone' reason='requested android.permission.RECORD_AUDIO permission'
  uses-feature: name='android.hardware.screen.landscape'
  uses-implied-feature: name='android.hardware.screen.landscape' reason='one or more activities have specified a landscape orientation'
  uses-feature: name='android.hardware.touchscreen'
  uses-implied-feature: name='android.hardware.touchscreen' reason='default feature for all apps'
main
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--'
densities: '120' '160' '240' '320' '480' '640'
<--
Jun 09, 2015 4:38:41 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe -s LGD8552e174058 shell am instrument -e main_activity test.appp.MainActivity -e server_port 8080 io.selendroid.test.appp/io.selendroid.server.ServerInstrumentation
Jun 09, 2015 4:38:42 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 09, 2015 4:38:42 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe -s LGD8552e174058 forward tcp:8080 tcp:8080
Jun 09, 2015 4:38:42 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 09, 2015 4:38:42 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver waitForServerStart
INFO: Waiting for the Selendroid server to start.
Jun 09, 2015 4:38:42 PM io.selendroid.standalone.android.impl.AbstractDevice isSelendroidRunning
INFO: Checking if the Selendroid server is running: http://localhost:8080/wd/hub/status
Jun 09, 2015 4:38:42 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:8080: The target server failed to respond
Jun 09, 2015 4:38:42 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8080
Jun 09, 2015 4:38:42 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:8080: The target server failed to respond
Jun 09, 2015 4:38:42 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8080
Jun 09, 2015 4:38:42 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8080: Connection reset
Jun 09, 2015 4:38:42 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8080
Jun 09, 2015 4:38:42 PM io.selendroid.standalone.android.impl.AbstractDevice isSelendroidRunning
INFO: Can't connect to Selendroid server, assuming it is not running.
Jun 09, 2015 4:38:44 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe -s LGD8552e174058 shell echo $EXTERNAL_STORAGE
Jun 09, 2015 4:38:44 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
/storage/emulated/legacy
<--
Jun 09, 2015 4:38:44 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe -s LGD8552e174058 shell ls C:\storage\emulated\legacy/
Jun 09, 2015 4:38:44 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
C:\storage\emulated\legacy/: No such file or directory
<--
Jun 09, 2015 4:38:44 PM io.selendroid.standalone.android.impl.AbstractDevice isSelendroidRunning
INFO: Checking if the Selendroid server is running: http://localhost:8080/wd/hub/status
Jun 09, 2015 4:38:44 PM io.selendroid.standalone.android.impl.AbstractDevice isSelendroidRunning
INFO: Got response status code: 200
Jun 09, 2015 4:38:44 PM io.selendroid.standalone.android.impl.AbstractDevice isSelendroidRunning
INFO: Got response value: {"value":{"supportedApps":[],"build":{"browserName":"selendroid","version":"0.13.0-SNAPSHOT"},"os":{"arch":"armeabi-v7a","version":"19","name":"Android"},"supportedDevices":[]},"status":0}
Jun 09, 2015 4:38:44 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver waitForServerStart
INFO: Selendroid server has started.

**~~~ Test started: testTestAppFunctionality**
~~~~~~~ test print 1
~~~~~~~ test print 2
~~~~~~~ test print 3
~~~~~~~ test print 4
	
Jun 09, 2015 4:39:36 PM io.selendroid.standalone.server.model.DeviceStore release
INFO: Releasing device HardwareDevice [serial=LGD8552e174058, model=LG-D855, targetVersion=ANDROID19]
Jun 09, 2015 4:39:36 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe -s LGD8552e174058 shell am force-stop test.appp
Jun 09, 2015 4:39:37 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 09, 2015 4:39:37 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe -s LGD8552e174058 forward --remove tcp:8080
Jun 09, 2015 4:39:37 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 09, 2015 4:39:37 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Selenium\Workspace\Android\sdk\platform-tools\adb.exe -s LGD8552e174058 shell pm clear test.appp
Jun 09, 2015 4:39:38 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
Success
<--
Jun 09, 2015 4:39:38 PM io.selendroid.standalone.server.SelendroidStandaloneServer stop
INFO: Stopping selendroid-standalone server
Jun 09, 2015 4:39:38 PM io.selendroid.standalone.android.impl.DefaultDeviceManager shutdown
INFO: Notifying device listener about shutdown
Jun 09, 2015 4:39:38 PM io.selendroid.standalone.android.impl.DefaultDeviceManager shutdown
INFO: Removing Device Manager listener from ADB
Jun 09, 2015 4:39:38 PM io.selendroid.standalone.android.impl.DefaultDeviceManager shutdown
INFO: stopping Device Manager

**~~~ Test finished: testTestAppFunctionality**
Jun 09, 2015 4:39:38 PM io.selendroid.standalone.SelendroidLauncher$1 run
INFO: Shutting down Selendroid standalone

**Comment by asm89** [comment]
The log level configuration affect the logging of the selendroid-server on the device, not the logging of the standalone server. The logs you pasted in your comments are standalone server logs.
