### ISSUE TITLE
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES] error while installing resigned apk by selendroid standalone jar

### ISSUE THREAD

**Issue by mayurdharmadhikari** [selendroid/selendroid#891]
Hi,

I am using selendroid-standalone-0.15.0-with-dependencies.jar to test my application and when I run command java -jar selendroid-standalone-0.15.0-with-dependencies.jar -aut testapp.apk,

It creates resigned apk and while trying to install it,I am getting "Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]"

Installed java version is 1.7
Thanks friends in advance!

**Comment by lukeis** [comment]
This likely means you don't have a debug certificate to sign apk's, should be located ~/.android/debug.keystore

Selendroid should be triggering the android apk to generate this, so not sure what's going on. Care to share the full output from your selendroid server?

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
