### ISSUE TITLE
Please allow a true/Boolean capability to be defined with the string "true"

### ISSUE THREAD

**Issue by sglebs** [selendroid/selendroid#892]
I am trying to use Selendroid from FitNesse https://github.com/fhoeben/hsac-fitnesse-fixtures/issues/10 but it passes "true" down. Can we please change this code below (in SelendroidCapabilities) so that it also takes the string "true" as a valid boolean/true value?

```
  public Boolean getEmulator() {
    if (getRawCapabilities().get(EMULATOR) == null
        || getRawCapabilities().get(EMULATOR).equals(JSONObject.NULL)) return null;
    return getBooleanCapability(EMULATOR);
  }

  // throws exception if user didn't pass the capability as a boolean
  private Boolean getBooleanCapability(String key) {
    Object o = getRawCapabilities().get(key);
    if (o == null) {
      return null;
    } else if (o instanceof Boolean) {
      return (Boolean) o;
    } else {
      throw new ClassCastException(String.format(
          "DesiredCapability %s's value should be boolean: found value %s of type %s", key, o.toString(), o.getClass()
              .getName()));
    }
  }
```

Thanks for listening!

**Comment by lukeis** [comment]
There's other Boolean capabilities and other drivers also have Boolean capabilities. I'd highly recommend updating your library to allow sending Boolean capabilities as there's no guarantee other new ones or other drivers won't require them in the future.

**Comment by fhoeben** [comment]
Why don't you use Capabilities `is` method instead of having your own `getBooleanCapability`? Or at least copy its behavior?

http://javadox.com/org.seleniumhq.selenium/selenium-api/2.40.0/org/openqa/selenium/Capabilities.html#is(java.lang.String)

```java
  public boolean is(String capabilityName) {
    Object cap = getCapability(capabilityName);
    if (cap == null) {
      return false;
    }
    return cap instanceof Boolean ? (Boolean) cap : Boolean.parseBoolean(String.valueOf(cap));
  }

```

**Comment by sglebs** [comment]
I like @fhoeben 's suggestion. Less code and more versatile. Great!

**Comment by sglebs** [comment]
Great, @fhoeben ! I liked the "This pull request can be automatically merged by project collaborators.". I hope it gets incorporated soon! :)

**Comment by lukeis** [comment]
merged the PR
