### ISSUE TITLE
Selendroid does not open the URL when I use it with Selenium Grid

### ISSUE THREAD

**Issue by JigeshShah** [selendroid/selendroid#893]
Selendroid does not open the URL when I use it with Selenium Grid.Below are the steps that I followed
1) Initated the Grid Hub using the Selendroid Grid Plugin and Selenium Grid Jar
java -Dfile.encoding=UTF-8 -cp "selendroid-grid-plugin-0.15.0.jar;selenium-server-standalone-2.45.0.jar" org.openqa.grid.selenium.GridLauncher -capabilityMatcher io.selendroid.grid.SelendroidCapabilityMatcher -role hub -host 192.168.1.30 -port 4444 

2) Opened the AVD in the VM (i.e. the node)
3)Initated the selendroid node using the below command
java -jar selendroid-standalone-0.15.0-with-dependencies.jar -port 5556 -hub http://192.168.1.30:4444/grid/register -proxy io.selendroid.grid.SelendroidSessionProxy -host 192.168.1.8

Hub IP :  192.168.1.30
Node IP:  192.168.1.8
4) navigate to http:// 192.168.1.30:4444/grid/console – was able to view the node that was added
5) Ran the below script on the Hub Machine. The Selendroid Web View is opening but it is unable to open the URL.PFA Image
package io.selendroid.demo.mobileweb;

import java.net.URL;

import io.appium.java_client.android.AndroidDriver;
import io.selendroid.client.SelendroidDriver;
import io.selendroid.common.SelendroidCapabilities;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

public class SelendroidTestWeb {

	
	@Test
	public void testSel() throws Exception
	{
		
		DesiredCapabilities capability =  DesiredCapabilities.android();
		
		WebDriver driver = new SelendroidDriver(new URL("http://192.168.1.8:5556/wd/hub"), capability);
		

	    driver.get("http://www.store.demoqa.com"); 
	    
		driver.findElement(By.xpath(".//*[@id='account']/a")).click();
		Thread.sleep(10000);
	    driver.findElement(By.id("log")).sendKeys("testuser_1");

	    driver.findElement(By.id("pwd")).sendKeys("Test@123");

	    driver.findElement(By.id("login")).click();
	    // Check the title of the page
	    System.out.println("Page title is: " + driver.getTitle());
	    driver.quit();
	 
	
	}
	
}

Note : I am able to ping among the Hub and Node and there is no firewall issue
![selendroidwebviewjpg](https://cloud.githubusercontent.com/assets/1023945/8145742/b3838af0-1231-11e5-8360-49ef61470d74.jpg)

**Comment by lukeis** [comment]
Please include your stacktrace and output from both hub and node.

**Comment by JigeshShah** [comment]
Seems like its an intermittent issue. Yesterday I tried n no of times it never worked.However it worked today but only twice after that it never worked

Error displayed when I connected Node to Hub

Jun 14, 2015 11:40:45 AM io.selendroid.standalone.server.model.SelendroidStandal
oneDriver getSupportedDevices INFO: Error occurred when building supported device info: null

Complete Log after I ran the scripts
oneDriver createNewTestSession
INFO: 'android' will be used as app under test.
Jun 14, 2015 12:14:52 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Android\android-sdk\platform-too
ls\adb.exe -s emulator-5554 shell input keyevent 82
Jun 14, 2015 12:14:55 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 14, 2015 12:14:55 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Android\android-sdk\platform-too
ls\adb.exe -s emulator-5554 shell input keyevent 4
Jun 14, 2015 12:14:56 PM io.selendroid.standalone.server.model.SelendroidStandal
oneDriver getSupportedDevices
INFO: Error occurred when building supported device info: null
Jun 14, 2015 12:14:59 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 14, 2015 12:14:59 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Android\android-sdk\platform-too
ls\adb.exe -s emulator-5554 shell pm list packages io.selendroid.androiddriver
Jun 14, 2015 12:15:01 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package:io.selendroid.androiddriver
package:io.selendroid.io.selendroid.androiddriver
<--
Jun 14, 2015 12:15:01 PM io.selendroid.standalone.server.model.SelendroidStandal
oneDriver createNewTestSession
INFO: the app under test is already installed.
Jun 14, 2015 12:15:01 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Android\android-sdk\platform-too
ls\adb.exe -s emulator-5554 shell pm list packages io.selendroid.io.selendroid.a
ndroiddriver
Jun 14, 2015 12:15:03 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package:io.selendroid.io.selendroid.androiddriver
<--
Jun 14, 2015 12:15:03 PM io.selendroid.standalone.server.model.SelendroidStandal
oneDriver createNewTestSession
INFO: Not creating and installing selendroid-server because it is already instal
led for this app under test.
Jun 14, 2015 12:15:03 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Android\android-sdk\platform-too
ls\adb.exe -s emulator-5554 shell setprop log.tag.SELENDROID ERROR
Jun 14, 2015 12:15:03 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 14, 2015 12:15:03 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Android\android-sdk\platform-too
ls\adb.exe -s emulator-5554 shell am instrument -e main_activity io.selendroid.a
ndroiddriver.WebViewActivity -e server_port 8082 io.selendroid.io.selendroid.and
roiddriver/io.selendroid.server.ServerInstrumentation
Jun 14, 2015 12:15:05 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 14, 2015 12:15:05 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Android\android-sdk\platform-too
ls\adb.exe -s emulator-5554 forward tcp:8082 tcp:8082
Jun 14, 2015 12:15:05 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jun 14, 2015 12:15:05 PM io.selendroid.standalone.android.impl.AbstractDevice st
artLogging
INFO: starting logcat:
Jun 14, 2015 12:15:05 PM io.selendroid.standalone.server.model.SelendroidStandal
oneDriver waitForServerStart
INFO: Waiting for the Selendroid server to start.
Jun 14, 2015 12:15:05 PM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Checking if the Selendroid server is running: http://localhost:8082/wd/hub
/status
Jun 14, 2015 12:15:05 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8082: Connection reset
Jun 14, 2015 12:15:05 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8082
Jun 14, 2015 12:15:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8082: Connection reset
Jun 14, 2015 12:15:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8082
Jun 14, 2015 12:15:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8082: Connection reset
Jun 14, 2015 12:15:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8082
Jun 14, 2015 12:15:06 PM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Can't connect to Selendroid server, assuming it is not running.
Jun 14, 2015 12:15:08 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Android\android-sdk\platform-too
ls\adb.exe -s emulator-5554 shell echo $EXTERNAL_STORAGE
Jun 14, 2015 12:15:08 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
/storage/sdcard
<--
Jun 14, 2015 12:15:08 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Android\android-sdk\platform-too
ls\adb.exe -s emulator-5554 shell ls C:\storage\sdcard/
Jun 14, 2015 12:15:10 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
C:\storage\sdcard/: No such file or directory
<--
Jun 14, 2015 12:15:10 PM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Checking if the Selendroid server is running: http://localhost:8082/wd/hub
/status
Jun 14, 2015 12:15:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8082: Connection reset
Jun 14, 2015 12:15:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8082
Jun 14, 2015 12:15:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8082: Connection reset
Jun 14, 2015 12:15:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8082
Jun 14, 2015 12:15:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8082: Connection reset
Jun 14, 2015 12:15:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8082
Jun 14, 2015 12:15:10 PM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Can't connect to Selendroid server, assuming it is not running.
Jun 14, 2015 12:15:12 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Android\android-sdk\platform-too
ls\adb.exe -s emulator-5554 shell echo $EXTERNAL_STORAGE
Jun 14, 2015 12:15:12 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
/storage/sdcard
<--
Jun 14, 2015 12:15:12 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Android\android-sdk\platform-too
ls\adb.exe -s emulator-5554 shell ls C:\storage\sdcard/
Jun 14, 2015 12:15:13 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
C:\storage\sdcard/: No such file or directory
<--
Jun 14, 2015 12:15:13 PM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Checking if the Selendroid server is running: http://localhost:8082/wd/hub
/status
Jun 14, 2015 12:15:14 PM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Got response status code: 200
Jun 14, 2015 12:15:14 PM io.selendroid.standalone.android.impl.AbstractDevice is
SelendroidRunning
INFO: Got response value: {"status":0,"value":{"build":{"version":"0.13.0-SNAPSH
OT","browserName":"selendroid"},"os":{"arch":"armeabi-v7a","name":"Android","ver
sion":"22"},"supportedDevices":[],"supportedApps":[]}}
Jun 14, 2015 12:15:14 PM io.selendroid.standalone.server.model.SelendroidStandal
oneDriver waitForServerStart
INFO: Selendroid server has started.

**Comment by JigeshShah** [comment]
Any updates on this? Curios to know whether its a code/design issue or I m doing something wrong on the configuration part

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
