### ISSUE TITLE
Unfortunately google play services has stopped.

### ISSUE THREAD

**Issue by 5654566** [selendroid/selendroid#896]
Hi I am new in selendroid. I have installed google play store in emulator and tried to run my code on emulator, i am getting error 'Unfortunately google play services has stopped' and my application is crashed...

If any one help me to solve this...

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
