### ISSUE TITLE
ADB Wifi - Devices are not handling the server connection

### ISSUE THREAD

**Issue by atobulredy** [selendroid/selendroid#905]
Hi,

Selendroid standalone jar is killing adb wifi device connection

Before I start the server I have connected device through adb wifi via IP address.

List of devices attached:

10.212.**:5555 device

After selendroid server gets started it's killing adb wifi connection.

It would very helpful if some one can add points on how to use adb wifi connection with the selendroid.

Hoping, for quick response.

Thanks in Advance !!!

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
