### ISSUE TITLE
selendroid driver.context("WEBVIEW_0") WEBVIEW prompt(‘runNativeMethod’,’aaaa’) WebChromeClient's onJsPrompt is not run but run window.prompt

### ISSUE THREAD

**Issue by xiaolvgirl** [selendroid/selendroid#908]
I use selendroid test the hybrid app.
But test the custom webview,it not work.
Because the custom webview use setWebChromeClient and onJsPrompt.
The page use javascript run prompt,
&lt;input type=”button” id=”btn” onclick=”prompt(‘runNativeMethod’,’aaaa’)” /&gt;
When I use driver.context(“WEBVIEW_0”)
Driver.executescript(“document.getElementById(‘btn’).click;”);
The button don’t run to onJsPrompt ,but run to window.prompt.
Why?

**Comment by lukeis** [comment]
instead of executing javascript directly to click, did you try:

    driver.findElement(By.Id("btn")).click();

**Comment by xiaolvgirl** [comment]
sorry , my issue is the button is clicked,but run prompt is window.prompt (javascript),not in to WebChromeClient's onJsPrompt

**Comment by xiaolvgirl** [comment]
sorry , my issue is the button is clicked,but run prompt is window.prompt (javascript),not in to WebChromeClient's onJsPrompt

---------------------------------------------------------------------------------------------------
Confidentiality Notice: The information contained in this e-mail and any accompanying attachment(s) 
is intended only for the use of the intended recipient and may be confidential and/or privileged of 
Neusoft Corporation, its subsidiaries and/or its affiliates. If any reader of this communication is 
not the intended recipient, unauthorized use, forwarding, printing,  storing, disclosure or copying 
is strictly prohibited, and may be unlawful.If you have received this communication in error,please 
immediately notify the sender by return e-mail, and delete the original message and all copies from 
your system. Thank you. 
---------------------------------------------------------------------------------------------------

**Comment by operatiay** [comment]
what happens when you click the button? is your javascript being executed in onJsPrompt (whatever it is)?

**Comment by xiaolvgirl** [comment]
I test a apk .
the apk's activity use webview.
wView.setWebChromeClient(new MyWebChromeClient());
public class MyWebChromeClient extends WebChromeClient {
public boolean onJsPrompt(WebView view, String url, String message,
			String defaultValue, final JsPromptResult result) {
the page has a button code is:
&lt;input type=”button” id=”btn” onclick=”prompt(‘runNativeMethod’,’aaaa’)” /&gt;
but i use selendroid
selendroiddriver.swithto.window("WEB_VIEW0") OR
webdriver.context("WEB_VIEW0")
I click the button in the page.
it not not run into onJsPrompt.
but run javascript's window.prompt

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
