### ISSUE TITLE
Update atoms

### ISSUE THREAD

**Issue by asm89** [selendroid/selendroid#925]
Seems we haven't updated the https://github.com/selendroid/selendroid/blob/master/selendroid-server/src/main/java/io/selendroid/server/model/js/AndroidAtoms.java file in quite a while. I couldn't find documentation on how to do this.

@DominikDary @lukeis Can any of you help out here?

**Comment by lukeis** [comment]
I left some documentation on how to do this here:

https://github.com/selendroid/selendroid/wiki/AndroidAtoms

will do this again now...

**Comment by lukeis** [comment]
done now:  16fc551912704af054c8ce105b8d83c09e29b085
