### ISSUE TITLE
Failure to run selendroid-standalone-0.15.0-with-dependencies.jar

### ISSUE THREAD

**Issue by LarryWu** [selendroid/selendroid#934]
Hi,

I have problem when I running this command:
java -jar selendroid-standalone-0.15.0-with-dependencies.jar -app selendroid-test-app-0.15.0.apk 

I had successfully executed days ago, but i'm not sure why I encounter this error recently.
I already checked my JAVA_HOME and ANDROID_HOME which are both configured.
Here is my check point on my MAC:
echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home

echo $ANDROID_HOME
/Users/Larry_Wu/Library/Android/sdk

Please help it!! Thanks!

Here is the error log:
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.SelendroidLauncher launchServer
資訊: Starting Selendroid standalone on port 4444
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.io.ShellCommand exec
資訊: Executing shell command: /Users/Larry_Wu/Library/Android/sdk/platform-tools/aapt remove /Users/Larry_Wu/Documents/Software/selendroid/selendroid-test-app-0.15.0.apk META-INF/MANIFEST.MF
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.io.ShellCommand exec
資訊: Executing shell command: /Users/Larry_Wu/Library/Android/sdk/platform-tools/aapt remove /Users/Larry_Wu/Documents/Software/selendroid/selendroid-test-app-0.15.0.apk META-INF/CERT.RSA
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.io.ShellCommand exec
資訊: Executing shell command: /Users/Larry_Wu/Library/Android/sdk/platform-tools/aapt remove /Users/Larry_Wu/Documents/Software/selendroid/selendroid-test-app-0.15.0.apk META-INF/CERT.SF
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.io.ShellCommand exec
資訊: Executing shell command: /Users/Larry_Wu/Library/Android/sdk/platform-tools/aapt remove /Users/Larry_Wu/Documents/Software/selendroid/selendroid-test-app-0.15.0.apk META-INF/ANDROIDD.SF
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.io.ShellCommand exec
資訊: Executing shell command: /Users/Larry_Wu/Library/Android/sdk/platform-tools/aapt remove /Users/Larry_Wu/Documents/Software/selendroid/selendroid-test-app-0.15.0.apk META-INF/ANDROIDD.RSA
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.io.ShellCommand exec
資訊: Executing shell command: /Users/Larry_Wu/Library/Android/sdk/platform-tools/aapt remove /Users/Larry_Wu/Documents/Software/selendroid/selendroid-test-app-0.15.0.apk META-INF/NDKEYSTO.SF
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.io.ShellCommand exec
資訊: Executing shell command: /Users/Larry_Wu/Library/Android/sdk/platform-tools/aapt remove /Users/Larry_Wu/Documents/Software/selendroid/selendroid-test-app-0.15.0.apk META-INF/NDKEYSTO.RSA
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.io.ShellCommand exec
資訊: Executing shell command: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/jarsigner -sigalg MD5withRSA -digestalg SHA1 -signedjar /Users/Larry_Wu/Documents/Software/selendroid/resigned-selendroid-test-app-0.15.0.apk -storepass android -keystore /Users/Larry_Wu/.android/debug.keystore /Users/Larry_Wu/Documents/Software/selendroid/selendroid-test-app-0.15.0.apk androiddebugkey
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.io.ShellCommand exec
資訊: Shell command output
-->
jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2045-04-27) or after any future revocation date.
<--
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
資訊: App signing output: jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2045-04-27) or after any future revocation date.
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
資訊: The app has been signed: /Users/Larry_Wu/Documents/Software/selendroid/resigned-selendroid-test-app-0.15.0.apk
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.io.ShellCommand exec
資訊: Executing shell command: /Users/Larry_Wu/Library/Android/sdk/platform-tools/aapt dump badging /Users/Larry_Wu/Documents/Software/selendroid/resigned-selendroid-test-app-0.15.0.apk
七月 02, 2015 4:59:23 下午 io.selendroid.standalone.SelendroidLauncher launchServer
嚴重: Error building server: The base package name of the apk resigned-selendroid-test-app-0.15.0.apk cannot be extracted.
Exception in thread "main" io.selendroid.server.common.exceptions.SelendroidException: The base package name of the apk resigned-selendroid-test-app-0.15.0.apk cannot be extracted.
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.getBasePackage(DefaultAndroidApp.java:68)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.getAppId(DefaultAndroidApp.java:139)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:129)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:65)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:54)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
