### ISSUE TITLE
Gradle build fails - update xalan

### ISSUE THREAD

**Issue by galaxyfreak** [selendroid/selendroid#946]
Gradle is throwing bad UTF-8 byle 9e at offset 00000002 from org/apache/xalan/res/XSLTErrorResources_ru.class.

http://stackoverflow.com/questions/20836047/xalan-jar-error-when-build-in-android-project claims to be fixed in Xalan 2.7.2

**Comment by DominikDary** [comment]
the main question is, what dependency is adding it, because from what i have seen we have not added it.

**Comment by galaxyfreak** [comment]
Selendroid Standalone -> selenium-java -> selenium-htmlunit-driver -> xalan

**Comment by lukeis** [comment]
i've excluded that dependency for now then :)

**Comment by DominikDary** [comment]
@galaxyfreak can you verify on the snapshot build that it works fine for you?

**Comment by galaxyfreak** [comment]
@DominikDary  Please could you build jar to be sure? I did, but size is about half of 0.16 release, and init example is not actually working (crash), so I assume I'm missing something, as I never used Maven before.

**Comment by lukeis** [comment]
@galaxyfreak it's here:
http://oss.sonatype.org/content/repositories/snapshots/io/selendroid/selendroid-standalone/0.17.0-SNAPSHOT/

**Comment by galaxyfreak** [comment]
@lukeis so my build is fine, size did decrease much in latest changes.

Well, my issue is sorted but I'd like to get it up and running for a start.

Logcat: http://pastebin.com/NEWKVuhP
Code: http://pastebin.com/FM6QgXTk

Fails on driver = new SelendroidDriver(caps);

**Comment by lukeis** [comment]
what device or emulator are you running this on?

"java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.concurrent.atomic.AtomicBoolean.compareAndSet(boolean, boolean)' on a null object reference"

implies it couldn't find that method which is provided by the Android API library... which would imply you're not running in a proper android environment?

**Comment by galaxyfreak** [comment]
Sony Xperia Z3, Android 5.0.2

**Comment by lukeis** [comment]
so, that's lollipop... the error makes no sense to me, why would it think a core library isn't available. Something might be funky with that device?

Can you test against an emulator?

**Comment by galaxyfreak** [comment]
@lukeis tested, same error.

**Comment by lukeis** [comment]
i'm now entirely confused... what are you building with gradle and why is it including selendroid? Can you give us a way to reproduce the issue?

**Comment by galaxyfreak** [comment]
Nothing yet. Step by step. that onCreate code is only code I have for now.

**Comment by galaxyfreak** [comment]
How do you run it? From what I see, you can't use stock httpclient on Android, but have to use android port. Yet you have httpclient in all POM files..
