### ISSUE TITLE
Selendroid Selenium grid android test couldn't find element

### ISSUE THREAD

**Issue by ken4ward** [selendroid/selendroid#950]
I am trying to run a test on 2 android devices. Though, being in the preliminary stage of learning mobile testing I limited my test for now to only one device, just to make sure I'm able to connect via Selenium Grid to the device which has been successful. Running the test make me raise this question. These are my config setups:

Setup for Selendroid standalone:

java -jar selendroid-standalone-0.15.0-with-dependencies.jar -app C:\Selenium\RemoteHub\selendroid-test-app-0.15.0.apk -port 5544
Setup for Selendroid-grid:

java -Dfile.encoding=UTF-8 -cp "selendroid-grid-plugin-0.15.0.jar;selenium-server-standalone-2.46.0.jar" org.openqa.grid.selenium.GridLauncher -capabilityMatcher io.selendroid.grid.SelendroidCapabilityMatcher -role hub -host 127.0.0.1 -port 4545
Setup fornode json file:

{
  "capabilities": [{
      "browserName": "selendroid",
      "maxInstances": 1,
      "aut": "io.selendroid.testapp:0.15.0",
      "OS":"ANDROID"
  }, {
      "browserName": "android",
      "maxInstances": 1
  }],
  "configuration": {
      "maxSession": 1,
      "register": true,
      "hubHost": "localhost",
      "hubPort": 4545,
      "remoteHost": "http://localhost:5544",
      "proxy": "io.selendroid.grid.SelendroidSessionProxy"
  }
}
This is the curl code to connect node to grid

curl -H "Content-Type: application/json" -X POST --data @L60-Node-Config.json http://localhost:4545/grid/register
The configurations work properly because I have been able to see the node as connected to the Selenium grid on the browser.

I wrote this script in Eclipse to test an app. This is the code:

static WebDriver driver;

    public static void main(String[] args) throws Exception {
        SelendroidConfiguration config = new SelendroidConfiguration();

        //config.addSupportedApp(app);
        config.setPort(5602);
        config.setSessionTimeoutSeconds(300000);
        SelendroidLauncher launch = new SelendroidLauncher(config);
        launch.launchSelendroid();

        DesiredCapabilities caps = SelendroidCapabilities.android();
        caps.setBrowserName("android");

        caps.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
        caps.setCapability("port", "5544");
        caps.setVersion("4.2.2");
        caps.setCapability("serverStartTimeout", "30000");
        caps.setCapability("mainActivity", "io.selendroid.testapp.HomeScreenActivity");
        caps.setCapability("basePackage", "io.selendroid.testapp");
        caps.setCapability("browserName", "android");
        caps.setCapability("targetVersion", "0.15.0");
        caps.setCapability("platformVersion", "17");
        caps.setCapability("model", "L60");
        caps.setCapability("emulator", false);
        caps.setCapability("serial", "0123456789ABCDEF");

        driver = new SelendroidDriver(new URL("http://localhost:5544/wd/hub"), caps);
        driver.switchTo().window("NATIVE_APP");
        System.out.println("Context handles = " +((SelendroidDriver) driver).getContextHandles());

        WebElement inputField = driver.findElement(By.id("my_text_field"));

        inputField.sendKeys("Selenium");

 }
Whenever I run this test it opens - "AndroidDriver Webview App", a different app from the one I set to test which is "selendroid-test-app-0.15.0". Because of this I try to set the context to "NATIVE_APP" but it returns the same app, it is for the reason that the test fails by not seeing the element specified.

This is the error log:

Jul 29, 2015 2:00:17 PM io.selendroid.standalone.SelendroidLauncher launchServer
INFO: Starting Selendroid standalone on port 5602
Jul 29, 2015 2:00:18 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\ken4ward\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe remove C:\Users\ken4ward\AppData\Local\Temp\android-driver4336468193036324988.apk META-INF/MANIFEST.MF
Jul 29, 2015 2:00:18 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jul 29, 2015 2:00:18 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\ken4ward\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe remove C:\Users\ken4ward\AppData\Local\Temp\android-driver4336468193036324988.apk META-INF/CERT.RSA
Jul 29, 2015 2:00:18 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jul 29, 2015 2:00:18 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\ken4ward\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe remove C:\Users\ken4ward\AppData\Local\Temp\android-driver4336468193036324988.apk META-INF/CERT.SF
Jul 29, 2015 2:00:19 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jul 29, 2015 2:00:19 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\ken4ward\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe remove C:\Users\ken4ward\AppData\Local\Temp\android-driver4336468193036324988.apk META-INF/ANDROIDD.SF
Jul 29, 2015 2:00:19 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\ken4ward\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe remove C:\Users\ken4ward\AppData\Local\Temp\android-driver4336468193036324988.apk META-INF/ANDROIDD.RSA
Jul 29, 2015 2:00:19 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\ken4ward\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe remove C:\Users\ken4ward\AppData\Local\Temp\android-driver4336468193036324988.apk META-INF/NDKEYSTO.SF
Jul 29, 2015 2:00:19 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\ken4ward\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe remove C:\Users\ken4ward\AppData\Local\Temp\android-driver4336468193036324988.apk META-INF/NDKEYSTO.RSA
Jul 29, 2015 2:00:19 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Java\jdk1.7.0_17\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\ken4ward\AppData\Local\Temp\resigned-android-driver4336468193036324988.apk -storepass android -keystore C:\Users\ken4ward\.android\debug.keystore C:\Users\ken4ward\AppData\Local\Temp\android-driver4336468193036324988.apk androiddebugkey
Jul 29, 2015 2:00:20 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
