### ISSUE TITLE
Hybrid By.linktext is not working

### ISSUE THREAD

**Issue by Jacob15** [selendroid/selendroid#951]
Hi-

I am trying to automate a hybrid app. After switching to webview need to click a link text there. By using by.linktext(text) selendroid is not working. But same with using xpath its working.
Did any one faced this kind of issue earlier?

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
