### ISSUE TITLE
Command "aapt remove" leads to INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION

### ISSUE THREAD

**Issue by chunrong** [selendroid/selendroid#954]
I tried on com.artifex.mupdfdemo.apk which is downloaded from google play.

If I resign this apk directly and then install, it will success.
But if I use selendroid, it cannt install with "INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION".

Thx

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by manjugb** [comment]
I am getting an exception while aapt will remove tmp file
aapt remove /tmp/android-driver5026474350596886785.apk META-INF/ANDROIDD.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
