### ISSUE TITLE
Issue when I try with an emulated device to open an HTTPS website with a proxy configured on the emulator

### ISSUE THREAD

**Issue by jboffel** [selendroid/selendroid#955]
Hello,

I'm not sure of the origin of the problem honestly, I use an emulated device Android 3.2 (API level 13) and I defined a proxy to be used by the emulator.

If I wget through the proxy the given HTTPS url, no matter the certificate is trusted or not I can access the page by asking wget to not check certificate.

By using selendroid, HTTP website have no problem but HTTPS will fail regardless of the certificate is trusted or not. I just get Webpage not available.

Any idea of the problem?

Thanks!

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
