### ISSUE TITLE
jarsigner wrong path

### ISSUE THREAD

**Issue by vinnitu** [selendroid/selendroid#957]
SEVERE: Error building server: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /usr/lib/jvm/java-8-oracle/jre/bin/jarsigner -sigalg MD5withRSA -digestalg SHA1 -signedjar /tmp/resigned-android-driver7178561189916122391.apk -storepass android -keystore /home/victor/.android/debug.keystore /tmp/android-driver7178561189916122391.apk androiddebugkey

but

$ whereis jarsigner
jarsigner: /usr/bin/jarsigner /usr/bin/X11/jarsigner /usr/share/man/man1/jarsigner.1.gz

**Comment by lukeis** [comment]
jarsigner is not typically on the PATH. Selendroid depends on JAVA_HOME pointing to a JDK path and not a JRE
