### ISSUE TITLE
How to Put app in Background and reLaunch again

### ISSUE THREAD

**Issue by suyash786** [selendroid/selendroid#974]
Hi ,

I am using Selendroid version selendroid-standalone-0.16.0-with-dependencies
Please advice is there any way to Put app in Background and bring the app again in Foreground
I am very new to Selendroid . Any help here will be highly appreciated .

Regards ,
Suyash Jain

**Comment by operatiay** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
