### ISSUE TITLE
Question regarding Forcereinstall

### ISSUE THREAD

**Issue by madiska** [selendroid/selendroid#994]
**Question**

I'm testing an app with several versions. (1.0.1, 1.0.2 and so on)
Currently when I run my testsuite. It works fine for the first time. When I wanna run it again from the start I will get 

io.selendroid.standalone.exceptions.AndroidSdkException: APK installation failed. Output:
pkg: /data/local/tmp/resigned-1.0.1.apk
Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
4205 KB/s (45840416 bytes in 10.645s)

Error. Here is my question. Is forcereinstall supposed to uninstall the app before running the server or it doesn't work like that. Currently I end up manually uninstalling the app.

**Comment by lukeis** [comment]
yeah, i think it's an issue that the force reinstall just tries to use adb's mechanism for re-installing rather than uninstall / install.

**Comment by madiska** [comment]
Okay. Guess ill try to do a workaround which run adb uninstall before the suite or something like that. Cheers
